### ISSUE TITLE
Deprecated packages being used

### ISSUE THREAD

**Issue by arimourao** [humhub/humhub#2132] opened 2016-12-03 19:48 UTC
After solving #2130 and #2131 composer throws the following warning:
`Package yiisoft/yii2-codeception is abandoned, you should avoid using it. Use codeception/codeception instead.
`

**Comment by cebe** [comment] 2016-12-03 20:12
duplicate of #2068. Please use the issue search on github before opening new issues.

**Closed** 2016-12-05 10:39 UTC
