### ISSUE TITLE
Tooltips! 

### ISSUE THREAD

**Issue by cagatayldzz** [humhub/humhub#1337] opened 2015-11-27 17:20 UTC
![12274252_1509558269371891_3852030327469960113_n](https://cloud.githubusercontent.com/assets/7725575/11446060/24b47a06-952a-11e5-832c-928bbe08c18b.jpg)
Tooltips!
and
![3](https://cloud.githubusercontent.com/assets/7725575/11446070/3e912956-952a-11e5-8b5e-953cecfe8590.png)
less than a minute ago  (http://translate.humhub.org/ module name ?)

Humhub Version: 1.0.0-beta.1

**Comment by programguy** [comment] 2015-11-27 17:25
This was broken in the 0.2 releases of HumHub also.

**Comment by programguy** [comment] 2015-11-27 17:25
Duplicate of #1335

**Closed** 2015-12-15 04:47 UTC
