### ISSUE TITLE
Space switcher iOS 8 landscape

### ISSUE THREAD

**Issue by jelofson** [humhub/humhub#655] opened 2015-01-28 05:29 UTC
When trying to switch spaces on my iPad 3 in landscape mode, tapping on the bottom space in the list triggers the create new space dialog. I only have two spaces at the moment. Tapping the first space works fine. Explicitly tapping on create new space does nothing. In portrait mode, it's fine. Version 0.10.0

**Comment by jelofson** [comment] 2015-01-28 05:45
This appears to be triggered by the virtual keyboard. Because the search box always has focus, but the keyboard may not appear unless you scroll. If I close the keyboard, then tap the space it works. Or close the keyboard, the open it again, it works.

**Comment by andystrobel** [comment] 2015-03-24 11:13
I can't reproduce it. I think it's fixed in combination with other modifications.

**Closed by andystrobel** 2015-03-24 11:13 UTC
Labels: Component:Frontend, Status:Need to be confirmed, Type:Bug
