### ISSUE TITLE
Private Messenging | No User selectable as recipient

### ISSUE THREAD

**Issue by LoriSan** [humhub/humhub#1976] opened 2016-09-02 12:48 UTC
Hey there,

since the last update, i'm running into some strange issue.

When i try to create a new private message, the system shows up with the name i searched for but the name is not selectable anymore (Please see screenshot attached)

I did not change any option in the backend and theres no popup blocker or noscript thing activated for that site.

The Logfiles also show no hint on this activity.

What could be the blocker at this place?

Thanks in advance
- Dominik
  ![pm1](https://cloud.githubusercontent.com/assets/21943402/18204298/4a8b758a-711c-11e6-8fa7-19921a7b2ad5.jpg)

**Comment by buddha87** [comment] 2016-09-02 13:59
Hi which humhub version and mail module version are you using? And do you have the friendship system activated?

**Comment by LoriSan** [comment] 2016-09-02 15:03
Hello buddha87,

friendship system is ebabled with HumHub 1.1.0 and Mail Version 0.9.2

Best regards,
Dominik

**Comment by 001101** [comment] 2016-09-02 16:52
Having the same issue, it's because of the friendship system, the bug was marked as solved for 1.1.0-stable, but it not working for you and me either.

You have to disable friendship system, otherwise only friends can message itself, which is annoying, and even admins can't send to anybody.

**Comment by LoriSan** [comment] 2016-09-02 18:42
Theres a similar answer ins the community hub:

> If the friendship system is activated users have to allow other users to send messages in theire security settings. If you are system admin you can use the Profile -> Send Message button to send messages which is currently just a workaround to be able to send messages to everyone as system admin.

Is there a chance to set the default value to allow tho? Or make it at least configurable?

**Comment by buddha87** [comment] 2016-09-05 12:16
Its not a bug, it's the default user permission setting when the friendship system is enabled.

**Comment by 001101** [comment] 2016-09-05 23:14
It's a usability bug

**Closed** 2019-01-16 16:20 UTC
