### ISSUE TITLE
Numeration in summary is wrong

### ISSUE THREAD

**Issue by jdepi** [humhub/humhub#5814] opened 2022-07-25 20:51 UTC
### What steps will reproduce the problem?
Enter a post, in which you use dates as numeration. Example:
21. November ....
22. November ....
23. November ...

### What is the expected result?
All users which get a summary of all unread messages via email should see these dates in the summary.

### What do you get instead?
In the summary you can read:
1. November ...
2. November ...
3. November ...
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.11.4
| PHP version      | v7.4.30
| Operating system | Ubuntu

**Comment by luke-** [comment] 2022-07-26 17:21
Is this about the content of a normal post. What are you entering exactly?

**Comment by jdepi** [comment] 2022-07-26 17:48
Hi Luke,
yes, it is a normal post. The summary was received by a colleague. I entered 21. November and a text. When I pressed enter, the following bullet was set automatically to 22. I entered text again plus enter. The third bullet point was named 23., automatically.

**Comment by yurabakhtin** [comment] 2022-07-27 08:58
@luke- I cannot reproduce this:

![test-list](https://user-images.githubusercontent.com/6995524/181206623-1debac53-b60d-4de8-95dc-9501d7e340ab.png)

**Comment by ralfblask** [comment] 2022-08-03 11:47
Try
21.[SHIFT]+[SPACE]November

**Comment by jdepi** [comment] 2022-08-03 11:51
Hi everybody,
the editor itself works fine. I confirm all steps above.
In the evening, all space members get an email with a summary from the platform with this content, but: the numeration in this summary is wrong: 1., 2., 3., instead of 21., 22., 23.
Because of handling dates, all readers get wrong dates in the summary.

**Comment by yurabakhtin** [comment] 2022-08-03 15:52
Yes, in **Mail** Summary it is reproduced:

![mail-summary](https://user-images.githubusercontent.com/6995524/182652431-74f80fa8-fed2-4ac0-ac62-1897afbe9674.png)

I will try to find a solution.

---

The text is rendered there with code:

```php
RichText::preview($text, 0, [
    RichTextToShortTextConverter::OPTION_CACHE_KEY => RichTextToShortTextConverter::buildCacheKeyForContent($post)
])
```

in web mode it is rendered with code:

```php
RichText::output($post->message, ['record' => $post])
```

**Comment by jdepi** [comment] 2022-08-03 15:58
Yes, that's the issue! Thanks Yuriy.

**Comment by luke-** [comment] 2022-08-03 16:10
Maybe we can replace newlines with a space?

**Comment by yurabakhtin** [comment] 2022-08-03 16:39
@jdepi @ralfblask @luke- Fixed in PR https://github.com/humhub/humhub/pull/5828:

![mail-summary-after-fix](https://user-images.githubusercontent.com/6995524/182662754-5ed5e52c-76af-4d37-8e08-a103288aec52.png)

**Comment by luke-** [comment] 2022-08-05 13:33
@yurabakhtin Thanks looks good. Can you please see my PR comment?

**Closed** 2022-08-08 09:38 UTC
Labels: Status:Need more information
