### ISSUE TITLE
iOS Posting and Display Issues 1.4.0-beta.1

### ISSUE THREAD

**Issue by geekaroni** [humhub/humhub#3747] opened 2019-11-19 14:55 UTC
When trying to post a status on the new 1.4.0-beta.1 version, the text field covers the whole screen making it impossible to find buttons or add photos. https://i.imgur.com/SrhAecf.mp4

**Comment by luke-** [comment] 2019-11-23 20:40
Duplicate of #3711

**Closed by luke-** 2019-11-23 20:40 UTC
