### ISSUE TITLE
Password field should not be required if user has no password

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#5182] opened 2021-07-21 09:17 UTC
### What steps will reproduce the problem?

Create a user without password (e.g that login only with an SSO).
Login with this user and try to change email : the current password is required.

Cause: User hasPassword function doesn't work.

I will send a PR fixing this issue.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.9-beta2

**Comment by funkycram** [comment] 2021-07-21 09:37
I don't know why, but I cannot create a PR of my commit: https://github.com/funkycram/humhub/commit/ca12ddee03e058478926089a78b12b13c138a70f

**Comment by luke-** [comment] 2021-07-21 16:10
@funkycram Hmm good question. Does the commit check if there is a "CurrentPassword" table entry with an empty password?

**Comment by funkycram** [comment] 2021-07-21 16:18
The `return ($user->currentPassword !== null && $user->currentPassword->currentPassword !== null);` check if there is a "CurrentPassword" table (`user_password`) entry yes (this was already the case), but also if the password is not null. If both conditions are true, the user has a password set.
Before this commit, a user could have an entry in the `user_password` table but with a `password` field set to null and the `hasPassword` function was returning true. This was not correct. That's why I suggest to check also if the `password` field is not null.
Perhaps we could replace `&& $user->currentPassword->currentPassword !== null` with `&& !$user->currentPassword->currentPassword` in case the password value is a string: ''

**Comment by luke-** [comment] 2021-07-21 16:29
Actually, no entries with empty passwords should be created in the `userPassword` table.
We should also look for the bug behind this. Otherwise we can still work with `empty()` here.

**Comment by funkycram** [comment] 2021-07-21 16:33
Well, I do have empty passwords when a user creates his account with an SSO:
![image](https://user-images.githubusercontent.com/23310825/126525456-96605fb0-ab34-4cdb-8e48-e725cddd5089.png)

Yes, `return !empty($user->currentPassword->currentPassword);` would be fine to.

**Comment by luke-** [comment] 2021-07-21 16:41
Yes, but can you reproduce when the Password records are created? I think we should disable the creation of empty password records.

**Comment by funkycram** [comment] 2021-07-21 17:06
@luke- https://github.com/humhub/humhub/pull/5185

Yes, as soon as I have time, I'll try to found when the Password records are created.

**Comment by luke-** [comment] 2021-07-21 17:51
Great, thank you. Let me now when we can help. 

We should then also create a migration which deletes the empty user_password db records.

**Comment by luke-** [comment] 2021-07-21 18:13
@funkycram Seems there is a problem with the current tests:
https://github.com/humhub/humhub/runs/3126774327?check_suite_focus=true#step:21:1365

Can you please check?

**Comment by funkycram** [comment] 2021-07-21 19:13
The error message is `Field by name, label, CSS or XPath element with '#accountchangeemail-currentpassword' was not found.`
It is not related to the PR.

**Comment by ArchBlood** [comment] 2021-07-21 22:28
Question, why is `#accountchangeemail-currentpassword` being used if you're checking the field `#accountchangeemail-currentPassword`?

So in this case something similar to the following?

```php
<?php

namespace user\acceptance;

use user\AcceptanceTester;
use tests\codeception\_pages\AccountSettingsPage;
use \Codeception\Step\Argument\PasswordArgument;

class ChangeEmailCest
{
    public function testChangeEmail(AcceptanceTester $I)
    {
        $I->wantTo('ensure that changing email works');

        $I->amGoingTo('change email address');
        $I->amUser();
        $I->clickAccountDropDown();
        $I->click('Account settings');
        $I->waitForElementVisible('#profile-tabs', 20);
        $I->expectTo('see the profile edit form');

        $I->waitForElementVisible('.nav-tabs', 20);
        $I->click('Change Email');
        $I->waitForText('Your current E-mail address is');

        $I->amGoingTo('fill only new email');
        $I->fillField('#accountchangeemail-newemail[email]', 'old@email.com');
        $I->fillField('accountchangeemail-currentPassword', '');

        $I->scrollToBottom();
        $I->click('save');
        $I->wait(1);
        $I->expectTo('see an error');
        $I->see('Current password cannot be blank.');

        $I->amGoingTo('fill password and not valid new email');
        $I->fillField('#accountchangeemail-newEmail[email]', 'new@email.com');
        $I->fillField('accountchangeemail-currentPassword', new PasswordArgument('123abc'));

        $I->scrollToBottom();
        $I->click('save');
        $I->wait(1);
        $I->expectTo('see an error');
        $I->see('New E-Mail address is not a valid email address.');

        $I->amGoingTo('fill all required fields with valid data');
        $I->fillField('#accountchangeemail-newEmail[email]', 'new@email.com');
        $I->fillField('accountchangeemail-currentPassword', new PasswordArgument('123abc'));

        $I->scrollToBottom();
        $I->click('save');
        $I->wait(1);
        $I->expectTo('see no errors after saving');
        $I->dontSee('Current password cannot be blank.');
        $I->dontSee('New E-Mail address is not a valid email address.');
        $I->wait(5);
        $I->see('We´ve just sent an confirmation e-mail to your new address.');
    }

}
```

**Comment by luke-** [comment] 2021-07-22 09:09
@yurabakhtin Can you please help here to fix the in the `master` branch?

**Comment by yurabakhtin** [comment] 2021-07-22 12:28
@luke- Fixed in PR https://github.com/humhub/humhub/pull/5186.
The problem was in the original PR https://github.com/humhub/humhub/pull/5185/files#diff-8e9e361bbd64c6e578b6c76dab8ef23ef20c6b0767b461a8a658e36d82a0a5daR60 because we cannot use property `$currentPassword` of the class `Password`, this property is filled only after form submit, so we should use `$password` instead, because this property contains a value from DB.

**Comment by funkycram** [comment] 2021-07-22 13:31
Thanks @yurabakhtin !

**Closed** 2021-07-22 13:59 UTC
Labels: Kind:BUG
