### ISSUE TITLE
Multiple like buttons with symbols

### ISSUE THREAD

**Issue by olantrust** [humhub/humhub#3918] opened 2020-03-13 02:56 UTC
Other messaging and workflow systems use thumbs up as a like symbol, but also have a heart symbol, tears, 'wow', angry, and a smile for example. This would help users significantly - saving typing when a symbol would convey all and take less space.

**Comment by acheype** [comment] 2020-09-09 16:28
We need also that functionality, not to show some emotion symbols but to select some posts or comments. In our case, we would like an 'book' icon to tell the space members that we think this information could be capitalize in the 'wiki' tab (module wiki of humhub).

So if you consider to develop the functionality, please make it configurable as the admins could choose 1) which icons they offer to the users  2) which messages are displayed to the users on hover these icons

**Comment by buddh4** [comment] 2020-09-14 16:33
@acheype couldn't you use a topic for this? Topics can't be assigned to comments but at least at content level.

**Comment by acheype** [comment] 2020-09-14 18:28
@buddh4 I'm not sure to understand. Do you need another topic ? To me, it was just to show my interest about this "Multiple like buttons" functionality by citing an use case example !

**Comment by buddh4** [comment] 2020-09-14 19:45
No I just thought you may could use the topic feature to mark/tag your content for your use-case, perhaps I misunderstood your use-case.

**Comment by ArchBlood** [comment] 2020-09-14 20:50
Wouldn't this fall under the reactions issue?

**Comment by Carl2213** [comment] 2020-09-15 00:07
#2415

**Comment by buddh4** [comment] 2020-09-30 10:22
Duplicate of https://github.com/humhub/humhub/issues/2415

**Closed by buddh4** 2020-09-30 10:22 UTC
Labels: Kind:Enhancement, Topic:Social, Topic:Usability
