### ISSUE TITLE
GUID Displayed in Email HTML

### ISSUE THREAD

**Issue by miqrogroove** [humhub/humhub#5046] opened 2021-04-27 02:30 UTC
I received an email from my HumHub site with three oddly different messages.

```
Subject: <user> just mentioned you in comment "Cool@<me>(<url>)"

Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<user> mentioned you in comment "Cool<url>".


Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<p>Coolmention:6db1cec2-028a-4aaa-80a6-754bc6c13af6</p>
```

It's that last one displayed in my email client for the body of the message.  Why am I seeing that?

| Q                | A
| ---------------- | ---
| HumHub version   | 1.8.1
| PHP version      | 7.4.16
| Operating system | Ubuntu

**Comment by luke-** [comment] 2021-04-27 11:28
@yurabakhtin Can you please take a look here?

**Comment by yurabakhtin** [comment] 2021-04-30 13:52
@luke- I cannot understand why the email client displays the content as body, probably some bug of the email client, or some char from the comment content breaks it.

@miqrogroove Could you provide us the full text of the comment so we will test this? Is the `Cool@<me>(<url>)` full comment or did you removed from there?

My testing:
<img width="925" alt="test_mentioning" src="https://user-images.githubusercontent.com/6995524/116704666-5938fd00-a9d4-11eb-98d3-3cc8f4cb484b.png">

**Comment by miqrogroove** [comment] 2021-04-30 14:27
```
mysql> SELECT message FROM comment WHERE id = 107;
+-------------------------------------------------------------------------------+
| message                                                                       |
+-------------------------------------------------------------------------------+
| Cool![Robert Chapin](mention:6db1cec2-028a-4aaa-80a6-754bc6c13af6 "/u/robc/") |
+-------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by yurabakhtin** [comment] 2021-05-03 15:24
@miqrogroove Thank you foe the comment source.

@luke- It seems the `class MentioningExtension extends RichTextLinkExtension` tries to render the mention code with sign `!` before it as image, I think we should try to parse this as image only for extension `file-guid`, and don't parse others like `mention`, `oembed`, do you agree?

<img width="1041" alt="test_mention" src="https://user-images.githubusercontent.com/6995524/116896275-bf27bd80-ac3c-11eb-8a65-e2ac0df3f61b.png">

**Comment by luke-** [comment] 2021-05-04 11:56
@yurabakhtin Just to make sure I understand it correctly: Currently the Mentioning/Link is incorrectly recognized as an image because of the missing space and the "!" character.

Solution would be not to recognize images if there is a "mention:" or "oembed:" in the src ()?

**Comment by yurabakhtin** [comment] 2021-05-04 12:23
@luke- Yes, you have understood this correctly.

**Comment by luke-** [comment] 2021-05-04 12:31
@yurabakhtin Ok, sounds like a good solution. Will you do a PR on this when you get a chance?

**Comment by yurabakhtin** [comment] 2021-05-05 08:55
@luke- I have tried to fix this issue but it is more complex then I thought before, because there are issues in 3 places:

1. Render content by php for display at HTML page, at this step data from DB is converted from `Cool![User Name](mention:a0c1c175-7fc8-48d7-9d2a-14e559ff6f07 "/u/admin/")` to `Cool[User Name](mention:a0c1c175-7fc8-48d7-9d2a-14e559ff6f07 "/u/admin/")`, i.e. the sign `!` is removed. I guess the removing was implemented for next step in order to don't render the mention link as image, but I think it is a bug and we don't need to remove the sign here.
2. Then the rendered content is additionally rendered by JS library `humhub-prosemirror-richtext` so all codes like `[...](...)` or `![...](...)` are converted to html tags `<a>` or `<img>`. So if we will modify only the PHP part to don't remove the sign `!` before mentioning tags `[User name](mention:...)` then this JS library will display them as image that is wrong.
3. But current issue really is not related to the 2 points above. The current issue appears because of this setting https://github.com/humhub/humhub/blob/master/protected/humhub/widgets/mails/MailContentEntry.php#L70 when image is rendered as URL, i.e. the parser thinks the `![User Name](mention:...)` is image and grabs the part `mention:a0c1c175-7fc8-48d7-9d2a-14e559ff6f07` and displays it because for normal links there we have a normal URL. But please note in `develop` branch we have already another rendering code https://github.com/humhub/humhub/blob/develop/protected/humhub/widgets/mails/MailContentEntry.php#L75-L78 and there such code `![User Name](mention:...)` is rendered as image `<img>` tag, that is wrong too.

So for this issue we should fix 3rd point but probably it should be fixed together, I still didn't find a solution...

**Comment by yurabakhtin** [comment] 2021-05-12 05:42
@luke- I have found one solution for 3rd point only. Please review PR https://github.com/humhub/humhub/pull/5068, really I don't understand why this my solution solves the problem but it works, if you agree you can merge.

<img width="1080" alt="test_fixed_mention_link" src="https://user-images.githubusercontent.com/6995524/117923878-80a99700-b2fd-11eb-8804-16e001c83c7e.png">

As you can see 1st and 2nd points were not fixed yet. I couldn't find a solution yet but spent enough time unfortunately, if you think I should continue find tell me please or advice how it may be fixed if you know the code part better, thanks.

**Comment by luke-** [comment] 2021-05-19 15:21
@yurabakhtin Sorry for my late feedback on this. 

I would prefer to move this issue to the Richtext Editor repository for this. We should make sure here that no "!" can be inserted directly before link elements. (Maybe somehow escaped?) 

I would close your PR which seems to ignore Markdown images "![" completely, this solves the specific problem but probably causes other problems.

**Closed by luke-** 2021-05-19 15:21 UTC
Labels: Status:Need investigation

**Comment by yurabakhtin** [comment] 2021-05-20 08:16
@luke- 

> I would close your PR which seems to ignore Markdown images "![" completely, this solves the specific problem but probably causes other problems.

Yes, I confirm this after testing and review my screenshot again, sorry for the bad solution, we need to find another indeed.
Thank you for the creating the issue in the Richtext Editor repository, but I think the bug that I tried to fix is not related to the Richtext Editor and it should be fixed in core probably in the file `protected/humhub/modules/content/widgets/richtext/converter/BaseRichTextConverter.php`.

**Comment by luke-** [comment] 2021-05-20 08:59
@yurabakhtin Hmm, the problem also affects the Javascript "Markdown to HTML" parser.  To reproduce it:

- Create a regular stream Post and add as content first a link (using button) and then a "!" directly before the link. And save it.
This results in a broken image.

**Comment by yurabakhtin** [comment] 2021-05-20 10:35
@luke- Yes, I know about that issue and I described it in 2nd point of my comment 
https://github.com/humhub/humhub/issues/5046#issuecomment-832528134, so it should be fixed in the Richtext Editor repository indeed, but in my previous comment https://github.com/humhub/humhub/issues/5046#issuecomment-844848677 I told about 3rd point from my comment https://github.com/humhub/humhub/issues/5046#issuecomment-832528134 that should be fixed probably in core files of HumHub repo I think.
