### ISSUE TITLE
Android notification ?

### ISSUE THREAD

**Issue by happyfredo** [humhub/humhub#1418] opened 2016-01-12 19:11 UTC
Android notification for chrome (v47) seem don't work actually.
Bug or enhancement ?

Best regards to the team

**Comment by happyfredo** [comment] 2016-01-12 20:04
Apparently code work only for desktop notification.
Perhaps use this methos will be useful

http://deanhume.com/home/blogpost/push-notifications-on-the-web---google-chrome/10128

Best regards

**Comment by zelectron** [comment] 2016-10-16 11:54
Notification in not working in Android app.
Is there any fix/patch ?

**Comment by buddha87** [comment] 2016-10-18 11:19
There is no mobile app yet, we'll provide a mobile app with push notifications as soon as possible.

**Comment by CBRSHDW** [comment] 2017-04-27 18:53
Any chance the push notifications are close to finialized?

**Comment by buddh4** [comment] 2018-07-12 21:18
Duplicate of https://github.com/humhub/humhub/issues/1354 this is planned soon (for android and desktops).

**Closed by buddh4** 2018-07-12 21:18 UTC
Labels: Type:Enhancement
