### ISSUE TITLE
 Incorrect datetime value : deadline

### ISSUE THREAD

**Issue by yokoshima1** [humhub/humhub#1980] opened 2016-09-05 09:38 UTC
SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '' for column 'deadline' at row 1
The SQL being executed was: UPDATE `task` SET `deadline`=NULL WHERE deadline = "" OR deadline = "0000-00-00 00:00:00"

this is a bug due to $this->update('task', array('deadline' => new \yii\db\Expression('NULL')), 'deadline = "" OR deadline = "0000-00-00 00:00:00"'); at m141002_092800_fix_deadline that u can change it to deadline = "1970-01-01 00:00:00"

it  occured at /humhub/index.php?r=installer%2Fconfig%2Fmodules
best of luck

**Comment by cebe** [comment] 2016-09-05 09:44
duplicate of humhub/humhub-modules-tasks#29 and #1786

**Closed** 2016-09-06 17:14 UTC
