### ISSUE TITLE
Error: Unknown or bad timezone

### ISSUE THREAD

**Issue by omur-dalan** [humhub/humhub#2122] opened 2016-11-27 20:13 UTC
I got this error when i try to create an event in calendar module. But not all installations.I could not find the difference between them. Can you provide a required timezone configuration for at least Ubuntu 16.04, PHP 7 and MySQL 5.7 ?

**Comment by cebe** [comment] 2016-11-27 20:33
how about using UTC?

**Comment by oyepez003** [comment] 2016-11-29 04:30
I got the same issue in the master branch (using the calendar module: creating a new event).

**Comment by cebe** [comment] 2016-11-29 08:36
duplicate of https://github.com/humhub/humhub-modules-calendar/issues/41#issuecomment-242161878

**Comment by oyepez003** [comment] 2016-11-29 08:49
But it is an error of the humhub core code: Yii::$app->formatter->timeZone is null

**Comment by cebe** [comment] 2016-11-29 08:54
it is `Europe/Berlin` in my humhub setup... Seems you are missing some setting.

**Comment by cebe** [comment] 2016-11-29 08:56
on URL `humhub/index.php?r=user%2Faccount%2Fedit-settings` you can select a timezone. afaik that is set automatically to a default value for every user.

**Comment by oyepez003** [comment] 2016-11-29 09:02
Yes but that settings is saved in Yii::$app->timeZone, Yii::$app->formatter->timeZone is for the User timezone.

**Closed** 2019-01-17 11:49 UTC
