### ISSUE TITLE
Group permissions don't save for custom groups. 

### ISSUE THREAD

**Issue by jeremiahtenbrink** [humhub/humhub#2284] opened 2017-02-18 21:22 UTC
I was editing the group permission on a newly created group. So this is group id 3. It wont save the permissions shows in the group permissions tab. It does save them for the two default groups. 

![grouppermisionbug](https://cloud.githubusercontent.com/assets/17443353/23096973/9a15b3ba-f5e5-11e6-875d-85335a0e30af.JPG)
![grouppermisionbug1](https://cloud.githubusercontent.com/assets/17443353/23096974/9bd796b4-f5e5-11e6-8f1d-e277be279e62.JPG)
![grouppermisionbug2](https://cloud.githubusercontent.com/assets/17443353/23096975/9d7cbd28-f5e5-11e6-9e94-13c7848d07ea.JPG)

**Comment by jeremiahtenbrink** [comment] 2017-02-20 08:16
Nevermind. That commit doesn't fix the issue.

**Comment by buddh4** [comment] 2017-02-20 17:00
can't reproduce this, works fine for me, does this happen for all permissions?
Do you get the 'saved' response, when changing the permission?
Are there any errors logged in "Administration -> Information -> Logging" ?
Are there any js errors in your browser console?

**Comment by jeremiahtenbrink** [comment] 2017-02-20 17:35
hmmmm..... Not sure whats going on then. I'll continue to investigate and see if I can pin point what is wrong, but its still not saving when I change the options in the group permissions sections. Quick question, are you only using the default groups and or the default group permission options. Because I have added group permission for the mail module and am currently working on group permission for a certification module I'm working on. 

I will upload my humhub environment to another server and see if I get the same errors. Maybe its the ubuntu server settings I'm using.

**Comment by jeremiahtenbrink** [comment] 2017-02-20 18:03
Same results. It seems to be happening when someone creates a custom group. Then tried to edit the group permissions.

**Comment by jeremiahtenbrink** [comment] 2017-02-20 18:55
attached is the console error log from the browser.

**Comment by buddh4** [comment] 2017-02-20 21:55
Did you pull your changes from the master branch? Perhaps you need to pull the latest changes.

**Comment by buddh4** [comment] 2017-02-20 21:56
And clear your cache/assets (Administration -> Settigns -> Advanced -> Cache)

**Comment by jeremiahtenbrink** [comment] 2017-02-20 23:25
I did that many times over. lol. For some reason though now its working. Thanks for the assistance. Hope it didn't take up to much of your time, at least its not a bug in the system.

**Comment by buddh4** [comment] 2017-02-21 09:37
No problem, think it was a problem with the assets, which was fixed with the latest update.

**Closed** 2017-02-25 16:59 UTC
Labels: Status:Unable to reproduce
