### ISSUE TITLE
How to handle users without group assingment?

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#4511] opened 2020-10-14 14:53 UTC
How to handle Users without assigned Group. 
Users without a group assignment do not have any global permissions at the moment, which is not obvious.
Should we force at least one group or at least somehow warn admins if there are users without a group?

**Comment by luke-** [comment] 2020-10-14 17:43
How about a (virtual) default group in which all users are automatically members?

**Comment by buddh4** [comment] 2020-10-15 09:33
This virtual group would only be used in the permission layer as fallback, but $user->getGroups() would still return an empty array?

**Comment by yurabakhtin** [comment] 2020-12-18 08:25
> Users without a group assignment do not have any global permissions at the moment, which is not obvious.

I tested a user without a group, but if he is a member of space and can edit some data(e.g. "Create poll") then it is possible to create a Poll by the user.
I don't know what reason to have some global permission for a user without a group.

**Comment by buddh4** [comment] 2020-12-18 11:25
@yurabakhtin yes, those are container permission, I'am refering to global group permissions.

**Comment by yurabakhtin** [comment] 2020-12-18 12:00
@buddh4 yes, I understood that you told about "global group permissions" in your first comment here.
I just investigated how a user can work on site without the global permission and I see it can be enough well because the user can has other permissions per Container, so I don't see a reason to create some virtual/default group for users.
Of course, I cannot know why the user model was created without mandatory/required at least one group and why it should be required now.

**Comment by buddh4** [comment] 2020-12-18 12:33
Maybe we should just make sure that there always is a non admin group. And in case there are users without a group we should add a warning + a way of resolving (add all to non admin group) to the group or user overview. I think the main problem happens if unexperienced users delete the default user group or do not set a default group for users.

**Comment by luke-** [comment] 2020-12-18 17:56
In my opinion, a default group for all members would be a practical & clear way to define basic rights. 
Maybe even a separate group for guests (if access is allowed for unauthenticated users).

A problem or confusion that often occurs in this context is that if a user does not belong to a group, the main menu item "Directory" is suddenly no longer visible. However, if guest access is activated at the same time, a guest who is not logged in can see the Directory menu item.

Alternatively, the solution with at least one group per user is also ok, but then it must be ensured, as mentioned by @buddh4 , that it is not deleted.

**Comment by buddh4** [comment] 2020-12-18 18:03
I assume you mean one default group and not one group per user?

**Comment by luke-** [comment] 2020-12-18 18:06
I meant by that: Each user must always be assigned a group. As an alternative solution to the default groups apporach.

**Comment by ArchBlood** [comment] 2020-12-18 18:09
I'd suggest on first setup of a HumHub instance that the option to set the default group be integrated, this would probably solve the issue with less stress for all and far more simpler than creating a virtual group, although some might also suggest the same thing when it comes to Spaces and default user groups :thinking:

**Comment by luke-** [comment] 2020-12-18 18:48
That would also be a possibility, at least one non-admin group must be marked as the default group.

**Comment by ArchBlood** [comment] 2020-12-18 19:07
> That would also be a possibility, at least one non-admin group must be marked as the default group.

By default HumHub creates a group named Users so that could be used in this case couldn't it? I'd also suggest that this should be used and be configured where the name can be changed on setup as well if this option were picked

**Comment by luke-** [comment] 2020-12-18 19:17
In the group overview we could add a badge "Default". I would then simply introduce a checkbox "Default Group" in the group settings.

During the setup, no prompts are actually necessary here.

**Comment by yurabakhtin** [comment] 2020-12-25 05:13
@luke- 

> In the group overview we could add a badge "Default". I would then simply introduce a checkbox "Default Group" in the group settings.

Should I start to implement this?:

- Add a new column `default TINYINT(1) DEFAULT 0` into the table `group`,
- Only one group can be default in a system, so on updating of a group if `default` is selected then a previous default group will be reset to not default,

But what should we do on upgrading/migration? Maybe we should find a first non-admin group and make it as default. I am not sure how it is correct, but otherwise a system still has no default group. Or is it normal to don't have a default group mandatorily? If yes, should we display some warning like "Please select a default group" on the group overview page?

**Comment by luke-** [comment] 2020-12-25 17:06
@yurabakhtin Yes, you can start!

I would suggest that for the migration we create a new group "Default Group" and assign all users who are not assigned to any other group to this group.

We should then create a notice about it here on the Migration Guide.
https://docs.humhub.org/docs/admin/updating-migration2

**Comment by yurabakhtin** [comment] 2020-12-28 08:14
@luke- 

> ... and assign all users who are not assigned to any other group to this group.

Why should we do this assignment? I think it would be better to don't store records in the table `group_user` for default group, we should automatically return a default group by the method `User->getGroups()` if the user has no assigned group.
And for better UI we should mark the default group somehow on user edit form, and even don't allow to remove that like this:
<img width="860" alt="default_group_UI" src="https://user-images.githubusercontent.com/6995524/103199961-2f27df00-48fd-11eb-8313-4bc78a113026.png">
Of course the default group can be unassigned if user is assigned to another group.

**Comment by luke-** [comment] 2020-12-28 09:51
Ok, we can try the "dynamic" mapping using the getGroups method. If there are no problems here, we can do it that way.
Maybe it is easiest to mark the default group with the suffix "(Default)" in the GroupPicker.

**Comment by yurabakhtin** [comment] 2020-12-28 13:30
I have started in PR https://github.com/humhub/humhub/pull/4742

<img width="855" alt="default_group" src="https://user-images.githubusercontent.com/6995524/103217535-dde21480-4929-11eb-9e3a-b06d9ec8c0fa.png">
<img width="856" alt="user_default_group" src="https://user-images.githubusercontent.com/6995524/103217547-e1759b80-4929-11eb-9709-5dd8a9bf63bb.png">

**Comment by luke-** [comment] 2020-12-28 16:30
Thank you for the PR.

I have seen that there is already a similar option. (I hadn't thought of that at first).
![image](https://user-images.githubusercontent.com/4736168/103227152-ff44ff80-492d-11eb-9fb1-c57a33537231.png)

If I have understood it correctly, the discussed apprach is as follows: 

From now on, a user must always belong to at least one group. (We should also show an error here instead of just returning the default group when saving without a selected group.) 

For the migration of existing installations, we need to create a "Default group" and assign users without a group_user mapping here. (Only for existing installations).

Steps:
- We should then replace the option from the screenshot with a checkbox ("Show Group Dropdown during registration").
- For new installations the existing "Users" group becomes default, for existing installations there is a new "Default Group".
- If there a problems with LDAP/SSO users, we can fallback to the default group (also when checkbox is enabled.)
- Existing installations: when users without group (rare case), we'll add a mapping to the default group by migrations 

What do you think of that?

**Comment by yurabakhtin** [comment] 2020-12-29 09:28
@luke- 

> For the migration of existing installations, we need to create a "Default group"

I have implemented this here https://github.com/humhub/humhub/pull/4742/commits/f6a3e8c637d83d5cf22035123102b96fe28effe6#diff-52c77ff7ccd3ac2ad077232095edcfe6955622ad5a1ee3f6c758ddc8bf215795R18-R23

> ...and assign users without a group_user mapping here. (Only for existing installations).

I didn't do this because you confirmed by words "we can try the "dynamic" mapping using the getGroups method", i.e. currently if user has no mapped group in the table `group_user` then method `User->getGroups()` automatically maps to default Group, the implementation is here https://github.com/humhub/humhub/pull/4742/commits/f6a3e8c637d83d5cf22035123102b96fe28effe6#diff-d3a4745ae7c92bb2ed3212a38c146f5f29268cf40a693d007f752f679a1f52abR344-R347.
I think it is strange to keep such setting like "Default Group" and then store records in the table `group_user`, because if the "Default Group" will be changed in general settings then it will not be affected to all users with stored records in the table `group_user`.

----

About the general setting "Default user group for new users":
- it is stored in the table `setting` with name `auth.default user group`
- but I have implemented a new column `is_default_group` in the table `group` and only single group can have this option enabled.

So as I understand we should decide what one to keep: either `setting:auth.defaultUserGroup` or `group:is_default_group`.
I think better to keep only `group:is_default_group` because it easier to select default group from the table `group` without unnecessary join with table `settings`. I.e. from boths forms ("General user settings" and "Group edit form") we should update only `group:is_default_group`. Of course we should implement new methods to get default group instead of `Yii::$app->getModule('user')->settings->get('auth.defaultUserGroup')`.

Also if we will use only single then the dropdown general setting "Default user group for new users" should be renamed to "Default user group".

Also why is the default group printed as a hidden element with value on user registration form? I mean it can be edited by browser inspector, so if I change the value from any other value then no record is created in the table `group_user` for such "hacked" user, and this user will be fallback to Default Group, that is ok, but I think no reason to print out the default group as hidden element.

---

> - We should then replace the option from the screenshot with a checkbox ("Show Group Dropdown during registration").

Yes, we can do this, but we should consider where to store the Default Group, please read above `setting:auth.defaultUserGroup` vs `group:is_default_group`.

> - For new installations the existing "Users" group becomes default, for existing installations there is a new "Default Group".

Ok, for new installations. But what if general setting "Default user group for new users" is already selected to some Group, I think we can continue to use this Group as default instead of creating new one "Default Group", do you agree?

> - If there a problems with LDAP/SSO users, we can fallback to the default group (also when checkbox is enabled.)

I think my implemented fallback in `User->getUsers()` works well, so if some user has no group relation in the table `group_user` then it fallback to Default Group (new option `group:is_default_group`).

> - Existing installations: when users without group (rare case), we'll add a mapping to the default group by migrations

Ok.

---

I see the "Default user group for new users" has only non admin groups, so new checkbox on group edit form should be restricted as well. I will do this.

**Comment by luke-** [comment] 2020-12-29 10:08
Yes, you are absolutely right, I agreed with the "dynamic" approach at first. But after testing and thinking about it a bit, it feels kind of odd. 

As example:
- The display of the number of members in the default group is incorrect. 
- You cannot list all members of the group.
- Features such as default Spaces will probably not work properly if no "real" `group_user` record is created.
- It is a bit strange from the UI when you remove a group from the user and then automatically when saving a new group is in the field.

But I understand the point that the default group cannot be changed for existing users when we add database entries.
But I think that's ok, we just need to make it clear that the default group is for new users only.
 
---

On the other points:

- Yes, we should remove `setting:auth.defaultUserGroup` and always use `group:is_default_group`. Of course with a new method to easy get the default group.

- There is also the case that `setting:auth.defaultUserGroup` is set to "0", in which case a list of groups with the flag `group:show_at_registration` is displayed during registration. To cover this case we need to provide a new setting `setting:showGroupDropdownOnRegistration` as boolean/checkbox.

- Atm, I'm not sure, why we use a hidden field here. We should remove it in a separte PR and test different cases.

- Migrations are also executed on new installations. However, we must ensure that the default group is only created for existing installations. Also, good point from you, we should migrate the setting `setting:auth.defaultUserGroup` (if set) to the Default Group. (`is_default_group`).

- Yes, the default group cannot be the Admin group 

---

I hope I have not missed any points.

**Comment by yurabakhtin** [comment] 2020-12-29 11:14
@luke- After reading your comment above I am a bit confused because you wrote the "dynamic" approach creates the issues like incorrect members number and impossible to list members and then you wrote to continue to implement next features where we will use the "dynamic" approach.
So as I have understood we need the Default Group only for new users, if yes then why do we need the new checkbox and column `group:is_default_group`?

It looks like what we had to do is to make the field "Groups" required on the user edit form, i.e. we should deny to store user without a group.

Then on the general user settings we should convert the first option "None - shows dropdown in user registration." to new checkbox "Show Group Dropdown during registration", and make the dropdown as required, i.e. at least one group with "Show At Registration" should exist in system.
Also it seems we can allow the new group checkbox `group:is_default_group` only for group with enabled "Show At Registration", right?

If we will store records in the table `group_user` even per Default Group and it will be used only for new users at registration then I don't understand why we need the new `group:is_default_group` at all.

**Comment by luke-** [comment] 2020-12-29 11:45
@yurabakhtin Maybe first to be sure, with `dynamic approach`, I meant that  `getGroups()` will return a group membership that does not exist in the database. 

Yes, we need the default group for following scenarios:
- Registration process - If `Show dropdown during registration` is enabled **and** no groups with `Show at registration` are available (**standard case**)
- To map all existing members without any group membership to it (migration)
- As fallback for users which are automatically created (e.g. by LDAP/SSO) 

Theoretically, we can also skip the checkbox `User can choose group during registration`  and say as soon as there are several `ShowAtRegistration` groups, they will be displayed during registration. 

Yes, the "Groups" field when editing the user should become required.

> If we will store records in the table group_user even per Default Group and it will be used only for new users at registration then I don't understand why we need the new group:is_default_group at all.

I am not sure if I have understood this correctly. Why does it not make sense to actually save users for the default group?

---

Unfortunately, the current solution with "Show at registration" option for the groups and the dropdown for registration control and the new default group is somewhat complicated. Also, the "Show at Registration" of the groups + the  group selection is a very rarely used feature.

**Comment by yurabakhtin** [comment] 2020-12-29 14:40
@luke- Ok, what I have done in new commit https://github.com/humhub/humhub/pull/4742/commits/6fe7a587b423d27eff34d82e07cccae7d65889a5 "Replace general user setting “Default user group” with column `group:is_default_group`":

<img width="853" alt="settings" src="https://user-images.githubusercontent.com/6995524/103290840-7dbba300-49fb-11eb-9685-c9569790275d.png">

- The general setting `setting:auth.defaultUserGroup` was completely with column from groups table `group:is_default_group`,
- New checkbox "Show Group Dropdown during registration" was created instead of the old first option "None - shows dropdown in user registration.",
- Changes in migration:
  - if some group was used as old "Default user group for new users" then this group will be converted to `group:is_default_group`, otherwise new group "Default Group" will be created,
  - insert records into `group_user` per each user without an assigned group, (please note I have done this only for active users `user.status = 1`, if you think we need this for all deleted and disabled user I will remove the restriction quickly).

I am not sure this is a finished solution, I think we still need to test this and review the code to be sure, because I just tried to implement this like you described above and hope that was required.

**Comment by luke-** [comment] 2020-12-29 16:48
That looks good to me so far. Do you have any concerns about the solution?

- Migration, I would include all users including the deactivated users but not soft deleted users.
- I like the solution of having the `defaultUserGroup` configurable in both places (Group Edit & User Settings groups). At first I thought the dropDown could be removed, but it's actually quite nice this way.
- We should also handle deleted groups.  Here, following confirm dialog and behaviour should be sufficient: `Users who are not assigned to another group are automatically assigned to the standard group. ` What do you think?
- In the case of a completely new HumHub installation, the default group should be "Users" and no further group should be created. To improve recognition during migration, I have prepared a PR here. What do you think of this?
https://github.com/humhub/humhub/pull/4749/files#diff-165768d5264abf499f64dfebc8457418231c40e499429732ec7080f5695eab96R155

**Comment by yurabakhtin** [comment] 2020-12-30 09:45
@luke- I think this solution is enough correct, but to make it better I have done additional changes in the commit https://github.com/humhub/humhub/pull/4742/commits/308a84bb0878ce979cbab4225b3a73819ab4ecf2:

- Deny deleting of the default group,
- Deny unchecking of the group option "Default Group", i.e. if a group is default then the checkbox is disabled in order to keep one default group in system. I mean admin only can set a new default group but it is impossible to unset the default group.
- Additional checking to don't set admin group as default.


> - Migration, I would include all users including the deactivated users but not soft deleted users.

Commits https://github.com/humhub/humhub/pull/4742/commits/13f31f9f215fd54b1be84a350f3016211c86e604, https://github.com/humhub/humhub/pull/4742/commits/95375b135b7a26497555f890f09e83445362855c

> - We should also handle deleted groups. Here, following confirm dialog and behaviour should be sufficient: `Users who are not assigned to another group are automatically assigned to the default group.` What do you think?

I agree and have done this in https://github.com/humhub/humhub/pull/4742/commits/375342f110dc528bc5a194aec3390fd7f70995b4

> - In the case of a completely new HumHub installation, the default group should be "Users" and no further group should be created. To improve recognition during migration, I have prepared a PR here. What do you think of this?
https://github.com/humhub/humhub/pull/4749/files#diff-165768d5264abf499f64dfebc8457418231c40e499429732ec7080f5695eab96R155

Yes, I think the `humhub\components\Migration->isInitialInstallation()` can be useful, but I made the group "Users" as default here https://github.com/humhub/humhub/pull/4742/commits/13f31f9f215fd54b1be84a350f3016211c86e604#diff-ad3c9b4512c98bc7307be8b2d80a598fe0b59587f3948400819a827a0b408a5dR439, so if the "Users" group will be created as default then on my migration no new default group will be created.

**Comment by luke-** [comment] 2020-12-30 10:09
Ok, looks good.

---

Can you please also create an issue in https://github.com/humhub/wording for the new texts (e.g. attribute hints) so we can proofread them.

---

Currently, the "Default Group" is also created during a fresh installation. 

![image](https://user-images.githubusercontent.com/4736168/103344351-a80a7080-4a8e-11eb-9f87-543f730388fb.png)

The problem seems to be that the migrations are executed before the "InitialData" of the installer. I think that in such cases we can't avoid the method "isInitialInstallation".

**Comment by yurabakhtin** [comment] 2020-12-30 11:04
@luke- How could you install without errors?
I got the error: `Setting unknown property: humhub\modules\user\models\Group::is_default_group` on the line `$group->is_default_group = 1;` from the "InitialData", it looks like the "InitialData" is called before migrations.
If I remove that my today's line `$group->is_default_group = 1;` then I got another error `Getting unknown property: humhub\modules\user\models\Group::notify_users`.

**Comment by luke-** [comment] 2020-12-30 11:08
@yurabakhtin See my comment here: https://github.com/humhub/humhub/pull/4742#issuecomment-752403052

**Comment by yurabakhtin** [comment] 2020-12-30 12:03
@luke- 

> See my comment here: #4742 (comment)

Thank you, this helped me to install after I merged `develop` branch into the PR.

> Currently, the "Default Group" is also created during a fresh installation.

Fixed in commit https://github.com/humhub/humhub/pull/4742/commits/6b21a48fbf45960b365c014b5b21dba2e1cd0e04

**Closed** 2021-02-05 17:19 UTC
Labels: Component:User, Kind:Discussion / Problem

**Comment by donni106** [comment] 2022-06-27 15:21
> However, if guest access is activated at the same time, a guest who is not logged in can see the Directory menu item.

@luke-  https://github.com/humhub/humhub/issues/4511#issuecomment-748231767

i read this right now and am in the situation, that i do not want guests to be able to access /directory/... pages. with being able to deactivate directory access per user groups, i am not able to do so for guests, right? or is this implemented in some newer version, as i am on 1.8.3. thanks.

**Comment by luke-** [comment] 2022-06-27 18:34
@donni106 For guest users, without any group we haven't a good solution yet. At the moment we need to handle them explicit without permissions. E.g. https://github.com/humhub/humhub/pull/5588

**Comment by donni106** [comment] 2022-06-28 08:48
We could think of clients that have problems with having all the names/usernames of users public, so that "everyone" knows who is registered on the platform. I would love to get an ability to hide the section. The PR looks promising, thanks.

**Comment by luke-** [comment] 2022-07-05 12:33
Ok, but FYI: There may  be changes here in future versions.
