### ISSUE TITLE
Error 500 when disabling DEBUG

### ISSUE THREAD

**Issue by GuguRD** [humhub/humhub#2261] opened 2017-02-13 17:25 UTC
When I disable debug by commenting:

```
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');
```

I got a error 500 and a lot of JS errors, the 500 is not printed anywhere (APACHE, app.log) 

> HUMHUB Version: Master Branch commit a063b031b01e0d8508ab6ca0a2630999367dc9e4
> DEBIAN
> APACHE 2.4

**Comment by buddh4** [comment] 2017-02-14 11:58
Did you update from 1.1 to 1.2 by a git pull ? Did v1.2 work before?

**Comment by GuguRD** [comment] 2017-02-14 16:31
I made a git pull and executed migrations and composer updates...

**Comment by buddh4** [comment] 2017-02-20 14:53
Did the update/migration run without errors, did you try to pull the latest version?

**Comment by oramadev** [comment] 2017-02-22 15:31
The problem is now fixed,  updated to the last commit on master and it is working fine. Although I cannot say what commit fixed it.

**Closed** 2017-03-03 10:04 UTC
