### ISSUE TITLE
mising trasnlations 'hook' on app Core error handle

### ISSUE THREAD

**Issue by Buliwyfa** [humhub/humhub#2766] opened 2017-09-24 14:32 UTC
### What steps will reproduce the problem?
Go to this Humhub free hosting:
https://1010.humhub.com

login as
david/david

Go to
https://1010.humhub.com/admin
to raise the error

### What is the expected result?
All texts translated, like on this **mockup** screen
![imagen](https://user-images.githubusercontent.com/13509685/30783506-3f36d022-a144-11e7-85b3-f3d2ca59fcb2.png)

### What do you get instead?
Most important text is not translated. This is a real screen capture:
![imagen](https://user-images.githubusercontent.com/13509685/30783533-abefecee-a144-11e7-8439-c431607065a8.png)

### Additional info

Some translations are not being pick up

....\protected\humhub\components\access\AccessValidator.php
(91)    $this->reason = Yii::t('error', 'You are not permitted to access this section.');

Also on it seems to happend on:
....\protected\humhub\controllers\ErrorController.php"
(37)    $message = Yii::t('error', 'An internal server error occurred.');
(91)    $this->reason = Yii::t('error', 'You are not permitted to access this section.');

No idea how to correct call the translation, only know how to do it on core and custom modules. This seems to be core app translations.... or something else.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.2
| PHP version      |  7.0
| Operating system | windows 2016

**Comment by victorpdiez** [comment] 2017-09-27 15:46
Same problem...

**Comment by Felli** [comment] 2017-09-27 22:41
Could you also please provide which languages this happens on?

**Comment by Buliwyfa** [comment] 2017-09-27 23:15
You can test it on Humhub free host given
Just log in as david/david (user/pass)

Go to  user account and change the langue
https://1010.humhub.com/user/account/edit-settings

Then visit

https://1010.humhub.com/admin

You can check it happens in:
- Spanish (screenshot above)

- French
![imagen](https://user-images.githubusercontent.com/13509685/30942062-f35d7820-a3e8-11e7-99a0-0aceb18555fd.png)

- Portuguese
![imagen](https://user-images.githubusercontent.com/13509685/30942178-a1cfef50-a3e9-11e7-8ccd-8e25bf9b6345.png)

- Italian
![imagen](https://user-images.githubusercontent.com/13509685/30942193-bbacdd20-a3e9-11e7-9808-f577fa8b7bd1.png)

- Catalan
![imagen](https://user-images.githubusercontent.com/13509685/30942147-73996418-a3e9-11e7-9389-b5f6073d0176.png)
![imagen](https://user-images.githubusercontent.com/13509685/30942152-7bd3b1d8-a3e9-11e7-9448-80d16ffda4c6.png)

- Korean
![imagen](https://user-images.githubusercontent.com/13509685/30942226-fb98b814-a3e9-11e7-91db-7626fc684d57.png)

-Japanese
![imagen](https://user-images.githubusercontent.com/13509685/30942294-6397496c-a3ea-11e7-9e69-5a56a8ba272d.png)


I believe on many other but I only try the ones we need

**Comment by 001101** [comment] 2017-09-28 18:46
http://translate.humhub.org

**Comment by Buliwyfa** [comment] 2017-09-28 19:14
@001101  I know  where are the translations, 
If you care to read it carefully and test it, you may find that the problem is that some translations are not being pickup as I point out in the best way I can.

**Comment by Buliwyfa** [comment] 2017-09-28 19:32
Doing further testing I found that

When logged as david/david

Translation works on
https://1010.humhub.com/dashboard/**admin**

But it does not work on reported URL

https://1010.humhub.com/**admin**

**Comment by Felli** [comment] 2017-09-28 20:36
Just to note, I've tested this out now, and I'm unable to reproduce some of this on self-host, this leads me to believe that it only happens on HumHub hosting plans for the most part.

### Example
> `You are not permitted to access this section.` (Won't translate therefore needs a more in-depth investigation.)

Other error messages will translate.

**Comment by Buliwyfa** [comment] 2017-09-28 21:38
@Felli  Thanks for testing it.

Not sure if you got the chance to test my final comment

As regular user, the error is translated on this URL

localhost/dashboard/admin

However, this will not

localhost/admin

Thanks for your interest!

**Comment by Felli** [comment] 2017-09-28 22:05
@Buliwyfa yes, I completely understand the issue at hand.

### Examples
> Does translate `localhost/dashboard/admin`
![](https://image.prntscr.com/image/pG6lMS9XSaiI-a4tEZpyww.png)

> Does not translate `localhost/admin`
![](https://image.prntscr.com/image/V5Va4EdzQ7yfmF-1oVBKpQ.png)

This leads me to believe that the first error message has been updated but the second one hasn't been updated. I've tested this on the community site as well as self-hosted sites.

**Comment by Buliwyfa** [comment] 2017-09-28 23:34
@Felli  thanks a lot for your time testing it.

:) y did not see the note...  since 0.11

So how can I request to be updated?

**Comment by Felli** [comment] 2017-09-29 01:16
I'm sure this will be updated soon, as it deals with translating errors, @buddh4 or @luke- still have to check things out, I'm not sure this will make it into `v1.3` or not at this point as `v1.3` is being rushed because of deadlines.

**Comment by Buliwyfa** [comment] 2017-09-29 01:17
ok! thank a lot for all!

**Comment by Felli** [comment] 2017-09-29 01:21
Also just to note, both of these are two different errors, one for the `lack of permissions to enter the ACP` as all of the screenshots show, and the other is `no page exists` under that directory.

**Comment by buddh4** [comment] 2017-10-04 09:59
Do you run/test this current master? I assume this text was introduced post v1.2.2 and therefore is not included in the translation.

**Comment by Buliwyfa** [comment] 2017-10-04 11:45
My test are on free humhub host

**Comment by buddh4** [comment] 2017-10-04 13:21
Could you check the version under "Administration -> Information2

**Comment by Buliwyfa** [comment] 2017-10-04 14:34
![imagen](https://user-images.githubusercontent.com/13509685/31181527-de7ee4aa-a921-11e7-90e9-d50fa62e6b24.png)

**Comment by Felli** [comment] 2017-10-05 19:36
I will also confirm this to be happening within free plan & self-hosted installations, I'll also note from here that this has been a feature since 0.11 as said here https://github.com/humhub/humhub/issues/2766#issuecomment-332976947.

**Comment by acs-ferreira** [comment] 2017-10-23 13:41
Can't reproduce on my install on `/admin` with a regular user
![image](https://user-images.githubusercontent.com/12234510/31890161-7837d5fe-b802-11e7-9adc-d179f9c9d73d.png)

**Comment by Buliwyfa** [comment] 2017-10-23 13:45
@acs-ferreira setup a free humhub plan an test it or use the URL and user given for the free humhub plan I used.

Also, on your installation did you apply any new commit or change anything on server configuration or htaccess file?

Thanks

**Comment by acs-ferreira** [comment] 2017-10-23 14:03
I can reproduce on your demo, not on my server.
But i can't tell you exactly why. I'm running the latest `master`.

Also, i do `yii message/extract` regularly for some reasons, maybe it helps?

**Comment by luke-** [comment] 2017-12-13 18:31
Should be fixed on updated demo servers.

**Closed by luke-** 2017-12-13 18:31 UTC
