### ISSUE TITLE
Selecting " Content I'm involved" filter in Dashboard throws error message and empty stream

### ISSUE THREAD

**Issue by dranii** [humhub/humhub#5316] opened 2021-09-29 17:38 UTC
### What steps will reproduce the problem?

Go to Dashboard and select from Filter drop-down :  Content  I'm involved

### What is the expected result?

It will show all Content(s) I'm involved [ although it is not clear I'm involved = comments/likes/comments in public spaces/others?? any humhub documentation that clarifies this? I did not find on search!]

### What do you get instead?

I get an Empty stream with "Stream could not be initialized!" and occasional bottom bar error message "An unexpected server error occurred. If this keeps happening, please contact a site administrator." This happens in Dashboard only, in Profile page I get NO error message I do get Content(s) I'm involved (whatever that means) 

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.9.1
| PHP version  7.4x     | 7.4x
| Operating system | Linux

**Comment by ArchBlood** [comment] 2021-09-29 20:12
What modules do you have installed?

**Comment by dranii** [comment] 2021-09-30 01:13
Only fresh and default install of latest Humhub. _"No modules installed yet. Install some to enhance the functionality!"_
@ArchBlood could you reproduce the error with 1.9.1 in php7x or 8x?
I get this error & blank stream ONLY in Dashboard and not in Profile pages. Thanks.

**Comment by ArchBlood** [comment] 2021-09-30 01:23
> Only fresh and default install of latest Humhub. _"No modules installed yet. Install some to enhance the functionality!"_ @ArchBlood could you reproduce the error with 1.9.1 in php7x or 8x? I get this error & blank stream ONLY in Dashboard and not in Profile pages. Thanks.

Sorry, I'm not able to reproduce this issue, could you check your prerequisites? (**_Administration panel > Information > Prerequisites_**) then check the logging tab after and provide the error stack?

**Comment by dranii** [comment] 2021-09-30 02:27
Thanks. Prerequisites are okay. These are:

![Screenshot 2021-09-30 at 07-49-26 (4) Administration - HumHub](https://user-images.githubusercontent.com/9887635/135375006-282a8682-3962-4561-9ccc-a241994b71eb.png)
Error stack is as follows
![333](https://user-images.githubusercontent.com/9887635/135375456-6cd0d7c5-7cba-4aef-895b-d67e7389784a.png)


If possible I will try to set up a demo link (with latest Humhub and php 7x &/or php8x) where this error can be seen. If possible can you also please share a demo link of 1.9.1 in php8x (and mention what hosting environ)  where I can see this is working without error? This error occurs in Dashboard only and not Profile page. Thanks.

**Comment by yurabakhtin** [comment] 2021-09-30 11:30
@luke- Fixed in PR https://github.com/humhub/humhub/pull/5319.

**Comment by luke-** [comment] 2021-09-30 12:35
@yurabakhtin Great thanks!

**Closed by luke-** 2021-09-30 12:35 UTC
Labels: Kind:BUG

**Comment by dranii** [comment] 2021-09-30 14:03
@ArchBlood  Thanks - please see this has been fixed.
@luke- @yurabakhtin  Amazing, this is now working perfect. Thanks and best regards.
