### ISSUE TITLE
Wrong ContentContainer's 'class' value when creating a new User if the User's identity is overridden 

### ISSUE THREAD

**Issue by devantoine** [humhub/humhub#2683] opened 2017-07-28 09:35 UTC
Hi,

If I understand correctly how the `contentcontainer` table is supposed to work, when adding a new user, the `class` value for the corresponding user should be the one returned by `Yii::$app->user->getIdentity()`.

The issue is: when you create a new user, the associated `contentcontainer` record has a `class` value of `humhub\modules\user\models\User`, not the actual class being used (defined with the `identityClass` parameter in `config/common.php`).

This causes a lot of issues because when a user creates a content, `Content::setContainer()` can't work: `$this->contentcontainer_id` is always null because `ContentContainerActiveRecord::getContentContainerRecord()` returns null (`self::className()` returning `humhub\modules\user\models\User` and not the actual overridden class).

Is there a way to change this behavior or this is a bug which needs to be fixed asap?

HumHub version: 1.2.1.

**Comment by githubjeka** [comment] 2017-08-01 09:50
Can you provide some sketch of code to easy reproduction of the bug?
It's bug 99%

**Comment by devantoine** [comment] 2017-08-01 12:55
@githubjeka Simply extend the base `User` class and define it in `config/common.php` under `$config['component']['user']['identityClass']`

**Comment by githubjeka** [comment] 2017-08-01 13:04
```php
'components' => [
        'user' => [
            'identityClass' => humhub\modules\puperuser\models\User::class,
        ],
    ],
```

puperuser is just copy/paste from `protected/humhub/modules/user` with replace the namespace

And I get 

![image](https://user-images.githubusercontent.com/874234/28826527-1f05a404-76d3-11e7-82de-6ecb19e065e0.png)

**Comment by githubjeka** [comment] 2017-08-01 13:11
So... many errors on php 7

like this

```
TypeError

Argument 1 passed to humhub\modules\notification\components\NotificationManager::getDesktopNoficationSettings() must be an instance of humhub\modules\user\models\User or null, instance of humhub\modules\puperuser\models\User given, called in D:\projects\humhub\protected\humhub\modules\notification\widgets\views\overview.php on line 8
```

**Comment by githubjeka** [comment] 2017-08-01 13:12
How did you solve their ?

**Comment by githubjeka** [comment] 2017-08-01 13:16
Humhub doesn't allow you to change many things now, through config. Too much internal logic was written without thinking about these moments. But we have a completely working social network out of the box)

**Comment by devantoine** [comment] 2017-08-01 13:22
If I fix it with some hack are scripts to replace `humhub\modules\user\models\User` in `contentcontainer`'s `class` column there's a worst side effect: every base class inserting rows in `content` won't be able to find the related `contentcontainer` record because base classes use the base `User` class and the association is done by the fqcn of the `User` class.

For instance, when you're inserting a content using the `Post` class you're using the `PostController`. This controller extends `ContentContainerController` which will load the current space, in this case the `User` space: https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/components/ContentContainerController.php#L79

So, the base `User` class is then set as the current `contentcontainer` but when you save a `Post`, `ContentContainerActiveRecord::getContentContainerRecord()` is called (https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/components/ContentContainerActiveRecord.php#L166) and thus returns `null` because `self::className()` resolves to `humhub\modules\user\models\User`.

I'm not sure if what I try to explain is clear. It's been quite hard to understand how things work and even harder to find what's buggy.

**Comment by devantoine** [comment] 2017-08-01 13:24
@githubjeka Leave the extended class empty, it doesn't matter, result will be the same.
And it does work on PHP7, without any tweak.

**Comment by devantoine** [comment] 2017-08-01 13:28
> Humhub doesn't allow you to change many things now, through config. Too much internal logic was written without thinking about these moments. But we have a completely working social network out of the box)

Well, it was working fine in 1.0, before I upgrade to 1.2.1. My `User` class holds way more properties, I need them.

**Comment by githubjeka** [comment] 2017-08-01 13:52
This container for new user
```php
'user' => [
     'identityClass' =>humhub\modules\puperuser\models\User::class
],

namespace humhub\modules\puperuser\models;


class User extends \humhub\modules\user\models\User
{

}

```
![image](https://user-images.githubusercontent.com/874234/28828436-74e5bcc8-76d9-11e7-8b78-89dcf28963ef.png)

But I can create/update/delete posts by new user. What wrong in your case?

**Comment by devantoine** [comment] 2017-08-01 14:08
Yeah, you're facing what I'm facing, `$contentContainerActiveRecord` is null because of what I said above.

**Comment by buddh4** [comment] 2017-08-01 17:27
What are you trying to do extending the user identity or replacing it, and why do you just need to authenticate gainst another system or do you want to integrate humhub in an existing architecture?

**Comment by githubjeka** [comment] 2017-08-01 17:31
There is no difference what and how, contentContainer for new User alwais is `\humhub\modules\user\models\User`

**Comment by devantoine** [comment] 2017-08-01 17:41
@buddh4 I'm extending the existing user identity to store more data for internal usage, firebase tokens, etc.

Does the user's identity is meant to be extended with Humhub?

**Comment by buddh4** [comment] 2017-08-01 18:16
It's not supposed to be overwritten, don't know if there would be other side effects beside the mentioned issue. But you could just add fields to the user table and access them as expected, no need to overwrite the user model? As of firebase tokens etc I would not extend the user table but user [contentcontainer settings](http://docs.humhub.org/dev-modules-settings.html#contentcontainer-related-settings)

You can also consider adding yii [behaviours](http://www.yiiframework.com/doc-2.0/guide-concept-behaviors.html) to your user model, perhaps in the afterload event. I'am not really a fan of behaviours but this way you can add functionality without overwriting the model class.

**Comment by githubjeka** [comment] 2017-08-01 18:40
I agree and not.

@devantoine better create module which will receive information from humhub, but will only use interfaces and events for it. And not code HumHub inheritance. It's will the correct fix for this issue by you.

And HumHub could be uses abstraction for ContentContainer, Content, User, Stream ... Although [they are modules](https://github.com/humhub/humhub/tree/master/protected/humhub/modules) but it just сlasses decomposed into different directories, that knowing each of other. Since I have several times faced with the fact that this or that is difficult to substitute. Thanks anyway for your hard work.

**Comment by devantoine** [comment] 2017-08-01 20:54
@buddh4 After having a quick look at the behaviors it may do what I need. The behavior's properties will be persisted in DB? If not I don't understand how I'm suppose to add field to the user table and access them.

I do understand that removing this user's identity inheritance will fix all my issues, I just need to know how to and where to persist the extra fields.

As for the firebase tokens @buddh4, it's not a global setting, each user owns his tokens (yes, he may have multiple tokens) so I need to have an extra table linked to the user.

**Comment by buddh4** [comment] 2017-08-01 21:22
No, you can add functionality to your model, if you just need to add attributes, you can add them to the user table and the are available in `Yii::$app->user->getIdentity()->myNewAttribute`. But if you nee do add some helper functionas as `Yii::$app->user->getIdentity()->someComplexModelFunction()` you can use behaviours. But I would only extend core tables etc if there is no other solution at hand, as @githubjeka said you should implement a cusotm module and keep your logic seperated.

@githubjeka I'am open to any suggestions regarding the abstraction of ContentContainer.

**Comment by devantoine** [comment] 2017-08-02 10:22
@buddh4 I don't see how it would work with another module handling all these extra properties related to the user. The module would have its own table linked to the user's table?

I've moved everything from the extended `User` class to an `UserBehavior` class but I don't know how to attach it to the HumHub `User` class.

**Comment by githubjeka** [comment] 2017-08-02 10:37
http://www.yiiframework.com/doc-2.0/guide-concept-behaviors.html#attaching-behaviors

in YoruModule::init()
```
$component = Yii::$app->user; // or Yii::$app->user->identify;

// attach a behavior object
$component->attachBehavior('myBehavior1', new MyBehavior);

// attach a behavior class
$component->attachBehavior('myBehavior2', MyBehavior::className());

// attach a configuration array
$component->attachBehavior('myBehavior3', [
    'class' => MyBehavior::className(),
    'prop1' => 'value1',
    'prop2' => 'value2',
]);
```

or via config 
```php
// components section
'user'=>[
[
    'as myBehavior2' => MyBehavior::className(),

    'as myBehavior3' => [
        'class' => MyBehavior::className(),
        'prop1' => 'value1',
        'prop2' => 'value2',
    ],
]
]
```

**Comment by devantoine** [comment] 2017-08-02 12:14
@githubjeka Yeah, I was doing it in the config but my syntax was wrong. Thanks, it seems to be working as expected!

But just to be sure, in a behavior I can have methods like `init()`, `rules()`, `afterSave()` and so on?

**Comment by githubjeka** [comment] 2017-08-02 12:20
In this cases you should use [attach](http://www.yiiframework.com/doc-2.0/yii-base-behavior.html#attach()-detail) by events EventInit , BeforeValidate, AfterSave

**Comment by githubjeka** [comment] 2017-08-02 12:26
Study the code https://github.com/yiisoft/yii2/blob/master/framework/behaviors/TimestampBehavior.php
how it's work

**Comment by devantoine** [comment] 2017-08-07 09:14
Ok, so I'm able to define the following:

```php
return [
            ActiveRecord::EVENT_INIT => 'init',
            ActiveRecord::EVENT_BEFORE_VALIDATE => 'beforeValidate',
        ];
```

But what about overriding of base methods?

I've added a behavior to: `getProfile()`, `getSearchAttribute()`, `isActive()`, `rules()`

Is it doable or should I fork Humhub and wait until the base user class can be extended?

**Comment by githubjeka** [comment] 2017-08-07 09:16
Now, it's impossible without `extends`

**Comment by devantoine** [comment] 2017-08-07 09:19
Wow...

No workaround? I feel stuck on these :/

**Comment by githubjeka** [comment] 2017-08-07 09:21
Try add a behavior with
```php
publick function getProfile() {
// doing what you need before
$this->owner->getProfile();
// doing what you need after
}
```

**Comment by githubjeka** [comment] 2017-08-07 09:24
update page please ) F5

**Comment by devantoine** [comment] 2017-08-07 15:56
It seems that I'm facing an issue with Yii: if you add a behavior directly through the model, in the `Model::behaviors()` method (which I can't use), behaviors are attached to your model.

In the configuration array the only place where, I think, you can put behaviors is under the `components` section: `$config['components']['user']` but then the behaviors are attached to the User's component class, not the User's model.

**Comment by githubjeka** [comment] 2017-08-07 17:57
Read read read:
http://www.yiiframework.com/doc-2.0/guide-concept-behaviors.html
http://www.yiiframework.com/doc-2.0/guide-concept-events.html

`Yii::$app->user->identity->on(...)`
or
`Yii::$app->user->identity->attachBehavior(...)`

This code can be used in your module, via [Module::init()](http://www.yiiframework.com/doc-2.0/yii-base-module.html#init()-detail);

**Comment by devantoine** [comment] 2017-08-08 15:26
I've read all of that but it's not a "real" module, it's a "user" module which override some user's controllers using the Yii boostraping mechanism.
I'm not sure if I can override the HumHub user's module any other way.

So, I've added this line in my custom boostraping:

````
$userComponent->identity->attachBehavior('UserBehavior', UserBehavior::class);
```

But it seems there's to instance of the User's identity available. As you can see on the screenshot below, globally (through `Yii::$app`) my behavior is set but when I call it in a view it doesn't exist (see the debugger's dump).

![hh](https://user-images.githubusercontent.com/1639739/29079743-439c6056-7c5e-11e7-9538-b89be0694c28.png)

I'm starting to be lost on this one.

**Comment by devantoine** [comment] 2017-08-08 15:41
@buddh4 Any thought on overriding User's method? Should I fork Humhub?

**Comment by devantoine** [comment] 2017-08-08 16:10
Just to be sure I've edited HumHub base module class like this:

```php
public function init()
    {
        $this->attachBehavior('UserBehavior', UserBehavior::class);

        parent::init();
    }
```

It doesn't work either. It seems that when your model as the `behaviors()` method, the only way to add other behaviors is to override this method.

So I can't add any behavior to the User's model. The app is not extensible at all, no way to add new behavior or functionality to the handling of the users :/

**Comment by buddh4** [comment] 2017-08-08 16:38
If you tell me what you are trying to achieve, perhaps I can help you further, which behaviour are you trying to extend or change, perhaps there is a better solution than extending the identity?

Of course we can try to solve the original contentcontainer issue (and hope there is no other issue with overwriting the identity), but currently I don't know a usecase where this is absolutely necessary.

**Comment by devantoine** [comment] 2017-08-09 12:44
@buddh4 It's hard to explain. We've got extended validation rules (a user can have no email for instance), extended search attributes, extended attributes, two types of profiles (I don't know if it's done correctly, I'm not the one who coded the app), extended password rules, more action on the AccountController, extended AuthController so the user can login using an iOS or Android app, etc.

I don't understand why the fqcn is stored in the contentcontainer. Could it just be a const instead? So, depending on the constant we would ever load the HumHub's Space model or the User's identity model.

**Comment by buddh4** [comment] 2017-08-09 13:20
We are currently working on a no email solution, so this will probably be possible in 1.2.3 with ldap or a custom authclient.

The user model triggers [an event](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/models/User.php#L577), which can be used to append search attributes.

Regarding two profiles, don't know how it is solved or whats the reason for this is, perhaps you could rather extend the profile instead of the user identity, perhaps we can make the actual profile replacable.

Extended password rules are easy there is a `BEFORE_VALIDATE`, `AFTER_VALIDATE` event for every ActiveRecord model.

In most cases you don't need directly extend the AccountController, you can just write an own Controller which handles your additional logic, the controller itself should be as slick as possible anyways and the actual logic should remain in models/helper/services etc. The main challenge with such extension is extending the views, menues or replacing whole widgets etc. As for the two profiles I don't know the actual requirements.

You can add custom AuthController and as I mentioned before also work with no email from 1.2.3.

The User is stored in there since he is an ContentContainerActiveRecord, which can hold content entries (e.g on his wall etc). There are currently two types of contentcontainer User and Spaces.

So you should always consider solving such issues by means of events or other solution before directly overwriting core components.

But we'll investigate a bit in the contentcontainer / user identity issue nontheless.

**Comment by buddh4** [comment] 2017-08-09 13:29
A dirty workaround regarding the contentcontainer issue, you can listen to `BEFORE_SAVE` and replace the model class by yourself, at least until we have a solution.

**Comment by devantoine** [comment] 2017-09-05 13:40
I've created these two listeners, which seems to work fine.

The first one's goal is to replace the `ContentContainer::$class` value with my `User` class when inserting a new `User`:

```php
class ContentContainerListener
{
    public function onContentContainerInsert($event)
    {
        /** @var ContentContainer $contentContainer */
        $contentContainer = $event->sender;

        if ($contentContainer->getAttribute('class') == \humhub\modules\user\models\User::class) {
            $contentContainer->setAttribute('class', User::class);
        }
    }
}
```

The second one is used to set the correct `Content::$contentContainer` when it is empty (because of https://github.com/humhub/humhub/issues/2683#issuecomment-319368230):

```php
class ContentListener
{
    public function onContentInsert($event)
    {
        /** @var \humhub\modules\content\models\Content $content */
        $content = $event->sender;

        if (!$content->getContentContainer()->exists()) {
            /** @var User $user */
            $user = $content->getCreatedBy()->one();
            $content->setContainer($user);
        }
    }
}
```

It seems to work fine. What do you think?

Do you see any downside to this solution?

**Comment by buddh4** [comment] 2017-09-06 12:47
One problem I can imagin is that you can't always be sure which kind of user instance you are handling within your applications, for example when searching for all users of a group by using the default HumHub API, you'll get HumHub user instances instead of instances of your custom user class, which as a developer could be rather confusing, beside from that you'll have to test this very well.

**Comment by devantoine** [comment] 2017-09-06 12:52
@buddh4 Do you have any better solution?

**Comment by buddh4** [comment] 2017-09-06 16:34
Currently not sorry, as I said I would somehow try to solve the issue without overwriting the core user model if possible. In my opinion the user model is already too huge and should rather loose some functionality than beeing extended even further.

I think as long as your user model extens the core humhub model and you are aware that the HumHub API does not know your custom user model, it may work as expected. But I would try to run the core and some module [tests](https://github.com/humhub/humhub/blob/master/protected/humhub/docs/guide/developer/testing.md) to get sure.

I will bring the issue up next time when discussing new features etc with my colleagues, but beside the two seperate profiles (which is a rather a rare case I think) I currently don't see that many usecases.
If you have some further usecases which definetly requires the extension of the user model beside the mentioned ones, let me know, so I can add this to my argumentation ;)

All in all I aggree that the platform should be as flexible as possible.

**Closed** 2019-01-16 16:36 UTC
Labels: Status:Need investigation
