### ISSUE TITLE
Allow users to post directly to spaces from Dashboard.

### ISSUE THREAD

**Issue by miteshprmr34** [humhub/humhub#5667] opened 2022-04-26 06:10 UTC
We can have a dropdown to select spaces when posting from dashboard.
![oie_tNiK2n7Fm2sm](https://user-images.githubusercontent.com/75738012/165233418-9f0a2567-6501-44f3-8bdd-6addc85a44f3.png)

**Comment by ArchBlood** [comment] 2022-04-26 09:07
Duplicate of #5396

**Closed** 2022-04-26 12:18 UTC
