### ISSUE TITLE
Opengraph support in controllers

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#3506] opened 2019-03-04 16:10 UTC
Controller should be able to set [Open Graph](http://ogp.me/) metadata.

e.g. ContentContainerController should set the space image by default.
Other Controllers should be able to set images e.g. related to a content entry (first image within richtext).

Example:

```php
$this->setOpenGraphImage($imgUrl);
$this->setOpenGraphTitle($title);
...
```

**Comment by Ace2213** [comment] 2019-12-03 11:42
+1

| | Space URL | Profile URL | Content URL | Fallback | 
| ------------- | ------------- | ------------- | ------------- | ------------- |
| OG Image  | Space image | Profile image | (if) Attachment | Site logo |
| OG Title  | Space Title  | User name | Post by {Author} in {Space name} on {Site name} | Site name |
| OG Description  | Space subtext (truncated)  | User About (truncated)| Post content | Site description |
| OG Type  |Website|Website|(if) Attachment type|Website|

**Comment by ArchBlood** [comment] 2020-03-27 18:28
You should also add one for `og:description`
```php
$this->setOpenGraphDescription($description);
```

**Comment by ArchBlood** [comment] 2021-01-03 03:17
To keep this alive, would something like the following be possible with this?

```html
<meta property="og:url" content="<?= $og->setOpenGraphUrl($url); ?>" />
<meta property="og:type" content="article" />
<meta property="og:title" content="<?= $og->setOpenGraphTitle($title); ?>" />
<meta property="og:description" content="<?= $og->setOpenGraphDescription($description); ?>" />
<meta property="og:image" content="<?= $og->setOpenGraphImage($imgUrl); ?>" />
```
If this is the desired affect it shouldn't be that hard to implement into the main.php file and create a controller that can be `/* @var $og OpenGraph */`? :thinking:

Or go in a similar way that [vumanskyi/yii2-opengraph](https://github.com/vumanskyi/yii2-opengraph) has?

**Comment by funkycram** [comment] 2021-11-05 12:33
+1. Today, with Humhub 1.9, sharing a content with a link or the Social Share module on Facebook is quite bad: only the image of the space is show, but not title, description or image of the publication or other module's content.

**Comment by lisandi** [comment] 2022-01-01 07:14
+1 It isn't available in 1.10.3 either and to promote HumHub further as a social media and sharing platform it is a MUST HAVE to not lack behind other social scripts with similar functionalities. It is necessary that a featured image or the first image of a post gets shown in the shared post beside at least the title and some first lines (paragraph) of the post.

Showing only the space's image is contra-productive for promotion purposes of a space as people will get fast be annoyed by always the same image showing up and no other information or "motivation" given to visit a space.

**Comment by samuk** [comment] 2022-05-03 14:00
I'm willing to pay to make this happen reasonably quickly. 

Do you have any kind of process for sponsoring tickets? Or shall I just find a third party who can do it?

**Comment by luke-** [comment] 2022-05-03 15:00
@samuk We offer custom paid development for Professional Edition subscribers. Please feel free to contact hello@humhub.com for more infos.

**Comment by samuk** [comment] 2022-05-03 15:03
OK, thanks, I don't have the Professional edition, unfortunately. I'll try and find someone else to do it.

**Comment by luke-** [comment] 2022-05-03 15:08
If you would like to contribute a PR for it, feel free to write details of the planned implementation here in advance. So we can discuss if neccessary....

**Comment by samuk** [comment] 2022-05-03 15:10
OK will do.

Just noting this in case it's relevant: https://www.yiiframework.com/wiki/2559/how-to-add-open-graph-and-twitter-card-tags-to-yii2-website

**Comment by lisandi** [comment] 2022-05-04 07:10
@samuk I am not sure if the development of that kind will be appreciated as the issue is known for a long time and actually got removed, without that any further development took place. As you like us are running on non-proprietary AGPL code I would suggest releasing this improvement under AGPL so it can't be used under any proprietary licenses. Only then do you have also the real benefit of your contribution as all that are using your code need to release the whole work under AGPL too and need to make it available publicly if they are a user of a site that is using your code? It means if any other develop your code further you will directly benefit from it too as nothing will be hidden. That is not the case if releasing it as a proprietary solution.

What you, mention in the link looks promising but it is not clear how to reuse it on several pages, posts, wiki pages, etc.
HumHub is not only a website or a blog, it is much more - many systems in one.

The biggest problem right now is that you can't really share posts on other social media so it would drive people to your site because the current sharing option allows only one default image (useless to be honest as it will get pretty boring soon to see always the same image) On the other side a "featured" image is until now missing. Like in WP, Grav, and most other CMS systems and also Sngine they are using a special image field to define the images shown on social media. Adding such a field would be a real benefit but also would need to be done IMHO as part of the core functionality.

Wiki. custom pages, blog posts, news, stream posts, calendar, and all other HumHub Modules could reuse such an additional field.

`<title>¿Deseas comprar o vender una casa en Cuba? | HogarEnCuba, para comprar y vender casas en Cuba</title>
<meta name="author" content="Daxslab (https://www.daxslab.com)">
<meta name="description" content="Hay 580 casas...">
<meta name="generator" content="Yii2 PHP Framework (http://www.yiiframework.com)">
<meta name="keywords" content="HogarEnCuba, ...">
<meta name="robots" content="follow">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:description" content="Hay 580 casas...">
<meta name="twitter:image" content="https://www.hogarencuba.com/images/main-identifier_es.png">
<meta name="twitter:site" content="HogarEnCuba">
<meta name="twitter:title" content="¿Deseas comprar o vender una casa en Cuba?">
<meta name="twitter:type" content="website">
<meta name="twitter:url" content="https://www.hogarencuba.com/">
<meta property="og:description" content="Hay 580 casas...">
<meta property="og:image" content="https://www.hogarencuba.com/images/main-identifier_es.png">
<meta property="og:locale" content="es">
<meta property="og:site_name" content="HogarEnCuba">
<meta property="og:title" content="¿Deseas comprar o vender una casa en Cuba?">
<meta property="og:type" content="website">
<meta property="og:updated_time" content="10 sept. 2020 9:43:00">`

Taking that as an example as mentioned on the link you have posted all pure content parts could be added easily but how to get a consistent way of adding an image to the post? Here a special Feature and Social Media Image field would make things much easier. Especially also in the case when the actual image isn't available on the HumHub site itself but instead gets referred from another source as a link that then displays in the HumHub Post.

As a workaround, we use sometimes a Grav Site in the Background where we post the posts that should then be shown in HumHub and GRAV provides us all we need and we then post the complete GRAV post as Post in HumHub too.

**Comment by funkycram** [comment] 2022-05-06 08:54
@luke- I merged https://github.com/daxslab/yii2-taggedview/blob/master/View.php into https://github.com/humhub/humhub/blob/master/protected/humhub/modules/ui/view/components/View.php ([the licence](https://github.com/daxslab/yii2-taggedview/blob/master/LICENSE.md) authorizes this merger).

This is the new file:
[View.zip](https://github.com/humhub/humhub/files/8638754/View.zip)

It works with Facebook (tested) and resolves the issue with [the Link Preview module](https://github.com/humhub/linkpreview-issues/issues/23). I use it successfully on 2 platforms.

Would you like me to create a PR? And then, perhaps we could improve this new code.

**Comment by samuk** [comment] 2022-05-06 08:57
@funkycram great work, thanks.

**Comment by funkycram** [comment] 2022-05-09 10:45
Screenshot:
![image](https://user-images.githubusercontent.com/23310825/167394534-e76523b7-4aaa-4a88-a7c4-21ac25409f83.png)

On Facebook, the preview is similar.

**Comment by luke-** [comment] 2022-05-12 06:43
I am not sure that we can and want to include this change in this stage to the Core.

For us, the challenge would be that, for example, depending on the context space/profile or content automatically and as generically as possible the respective tags are set.

Ideally this task would be done by the `ContentContainerController`.

**Comment by funkycram** [comment] 2022-05-13 08:29
Thanks @luke- .
`ContentContainerController` is indeed a better way to get the title, the description or event an image of the content.
But then we will have preview only for contents (e.g. if we share on custom page or the home page, preview wont work).

What do you think about keeping a generic Open Graph rendering in the `View` class and add some code in `ContentContainerController` to rewrite the title, description and image with the one of the content?

**Comment by luke-** [comment] 2022-05-16 16:19
@funkycram That's a good point. I'm a little unsure if our BaseController or View would be the best place here.

In any case, I would want a more lightweight solution than `axslab/yii2-taggedview` for now. Maybe we can focus on a few important fields (title, type, image, ....) for now.

**Comment by Vander-Ng** [comment] 2022-05-21 06:38
+1, the preview content in the FB Post would help to get more users joining the network...  hope it would come true soon, thanks for the team!

**Comment by funkycram** [comment] 2022-09-13 15:20
@luke- https://github.com/humhub/humhub/pull/5863/files

Testing: https://www.opengraph.xyz/

Each modules needs to add their meta tags, on the PostController model.

**Closed** 2022-11-09 22:11 UTC
Labels: Kind:Enhancement, Module:Core, Require:Concept, Topic:Extensibility, Topic:Integration
