### ISSUE TITLE
"latest activities" constantly "loading" for users

### ISSUE THREAD

**Issue by ghost** [humhub/humhub#2051] opened 2016-10-27 17:32 UTC
I get some new errors in my logging and I tryed to find the source.

I loged in with a normal user profile and I noticed that latest activities widget is constantly loading and not showing informations.

I discovered next error:

```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
http://"HOST"/dashboard/dashboard/stream?limit=10&from=&mode=activity
```

And this one also:

`jquery.js:10208 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.`

Here my humhub logging:

`exception 'yii\base\Exception' with message 'Could not create url for content!' in /home/opengrow/public_html/es/community/protected/humhub/modules/content/models/Content.php:497 Stack trace: #0 /home/opengrow/public_html/es/community/protected/humhub/components/SocialActivity.php(95): humhub\modules\content\models\Content->getUrl() #1 /home/opengrow/public_html/es/community/protected/humhub/components/SocialActivity.php(78): humhub\components\SocialActivity->getUrl() #2 /home/opengrow/public_html/es/community/protected/humhub/modules/activity/components/BaseActivity.php(72): humhub\components\SocialActivity->getViewParams(Array) #3 /home/opengrow/public_html/es/community/protected/humhub/libs/Viewable.php(89): humhub\modules\activity\components\BaseActivity->getViewParams(Array) #4 /home/opengrow/public_html/es/community/protected/humhub/modules/content/activities/ContentCreated.php(43): humhub\libs\Viewable->render('web', Array) #5 /home/opengrow/public_html/es/community/protected/humhub/modules/activity/models/Activity.php(96): humhub\modules\content\activities\ContentCreated->render() #6 /home/opengrow/public_html/es/community/protected/humhub/modules/content/components/actions/Stream.php(264): humhub\modules\activity\models\Activity->getWallOut() #7 [internal function]: humhub\modules\content\components\actions\Stream->run() #8 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Action.php(92): call_user_func_array(Array, Array) #9 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\Action->runWithParams(Array) #10 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('stream', Array) #11 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/web/Application.php(87): yii\base\Module->runAction('dashboard/dashb...', Array) #12 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #13 /home/opengrow/public_html/es/community/index.php(25): yii\base\Application->run() #14 {main}`

I made new clean installation in new folder and using same database for discart a corrupted file and I still geting same errors.

Someone have an idea?

Thank you.

**Comment by cebe** [comment] 2016-10-27 21:29
duplicate of #2047

**Closed** 2019-01-17 11:48 UTC
