### ISSUE TITLE
Soft Delete of users instead of hard deletes.

### ISSUE THREAD

**Issue by davidjeddy** [humhub/humhub#1312] opened 2015-11-17 17:05 UTC
Enhancement:
Instead of hard deleting a user and all associated data would not soft deleting the user and checking that property of a user's account be easier?

**Comment by rondonjon** [comment] 2016-07-17 17:32
Possible duplicate of #1252

**Comment by buddh4** [comment] 2018-07-12 21:10
Will be part of v1.3

**Closed by buddh4** 2018-07-12 21:10 UTC
Labels: Type:Enhancement
