### ISSUE TITLE
Error inviting user to group

### ISSUE THREAD

**Issue by cvenditto** [humhub/humhub#2498] opened 2017-04-20 13:20 UTC
Hello, inviting an existing member to an existing group returns an unexpected error (as you can see in third image).
ver. 1.2.0 enterprise
![img_20042017_144130_0](https://cloud.githubusercontent.com/assets/27815634/25232724/b3a90c2e-25dc-11e7-9e1e-5ed3e0b2d456.png)
enterprise 
![img_20042017_144117_0](https://cloud.githubusercontent.com/assets/27815634/25232714/aabe2112-25dc-11e7-9628-b4374f503578.png)
![img_20042017_144043_0](https://cloud.githubusercontent.com/assets/27815634/25232720/ae9669de-25dc-11e7-980e-6e42dda79664.png)

**Comment by buddh4** [comment] 2017-04-20 23:30
Which language are you using, we had a similar issue with french translation.

**Comment by cvenditto** [comment] 2017-04-21 07:56
Italian

**Comment by acs-ferreira** [comment] 2017-04-21 13:55
Wouldn't it be safer to use `Html::encode($string)` or `Html::encode(Yii::t())` on all strings?

**Comment by buddh4** [comment] 2017-04-26 13:38
The issue is probably fixed by the following commig https://github.com/humhub/humhub/commit/32ffda6739b04ff3e0499a1a9e8e66cd556f3d73

**Closed** 2017-05-03 15:25 UTC
