### ISSUE TITLE
Feature Request: Automatic Refresh of stream

### ISSUE THREAD

**Issue by DemonWareXT** [humhub/humhub#827] opened 2015-03-20 17:06 UTC
Either I am too stupid to find it and or thread for that
But I'd really like to see a kind of auto refresh of the stream, notifying that there is new content

Is there anything like that available yet?

Thanks a lot all of you devs for your epic work, I only just started looking into this project, and it looks awesome!

Cheers!
Linus

**Comment by EvilSanta** [comment] 2015-04-16 19:20
Yes please.

**Comment by LateForLunch** [comment] 2015-04-19 09:16
Would be awesome to see this.

I noticed that the code for the notifications also returns information about the workspaces:
Request: /index.php?r=dashboard/dashboard/GetFrontEndInfo
Response before someone added a new post: {"workspaces":[{"name":"Test Space","guid":"6c5523a2-0572-40cc-92f3-56b6eb6b9e9d","totalItems":24,"newItems":0}],"newNotifications":"0","notifications":[]}
Response after someone added a new post: {"workspaces":[{"name":"Test Space","guid":"6c5523a2-0572-40cc-92f3-56b6eb6b9e9d","totalItems":25,"newItems":0}],"newNotifications":"0","notifications":[]}

So the totalItems works, but the newItems doesn't work yet.
I'm still trying to find my way around the whole project, so I'm not sure where to start to get this working.

**Comment by buddh4** [comment] 2018-07-12 20:39
Duplicate of https://github.com/humhub/humhub/issues/229

**Closed by buddh4** 2018-07-12 20:39 UTC
Labels: Status:Confirmed, Type:Enhancement
