### ISSUE TITLE
Humhub 1.9-beta.1 - People page crashes if a checkbox field is set to be shown on People overview

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#5136] opened 2021-06-20 10:35 UTC
### What steps will reproduce the problem?

Go to `/admin/user-people`
In `Information x` select a field whose type is "checkbox list" (not tested with other fields types)

### What is the expected result?

`/people` page should work

### What do you get instead?

![image](https://user-images.githubusercontent.com/23310825/122670691-92673f80-d1c3-11eb-94b7-12b49f983d09.png)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.9 beta.1
| PHP version      | 8.0

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by ArchBlood** [comment] 2021-06-20 12:50
Same as in #5137, can't reproduce on my end

**Comment by funkycram** [comment] 2021-06-20 12:53
No, #5137 is caused by PHP 8.0, but this issue has nothing to do with PHP version. It occurs with PHP 7.3 to.

**Comment by smashm** [comment] 2021-06-21 11:06
I can't reproduce it either. 
»1« is the shown info from the enabled checkbox. (PHP 7.4, actually I cannot run 8 in my test environment.)

![Bildschirmfoto 2021-06-21 um 12 55 34](https://user-images.githubusercontent.com/60502320/122752502-569aab80-d291-11eb-8344-7ceab6205d7b.png)

![Bildschirmfoto 2021-06-21 um 12 54 57](https://user-images.githubusercontent.com/60502320/122752516-5ac6c900-d291-11eb-934d-89018ed14fe7.png)

**Comment by luke-** [comment] 2021-06-21 13:26
@yurabakhtin Any idea?

**Comment by yurabakhtin** [comment] 2021-06-21 14:54
@luke- Yes, I can reproduce this with type "Checkbox List". I will fix this to display all checked options separated by comma.
It works without errors with type "Checkbox", but it displays only `1`, I will fix this to display a checkbox label instead.

**Comment by funkycram** [comment] 2021-06-21 14:59
Thanks @yurabakhtin . Sorry, you are right, problem is with Checkbox list, I made a mistake.

**Comment by yurabakhtin** [comment] 2021-06-21 15:38
@luke- Fixed in PR https://github.com/humhub/humhub/pull/5140

**Closed** 2021-06-21 15:54 UTC
Labels: Status:Unable to reproduce
