### ISSUE TITLE
Mobile - Zooming into pictures

### ISSUE THREAD

**Issue by Semir1212** [humhub/humhub#5310] opened 2021-09-24 13:28 UTC
| HumHub version   | 1.9.1
Android/iOS
Chrome/Safari

When opening a single picture it should be possible to zoom in manually. Currently the pictures is just moving instead of instead of being enlarged.

**Comment by Soundwave2142** [comment] 2021-11-21 13:28
@luke- 
I looked into this. It seems we are currently use blueimp. I tried updating the plugin ( as creator claimed new version support this ), however it did not help. Plugin is also installed via package manager (not statically as some other js scripts), so I don't think I can tinker with it? I also tried some of the small code snippets I found on internet, however non of them seems to work. 

I can look for another plugin we can integrate into humhub, or I would suggest assigning this task to someone else as I lack proper knowledge and experience in front-end development to accomplish this task.

**Comment by luke-** [comment] 2021-11-23 15:34
@Soundwave2142 Ok, thanks anyway for take a look -- then lets postpone this issue for now :-)

**Comment by marc-farre** [comment] 2024-05-20 15:28
It’s possible to zoom with the pinch-to-zoom functionality.

**Comment by marc-farre** [comment] 2024-05-20 19:40
@luke- The issue is `maximum-scale=1.0, user-scalable=no`: https://github.com/humhub/humhub/blob/master/protected/humhub/views/layouts/main.php#L13

If we remove them, then we can pinch to zoom on the image.

I suggest replacing this line with:
```php
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
```

If you agree, I can send a PR (on develop?).

**Comment by JK742020** [comment] 2024-05-21 06:10
Will this be implemented in the next release?

**Comment by luke-** [comment] 2024-05-21 06:55
@marc-farre What specific effects will the change have?

**Comment by marc-farre** [comment] 2024-05-21 07:05
@luke- 
1/ I would remove `maximum-scale=1.0, user-scalable=no"` which prevents from zooming in
2/ I would also remove `minimum-scale=1.0` which prevents from zooming out, because I don't see any reason to restrict this possibility, even if it's not related to any issue we have. If you prefer to keep it, it's also fine.
3/ `viewport-fit=cover` is specific of iOs for dealing with the "safe area" on e.g., iPhone X and above, where the screen has a notch and round corners. It tells the website to cover the entire viewport, including the area behind the notch. Again, this is not related to this issue, and optional.

**Comment by luke-** [comment] 2024-05-21 07:29
@marc-farre I couldn't find any reason why we introduced this scaling restriction.

Anyway, I would somehow prefer that we enable zooming only in the gallery view of images. Then the UI would remain stable.  But maybe from an accessibility perspective it is better to allow scaling  at least in the web view.

But I would like to avoid this in the mobile app. To be able to zoom around freely. Also from the perspective of possible future native elements.

**Comment by marc-farre** [comment] 2024-05-21 08:05
@luke- If we don't remove `maximum-scale=1.0, user-scalable=no` zooming on gallery pictures will nether be possible unless we replace Blueimp Gallery with another library, because it's the only way to achieve it with it: 
https://github.com/blueimp/Gallery/issues/121#issuecomment-629748137

And because Blueimp Gallery project is not maintained anymore and this feature is not planned: https://github.com/blueimp/Gallery/issues/275#issuecomment-1529599280

If we remove `maximum-scale=1.0, user-scalable=no`, it will apply on all the document, mobile app included. I don't think there are solutions with CSS to allow zooming on a specific DIV element only. It would require JS which adds complexity.

I personally think we should be able to zoom anywhere on HumHub, mobile app included, for visually impaired people.

**Comment by luke-** [comment] 2024-05-21 08:10
@marc-farre Then let's add it for now. I could imagine that we could activate this scaling only during the gallery.

**Comment by marc-farre** [comment] 2024-05-21 08:46
@luke- PR https://github.com/humhub/humhub/pull/7016 with some code reformatting

**Comment by luke-** [comment] 2024-05-21 08:59
@marc-farre Thanks!

**Closed by luke-** 2024-05-21 08:59 UTC
Labels: Kind:Enhancement, Topic:Mobile, Topic:Usability

**Comment by marc-farre** [comment] 2024-05-21 09:24
> Will this be implemented in the next release?

@JK742020 Yes, in HumHub 1.16.0-beta.3

But you can already apply this fix by removing `, maximum-scale=1.0, user-scalable=no"` from your `protected/humhub/views/layouts/main.php` file (or theme if overwritten). See https://github.com/humhub/humhub/pull/7016/files#diff-793a8e2897ad3b22d5190e09dfbef70a03ca7a09cc6abe9b8c37125106d6a895L13

**Comment by JK742020** [comment] 2024-05-21 14:41
Great! Thanks to everybody involved!

**Comment by JK742020** [comment] 2024-06-18 07:10
Zoom in APP sometimes not available

Sometimes especially when opening the app from a notification zoom is not available. Sometimes zoom also is not available after opening app from icon. Sometimes it works in one and the other way. No pattern recognisable.

**Comment by marc-farre** [comment] 2024-06-18 07:57
@JK742020 I cannot reproduce the issue, but I think the proper way to solve this issue is implementing the new light box library: https://github.com/humhub/humhub/issues/6704
