### ISSUE TITLE
Error Issues in Log : Message pattern is invalid

### ISSUE THREAD

**Issue by jayavman** [humhub/humhub#5966] opened 2022-12-02 22:56 UTC
Receiving a bunch of these errors in the log (pages full of them). Not sure what they mean :

yii\i18n\I18N::format
Formatting message for language '' failed with error: Message pattern is invalid: MessageFormatter::__construct(): Passing null to parameter #1 ($locale) of type string is deprecated. The message being formatted was: This upload field only allows a maximum of {n,plural,=1{# file} other{# files}}..

Formatting message for language '' failed with error: Message pattern is invalid: MessageFormatter::__construct(): Passing null to parameter #1 ($locale) of type string is deprecated. The message being formatted was: Sorry, you can only upload up to {n,plural,=1{# file} other{# files}} at once..

### Additional info

| HumHub version   | 1.13.0-beta.2
| PHP version      | 8.1.12

**Comment by jayavman** [comment] 2022-12-05 00:31
@luke- 

Any update with this? I'm getting flooded with Log errors over this 

<img width="931" alt="Screenshot 2022-12-05 at 11 31 12 am" src="https://user-images.githubusercontent.com/114973646/205525614-d22e552e-1fa3-4206-b54b-db062d98d0c4.png">

**Comment by ArchBlood** [comment] 2022-12-05 03:00
Check your prerequisites under Administration > Information > Prerequisites and report back with the information, also what language is being used, as I'm not able to reproduce this.

**Comment by jayavman** [comment] 2022-12-06 07:21
<img width="591" alt="Screenshot 2022-12-06 at 6 20 57 pm" src="https://user-images.githubusercontent.com/114973646/205846736-a04b5cf4-fd1e-48a4-a9a4-87cbb337c556.png">

**Comment by yurabakhtin** [comment] 2022-12-06 08:15
@jayavman Thank you for the report and details!

@luke- There was the error only on PHP 8.1+ and only when user's language is English, because `sourceLanguage` was not defined for `humhub\components\i18n\ModuleMessageSource` that initialized in `yii\i18n\MessageSource`:

![source-lang-bug](https://user-images.githubusercontent.com/6995524/205856420-c02cee12-4d70-47c0-ba52-38ee3b87f789.png)

Fixed in PR https://github.com/humhub/humhub/pull/5969.

**Comment by jayavman** [comment] 2022-12-06 10:45
Yes, my user language is english and we are using 8.1 

Cheers guys :>

**Closed** 2022-12-06 13:27 UTC
Labels: Status:Need investigation
