### ISSUE TITLE
v1.16 beta2: broken Marketplace search

### ISSUE THREAD

**Issue by felixhahnweilheim** [humhub/humhub#6944] opened 2024-04-11 17:25 UTC
### What steps will reproduce the problem?
Update to 1.16.0-beta.2 via Updater module.
Go to Marketplace and search for anything.

### What is the expected result?
List of found modules or an empty emssage.

### What do you get instead?

Following error:
```
yii\base\ErrorException: Undefined array key "keywords" in /var/www/vhosts/humhub/httpdocs/protected/humhub/components/Module.php:139
Stack trace:
#0 /var/www/vhosts/humhub/httpdocs/protected/humhub/components/Module.php(139): yii\base\ErrorHandler->handleError()
#1 /var/www/vhosts/humhub/httpdocs/protected/humhub/modules/marketplace/models/Module.php(156): humhub\components\Module->getKeywords()
#2 /var/www/vhosts/humhub/httpdocs/protected/humhub/components/ModuleManager.php(444): humhub\modules\marketplace\models\Module->getKeywords()
#3 /var/www/vhosts/humhub/httpdocs/protected/humhub/components/ModuleManager.php(405): humhub\components\ModuleManager->filterModulesByKeyword()
#4 /var/www/vhosts/humhub/httpdocs/protected/humhub/modules/marketplace/widgets/ModuleGroups.php(83): humhub\components\ModuleManager->filterModules()
#5 /var/www/vhosts/humhub/httpdocs/protected/humhub/modules/marketplace/widgets/ModuleGroups.php(33): humhub\modules\marketplace\widgets\ModuleGroups->initDefaultGroups()
#6 /var/www/vhosts/humhub/httpdocs/protected/vendor/yiisoft/yii2/base/BaseObject.php(110): humhub\modules\marketplace\widgets\ModuleGroups->init()
#7 [internal function]: yii\base\BaseObject->__construct()
#8 /var/www/vhosts/humhub/httpdocs/protected/vendor/yiisoft/yii2/di/Container.php(412): ReflectionClass->newInstanceArgs()
#9 /var/www/vhosts/humhub/httpdocs/protected/vendor/yiisoft/yii2/di/Container.php(171): yii\di\Container->build()
#10 /var/www/vhosts/humhub/httpdocs/protected/vendor/yiisoft/yii2/BaseYii.php(366): yii\di\Container->get()
#11 /var/www/vhosts/humhub/httpdocs/protected/humhub/components/Widget.php(59): yii\BaseYii::createObject()
#12 /var/www/vhosts/humhub/httpdocs/protected/humhub/modules/marketplace/views/browse/index.php(35): humhub\components\Widget::widget()
#13 /var/www/vhosts/humhub/httpdocs/protected/vendor/yiisoft/yii2/base/View.php(348): require('...')
#14 /var/www/vhosts/humhub/httpdocs/protected/vendor/yiisoft/yii2/base/View.php(258): yii\base\View->renderPhpFile()
#15 /var/www/vhosts/humhub/httpdocs/protected/vendor/yiisoft/yii2/base/View.php(157): yii\base\View->renderFile()
#16 /var/www/vhosts/humhub/httpdocs/protected/vendor/yiisoft/yii2/base/Controller.php(408): yii\base\View->render()
#17 /var/www/vhosts/humhub/httpdocs/protected/humhub/modules/marketplace/controllers/BrowseController.php(51): yii\base\Controller->render()
#18 [internal function]: humhub\modules\marketplace\controllers\BrowseController->actionIndex()
#19 /var/www/vhosts/humhub/httpdocs/protected/vendor/yiisoft/yii2/base/InlineAction.php(58): call_user_func_array()
#20 /var/www/vhosts/humhub/httpdocs/protected/vendor/yiisoft/yii2/base/Controller.php(179): yii\base\InlineAction->runWithParams()
#21 /var/www/vhosts/humhub/httpdocs/protected/vendor/yiisoft/yii2/base/Module.php(553): yii\base\Controller->runAction()
#22 /var/www/vhosts/humhub/httpdocs/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#23 /var/www/vhosts/humhub/httpdocs/protected/vendor/yiisoft/yii2/base/Application.php(385): yii\web\Application->handleRequest()
#24 /var/www/vhosts/humhub/httpdocs/index.php(28): yii\base\Application->run()

```

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.16.0-beta.2
| PHP version      |  8.2
| Operating system | Ubuntu with Plesk

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by marc-farre** [comment] 2024-04-11 19:59
@yurabakhtin I think the issue is that the form sends `keyword` and not `keywords`.

**Comment by yurabakhtin** [comment] 2024-04-12 06:26
@luke- Fixed in the PR https://github.com/humhub/humhub/pull/6946.

We already fixed similar issues in the PR https://github.com/humhub/humhub/pull/6909, but it was merged only in the `master` branch.

But the method `getKeywords()` doesn't exist in the `master`, so I have created new PR for `develop` where fixed the method and all others which were fixed in the `master` PR.

**Closed** 2024-04-12 06:48 UTC
Labels: Kind:BUG
