### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation:

### ISSUE THREAD

**Issue by ivantree** [humhub/humhub#2052] opened 2016-10-29 07:42 UTC
Caused by: PDOException
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'humhub.notification.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

in C:\wamp64\laravel\public\protected\vendor\yiisoft\yii2\db\Command.php at line 900

Database Exception – yii\db\Exception
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'humhub.notification.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
The SQL being executed was: SELECT COUNT(*) FROM (SELECT `notification`.*, count(distinct(originator_user_id)) as group_count, max(created_at) as group_created_at, min(seen) as group_seen FROM `notification` WHERE ((`seen`=0) OR (`seen` IS NULL)) AND (`user_id`=1) GROUP BY COALESCE(group_key, id), `class` ORDER BY `group_seen`, `group_created_at` DESC) `c`

Error Info: Array
(
    [0] => 42000
    [1] => 1055
    [2] => Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'humhub.notification.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
)

**Comment by buddha87** [comment] 2016-10-29 12:53
Duplicate of https://github.com/humhub/humhub/issues/1777

**Closed by buddha87** 2016-10-29 12:53 UTC
