### ISSUE TITLE
Scheduled Post Permalink Leads to error 

### ISSUE THREAD

**Issue by ArchBlood** [humhub/humhub#6515] opened 2023-08-16 11:42 UTC
### What steps will reproduce the problem?
- Create a scheduled Post
- Open the drop-down on the post and select permalink and go to the post

![Screenshot_20230816-073211.jpg](https://github.com/humhub/humhub/assets/35392110/aa39d0f0-7f82-4a52-910b-5f8a30eec276)

![Screenshot_20230816-073153.png](https://github.com/humhub/humhub/assets/35392110/dc7d63de-020d-44ac-95e9-7072952dd2c3)

### What is the expected result?
Should show the scheduled Post or a mention of the post not being available till a scheduled date.

### What do you get instead?
Oops something went wrong

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | Community site 
| PHP version      | Community site 
| Operating system | Community site 

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by yurabakhtin** [comment] 2023-09-07 10:35
@luke- Fixed in PR https://github.com/humhub/humhub/pull/6540.

**Comment by yurabakhtin** [comment] 2023-09-13 08:34
We should use the approach from PR https://github.com/humhub/humhub/pull/6005 instead of https://github.com/humhub/humhub/pull/6540.

**Comment by ArchBlood** [comment] 2024-01-11 22:49
Seems to also throw this error for notifications if you're following someone that schedules a post, this affects all versions of `1.15`.

**Comment by yurabakhtin** [comment] 2024-01-12 09:17
@ArchBlood Do you mean user recieves a notification about scheduled post?

If yes, I am not sure it is possible because here https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/models/Content.php#L277-L280 we restrict this:

```php
if (!$this->getStateService()->isPublished()) {
    // Don't notify about not published Content
    return;
}
```

Could you show what error you have and how to reproduce this if you know? Thanks.

**Comment by ArchBlood** [comment] 2024-01-14 23:20
> @ArchBlood Do you mean user recieves a notification about scheduled post?
> 
> If yes, I am not sure it is possible because here https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/models/Content.php#L277-L280 we restrict this:
> 
> ```php
> if (!$this->getStateService()->isPublished()) {
>     // Don't notify about not published Content
>     return;
> }
> ```
> 
> Could you show what error you have and how to reproduce this if you know? Thanks.

I'd have to ask my client about this, as I can confirm in their instance that a notification was sent to followers of the user about the scheduled post then the error popped up, I'll try getting a test instance up and try recreating this for the error logs. :thinking:

**Comment by ArchBlood** [comment] 2024-01-14 23:30
> > @ArchBlood Do you mean user recieves a notification about scheduled post?
> > If yes, I am not sure it is possible because here https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/models/Content.php#L277-L280 we restrict this:
> > ```
> > if (!$this->getStateService()->isPublished()) {
> >     // Don't notify about not published Content
> >     return;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Could you show what error you have and how to reproduce this if you know? Thanks.
> 
> I'd have to ask my client about this, as I can confirm in their instance that a notification was sent to followers of the user about the scheduled post then the error popped up, I'll try getting a test instance up and try recreating this for the error logs. 🤔

Okay, I'm not able to recreate the issue for the notifications, but the viewing the scheduled post as myself or another user through the permalink does as this issue was meant for, I've also confirmed that viewing a draft through permalink also causes the same issue as this one, no error logs happen for either of these issues.

**Comment by yurabakhtin** [comment] 2024-01-15 11:12
@ArchBlood 

> but the viewing the scheduled post as myself or another user through the permalink does as this issue was meant for, I've also confirmed that viewing a draft through permalink also causes the same issue as this one, no error logs happen for either of these issues.

As I undestand you mean the "Permalink" is visible for Scheduled and Draft posts but when we click then we see only "Oooops... It looks like you may have taken the wrong turn." instead of expected post content.
Yes, I agree we have the same bug.

@luke- I see the bug was fixed in the PR https://github.com/humhub/humhub/pull/6005 as I wrote here https://github.com/humhub/humhub/issues/6515#issuecomment-1717187273 but the PR is not merged yet and I think it would be good to merge it into `master` instead of `next`, what do you think?

**Closed** 2024-08-04 11:46 UTC
Labels: Kind:BUG
