### ISSUE TITLE
Saving oEmbed Data

### ISSUE THREAD

**Issue by ArchBlood** [humhub/humhub#5716] opened 2022-05-21 20:21 UTC
### What steps will reproduce the problem?
On any of the current pre-installed or custom oEmbeds click the save button and you'll see that the provider endpoint `%url%` will decode all `%` to `%25` on save.

Example: `https://www.youtube.com/oembed?url=%url%&format=json` > `https://www.youtube.com/oembed?url=%25url%25&format=json`

### What is the expected result?
The transferred data should not be decoding the `%url%` in such a way.

### What do you get instead?
![Screenshot_1](https://user-images.githubusercontent.com/35392110/169667611-e380bf2a-7a0d-48de-8fa8-6b1e342f0be7.png)
![Screenshot_2](https://user-images.githubusercontent.com/35392110/169667612-c9fa91e7-7aac-4a47-8316-c510f2453c51.png)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.11+
| PHP version      | 7.4
| Operating system | CloudLinux & [HumHub Hosting Plans](https://willywonka.humhub.com/dashboard)

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by spunkram** [comment] 2022-05-23 09:29
I hope the problem is solved immediately.

**Comment by ArchBlood** [comment] 2022-05-24 19:03
> this problem should be solved with an update , it is not healthy for us to produce manual solutions !

The solution is not a manual implementation, this will be in the next release.

**Comment by yurabakhtin** [comment] 2022-05-25 03:08
Yes, it is not manual solution, however if someone need it, then the real fix is in the single line https://github.com/humhub/humhub/pull/5720/files#diff-550160e418aa56e463e5eae9d6955ed1faefb2d1fa9755782f9690d7327586fcR52 just wrap by `decodeURI()`.

**Closed** 2022-05-25 16:49 UTC
Labels: Kind:BUG, Topic:Administration, Target: Master
