### ISSUE TITLE
Special Domains not supported in oEmbed URL

### ISSUE THREAD

**Issue by ArchBlood** [humhub/humhub#3667] opened 2019-10-01 04:37 UTC
### What steps will reproduce the problem?
Enter say iframe.ly endpoints and URL prefix then save.

### What is the expected result?
Multiple URL type support.

### What do you get instead?
.ly domain not shown after save but is shown in the database.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.x
| PHP version      | 7.x
| Operating system | CentOS

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment] 2019-10-01 08:38
Can you please give an example of the OEmbed configuration?

**Comment by ArchBlood** [comment] 2019-10-01 10:56
So earlier I entered the wrong endpoint URL into the option (e.g used http://embed.ly not http://embedly.com) and saved but doing so saved within the database but not from the HumHub instance admin section, but once I reapplied the prefix URL and the new endpoint it fixed this issue.

**Comment by buddh4** [comment] 2019-10-11 16:22
I don't fully understand the issue. I've added a endpiont with 

Url Prefix: embed.ly
Endpoint Url: http://embed.ly

And it saved as expected. Please provide a more detailed step by step description of your problem.

**Comment by ArchBlood** [comment] 2019-10-11 16:38
After reapplying (https://github.com/humhub/humhub/issues/3667#issuecomment-536983226) the issue doesn't show again, seems strange to me because it wasn't showing the saved data on the HumHub backend but was in the database itself.

- Use embed.ly or iframe.ly Url prefix
- Use the wrong endpoint (eg. https://api.embed.ly instead of https://api.embedly.com)
- Save

After this, it wasn't showing the save state of the oEmbed option provided but was showing from the database side.

**Comment by buddh4** [comment] 2019-10-11 16:54
Ok, strange in case you can reproduce this, let us know. I'll close this issue for now. One thing I noticed is that the url is not trimmed and the error message is not emphasized due to legac form usage.

**Closed by buddh4** 2019-10-11 16:54 UTC
