### ISSUE TITLE
v1.13 Beta - Updater fails

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5949] opened 2022-11-28 15:47 UTC
### What steps will reproduce the problem?

Run Updater from `v1.12.2` to `v1.13.0-beta.1` (not longer available)

### What is the expected result?

No errors

### What do you get instead?

![image](https://user-images.githubusercontent.com/4736168/204320738-2e2be370-ccc9-407f-a643-fec061f5dfef.png)

```
Exception (Unknown Property) 'yii\base\UnknownPropertyException' with message 'Getting unknown property: humhub\modules\user\models\User::auth_key' 

in /var/www/humhub/protected/vendor/yiisoft/yii2/base/Component.php:154

Stack trace:
#0 /var/www/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(296): yii\base\Component->__get()
#1 /var/www/humhub/protected/humhub/modules/user/models/User.php(271): yii\db\BaseActiveRecord->__get()
#2 /var/www/humhub/protected/humhub/modules/user/models/User.php(350): humhub\modules\user\models\User->__get()
#3 /var/www/humhub/protected/humhub/modules/user/models/User.php(355): humhub\modules\user\models\User->getAuthKey()
#4 /var/www/humhub/protected/vendor/yiisoft/yii2/web/User.php(706): humhub\modules\user\models\User->validateAuthKey()
#5 /var/www/humhub/protected/vendor/yiisoft/yii2/web/User.php(199): yii\web\User->renewAuthStatus()
#6 /var/www/humhub/protected/vendor/yiisoft/yii2/web/User.php(367): yii\web\User->getIdentity()
#7 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Component.php(139): yii\web\User->getIsGuest()
#8 /var/www/humhub/protected/humhub/components/i18n/I18N.php(53): yii\base\Component->__get()
#9 /var/www/humhub/protected/humhub/components/bootstrap/LanguageSelector.php(29): humhub\components\i18n\I18N->autosetLocale()
#10 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(325): humhub\components\bootstrap\LanguageSelector->bootstrap()
#11 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(69): yii\base\Application->bootstrap()
#12 /var/www/humhub/protected/humhub/components/Application.php(83): yii\web\Application->bootstrap()
#13 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(271): humhub\components\Application->bootstrap()
#14 /var/www/humhub/protected/humhub/components/Application.php(65): yii\base\Application->init()
#15 /var/www/humhub/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\components\Application->init()
#16 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct()
#17 /var/www/humhub/protected/humhub/components/Application.php(49): yii\base\Application->__construct()
#18 /var/www/humhub/index.php(25): humhub\components\Application->__construct()
#19 {main}
```

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.13 beta1
| PHP version      |  7.4
| Operating system |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by ArchBlood** [comment] 2022-11-28 22:20
From testing, the issue is fixed when you switch from using the new User model (v1.13 beta 1) to the previous version (v1.12.2).

**Comment by ArchBlood** [comment] 2022-11-28 22:29
Changing this line to `return $this->guid ?: $this->auth_key;` seems to also work.

**Comment by yurabakhtin** [comment] 2022-11-29 05:53
@luke- @ArchBlood Fixed in PR https://github.com/humhub/humhub/pull/5950

**Closed** 2022-11-29 10:47 UTC
Labels: Kind:BUG
