### ISSUE TITLE
Missing package from documentation

### ISSUE THREAD

**Issue by arimourao** [humhub/humhub#2131] opened 2016-12-03 19:25 UTC
After solving #2130, running `composer install`, I get the following error:

' Problem 1
    - zendframework/zend-ldap 2.7.1 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - zendframework/zend-ldap 2.7.0 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - zendframework/zend-ldap 2.6.1 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - zendframework/zend-ldap 2.6.0 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - zendframework/zend-ldap 2.5.2 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - zendframework/zend-ldap 2.5.1 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - zendframework/zend-ldap 2.5.0 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - Installation request for zendframework/zend-ldap ^2.5 -> satisfiable by zendframework/zend-ldap[2.5.0, 2.5.1, 2.5.2, 2.6.0, 2.6.1, 2.7.0, 2.7.1].
`

The requirement for php-ldap is mentionated as a optional package but I'm being forced to install. Documentation:
https://www.humhub.org/docs/guide-admin-requirements.html

**Comment by cebe** [comment] 2016-12-03 19:42
duplicate of https://github.com/humhub/humhub/issues/1588

**Comment by arimourao** [comment] 2016-12-03 19:42
The problem is solved removing the line `"zendframework/zend-ldap": "^2.5",` from the composer.json. But either the docs or the composer has to be properly updated.

**Closed** 2017-03-28 16:01 UTC
