### ISSUE TITLE
Changing default permissions for creating private or public space has no effect

### ISSUE THREAD

**Issue by triteamz** [humhub/humhub#3811] opened 2020-01-06 00:17 UTC
### What steps will reproduce the problem?
Following the HumHub instructions [found here](http://docs.humhub.org/admin-permissions.html).

Following is added to `protected/config/common.php`:

    'params' => [
        'defaultPermissions' => [
            '\humhub\modules\space\permissions\CreatePrivateSpace' => [
                \humhub\modules\user\models\User::USERGROUP_SELF => \humhub\libs\BasePermission::STATE_DENY,
                \humhub\modules\user\models\User::USERGROUP_USER => \humhub\libs\BasePermission::STATE_DENY,
                \humhub\modules\user\models\User::USERGROUP_FRIEND => \humhub\libs\BasePermission::STATE_DENY,
                \humhub\modules\user\models\User::USERGROUP_GUEST => \humhub\libs\BasePermission::STATE_DENY,
            ],
            '\humhub\modules\space\permissions\CreatePublicSpace' => [
                \humhub\modules\user\models\User::USERGROUP_SELF => \humhub\libs\BasePermission::STATE_DENY,
                \humhub\modules\user\models\User::USERGROUP_USER => \humhub\libs\BasePermission::STATE_DENY,
                \humhub\modules\user\models\User::USERGROUP_FRIEND => \humhub\libs\BasePermission::STATE_DENY,
                \humhub\modules\user\models\User::USERGROUP_GUEST => \humhub\libs\BasePermission::STATE_DENY,
            ],
        ],
    ],

### What is the expected result?
- When viewing Group Permissions, the default for `Create private space` and `Create public space` should be deny.
- When a user clicks on the "My Spaces" dropdown, the user should not see the option to "Create new space"

### What do you get instead?
- Group Permissions default is still set to "Allow"
- Users still see the option to "Create new space" in the "My Spaces" dropdown.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.19
| PHP version      | 7.2.16
| Operating system | CentOS Linux release 7.6.1810

**Comment by buddh4** [comment] 2020-01-14 10:51
`\humhub\modules\space\permissions\CreatePrivateSpace` and `\humhub\modules\space\permissions\CreatePublicSpace` is a global permission not a container permission so `\humhub\modules\user\models\User::USERGROUP_SELF` won't have any effect, you'll need to set the user group id as key.

**Comment by buddh4** [comment] 2020-03-11 15:08
Duplicate of https://github.com/humhub/humhub/issues/3841

**Closed by buddh4** 2020-03-11 15:08 UTC
Labels: Component:User, Kind:Enhancement
