### ISSUE TITLE
Humhub 1.17-beta fails permission check during install

### ISSUE THREAD

**Issue by poVoq** [humhub/humhub#7281] opened 2024-10-29 17:39 UTC
I am trying to install the 1.17-beta, but it fails the permissions check on the dynamic config on the second step of the installation.

Using the exact same system with the 1.16.2 release and identical file permissions this works.

**Comment by ArchBlood** [comment] 2024-10-29 19:27
Confirmed that v1.17 beta does seem to have an issue on the self check, I've even tried a number of set permission combinations, seems the specific requirements can't be met by all server types.

![Screenshot_1](https://github.com/user-attachments/assets/ffb5b398-a154-4adc-a3a0-abb6387262d9)

As a temporary fix I'd remove `realpath()` which seems to fix the issue
https://github.com/humhub/humhub/blob/e10bd87a12426ca8cef2a9cc61a21d20a51d76c6/protected/humhub/libs/SelfTest.php#L588

![Screenshot_2](https://github.com/user-attachments/assets/58dca1d6-b44f-4d32-a7ac-c8b0d794858b)

**Comment by ArchBlood** [comment] 2024-10-29 19:34
As to why `realpath()` is the issue, it can introduce complications with symlinks and relative paths used as it is currently, if it's still wanted or needed it should only be used conditionally.

**Comment by yurabakhtin** [comment] 2024-10-30 07:47
@luke- We changed the code for the issue https://github.com/humhub/humhub-internal/issues/412 in the PR https://github.com/humhub/humhub/pull/7250.
As I understand you had there the path `Yii::getAlias(Yii::$app->params['dynamicConfigFile'])` = `'./html/cms/content'`.

I have tested on my local Windows server the code:

- `Yii::$app->params['dynamicConfigFile']` =  `@config/dynamic.php`
- `Yii::getAlias(Yii::$app->params['dynamicConfigFile'])` = `D:\www\humhub\humhub/protected/config/dynamic.php`
- `realpath(Yii::getAlias(Yii::$app->params['dynamicConfigFile']))` = `D:\www\humhub\humhub\protected\config\dynamic.php`

![paths](https://github.com/user-attachments/assets/39c347bc-726f-4f52-ac71-c36ad70ce6ae)

@ArchBlood Could you please check what path values you have there so you see the check error?

**Comment by luke-** [comment] 2024-10-30 10:02
@yurabakhtin In my scenario, I had symlinked the “config” directory. Somehow the writable check didn't work there. Do you understand, why doesn't “realpath” work, correctly? Does this only affect Windows file systems?

**Comment by poVoq** [comment] 2024-10-30 10:30
I am on a standard Fedora 40 server system using btrfs.

**Comment by yurabakhtin** [comment] 2024-10-30 13:52
@luke- 

> Do you understand, why doesn't “realpath” work, correctly?

I don't understand because I don't see what really path has the issue.
From the screenshot I see the message `Make writable for the Webserver/PHP!`, but real code there is:

- `'Make {filePath} writable for the Webserver/PHP!', ['filePath' => $path]`

I guess the `$path = realpath(Yii::getAlias(Yii::$app->params['dynamicConfigFile']))` is `false` there, because it is rendered as empty string there.

> Does this only affect Windows file systems?

I don't have such problems on my local Windows server.

**Comment by luke-** [comment] 2024-10-30 16:23
@yurabakhtin Can you please check my PR? https://github.com/humhub/humhub/pull/7285

`realpath()` returns false when the file doesn't exist yet.

**Comment by ArchBlood** [comment] 2024-10-30 17:18
> @yurabakhtin In my scenario, I had symlinked the “config” directory. Somehow the writable check didn't work there. Do you understand, why doesn't “realpath” work, correctly? Does this only affect Windows file systems?

Also seems to be an issue on Linux as well, this only affects the installer which is rather weird as it does not have issues on a preinstalled instance;

### Solution with `realpath()`
```php
// Check Dynamic Config is Writable
$title = Yii::t('AdminModule.information', 'Permissions') . ' - ' . Yii::t('AdminModule.information', 'Dynamic Config');

$path = Yii::getAlias(Yii::$app->params['dynamicConfigFile']);

if (!is_file($path)) {
    $path = dirname($path);
}

// Use realpath on the path alone to get the canonical path
// Applying realpath to a boolean (from is_writable) would cause errors, so keep them separate
$realPath = realpath($path);

if ($realPath !== false && is_writable($realPath)) {
    $checks[] = [
        'title' => $title,
        'state' => 'OK',
    ];
} else {
    $checks[] = [
        'title' => $title,
        'state' => 'ERROR',
        'hint' => Yii::t('AdminModule.information', 'Make {filePath} writable for the Webserver/PHP!', ['filePath' => $path]),
    ];
}
```

**Comment by yurabakhtin** [comment] 2024-10-30 17:41
> `realpath()` returns false when the file doesn't exist yet.

@luke- if it works this way then your solution `if (is_writeable(realpath($path))) {` returns `false` and the issue will not be solved.
The @ArchBlood's solution from https://github.com/humhub/humhub/issues/7281#issuecomment-2447860049 looks more correctly I think.

**Comment by yurabakhtin** [comment] 2024-10-30 17:43
> @yurabakhtin Can you please check my PR? #7285

It seems we should apply new solution for all my changes from the PR https://github.com/humhub/humhub/pull/7250/files, right?

**Comment by luke-** [comment] 2024-10-30 18:46
@yurabakhtin No, I don't think we need to apply this to all changes from the merged PR. We should only remove the `realpath()`, when the dir/file is potentially not yet existing. Can you please check this?

I'm quite sure my PR is working, because we have two scenarios:

- `dynamic.php` exists: no problems here
- `and `dynamic.php` not exists: then the `realpath` is executed, after https://github.com/humhub/humhub/pull/7285/files#diff-864ee5d29be553a1a5776cf6cea6e7190eea1b0c7a03ef5edd005e8d2b87fe58R590

I'll merge my PR and test it again.

**Comment by yurabakhtin** [comment] 2024-10-31 06:29
@luke- I have tested the install process when the config file `dynamic.php` is deleted:

- on current `develop` branch (without your PR):
![no-config](https://github.com/user-attachments/assets/ceb6b5c0-e9ab-4499-a210-b17a3d407a36)

- on your PR I see all options are green, so yes please merge it.

**Comment by ArchBlood** [comment] 2024-10-31 08:31
> @luke- I have tested the install process when the config file `dynamic.php` is deleted:
> 
> * on current `develop` branch (without your PR):
>   ![no-config](https://private-user-images.githubusercontent.com/6995524/381848947-ceb6b5c0-e9ab-4499-a210-b17a3d407a36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNjMxOTEsIm5iZiI6MTczMDM2Mjg5MSwicGF0aCI6Ii82OTk1NTI0LzM4MTg0ODk0Ny1jZWI2YjVjMC1lOWFiLTQ0OTktYTIxMC1iMTdhM2Q0MDdhMzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMzFUMDgyMTMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTNiOTdmZGM4YmI1NjhkZjU2Yjg0MTcyNGEzNjYzYTgxNDViNjhlNTFkOGI4NjlhYjY4N2ZlMjhjNDhiMGU2MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.3pxO6qlr0dfHgRMS649QrUF9KkMR-kU5JwGgukfsM7w)
> * on your PR I see all options are green, so yes please merge it.

Also tested, although it does not take into account when permissions differ between the symlink and its target, example, the symlink might be writable, but `realpath()` could point to a target with different permissions completely, causing the `is_writable()` check to fail unexpectedly or is returned as `false` in this case, https://github.com/humhub/humhub/issues/7281#issuecomment-2447860049 is the only workaround that I can think of off the top of my head.

**Comment by luke-** [comment] 2024-10-31 10:57
@ArchBlood Thank you for your proposal. I have adopted it as it is really nicer to check for “false”.

@yurabakhtin Merged

**Closed by luke-** 2024-10-31 10:57 UTC
Labels: Kind:BUG
