### ISSUE TITLE
Preview text maxLength issue

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#4947] opened 2021-03-05 10:33 UTC
Summary mail:

![grafik](https://user-images.githubusercontent.com/9800854/110103886-c2bad780-7da6-11eb-8f02-3b1dca6d4e4f.png)

Text in community:

- `I think this is what I’m going to have to do, too. How difficult is it to integrate?`
- `I wanted to buy https://www.humhub.com/de/marketplace/massuserimport/ a few days ago. However...`

| Q                | A
| ---------------- | ---
| HumHub version   | 1.8.0

**Comment by yurabakhtin** [comment] 2021-04-12 09:13
@luke- PR https://github.com/humhub/humhub/pull/5004.

I could not reproduce the issue with cropped text `I...`, only I saw the content as plain text without html tags.
But I agree there was a wrong code, it seems it was copied from the file `protected/humhub/modules/comment/activities/views/newComment.php` where `RichText::preview($text, $maxLength = 0)`, so it was not correct to use an array for second param, it is why I changed to use `RichTextToHtmlConverter::process($text, $options = [])` because similar `RichTextToPlainTextConverter::process($text, $options = [])` is used in the file `protected/humhub/modules/comment/activities/views/mail/plaintext/newComment.php`.

Also similar issue was in the file `protected/humhub/modules/content/activities/views/mail/created.php`.

**Comment by luke-** [comment] 2021-04-13 09:54
@yurabakhtin I was able to reproduce the problem with the latest `master`:
![image](https://user-images.githubusercontent.com/4736168/114533999-d16e9700-9c4e-11eb-8259-19dd03f876f5.png)

Your PR looks a little different. Are you sure there are no other differences?
![image](https://user-images.githubusercontent.com/4736168/114534149-f6fba080-9c4e-11eb-8dfb-6c65b567dc2e.png)

**Comment by yurabakhtin** [comment] 2021-04-13 13:44
@luke- Ah yes if I test with the string `I wanted to buy https://www.humhub.com/de/marketplace/massuserimport/ a few days ago. However...` I get the same issue, but it strange why it works when I replace first word from `I` to `She`:

<img width="606" alt="master" src="https://user-images.githubusercontent.com/6995524/114561730-7d77a880-9c76-11eb-9641-74d8b0f97e5f.png">

after my PR it looks like this:

<img width="608" alt="PR" src="https://user-images.githubusercontent.com/6995524/114562185-f37c0f80-9c76-11eb-8f6c-fe57679b1e67.png">

Should I find a solution to remove space around the content, probably we should replace the quotes `"` with html tag `<blockquote>`?

**Comment by luke-** [comment] 2021-04-13 14:26
@yurabakhtin Currently, we have the entire comment as a plain text version in the Activity email.
With your PR, the comment will be rendered with formatting (images, tables, bulletlists, etc.). This is not intended in the current layout and sometimes looks quite broken (e.g. tables).
We should keep the current style and perhaps rework the email templates in the future and allow a more markup...

**Comment by yurabakhtin** [comment] 2021-04-14 05:13
@luke- I thought for HTML email template version we should use `RichTextToHtmlConverter` because for Plain text email template version we have `RichTextToPlainTextConverter`.
But it seems you don't want to render all html entities in the HTML email template, right?
Please explain what should be rendered and what not for the case of HTML email template.
Should we use the same `RichTextToPlainTextConverter` or create some new `RichTextToEmailHtmlConverter` especially for email html template?

**Comment by luke-** [comment] 2021-04-14 09:52
@yurabakhtin Whether we use plaintext or HTML depends on the specific case (e.g. MailSummary or Notification) and the position.

Before we change anything in the current behavior (e.g. plaintext -> HTML) we should do that separately in an issue and also do some design tests with different inputs here. Send me a quick message or open an issue if you have improvement ideas. But they are very welcome!

Current Behavior for Markdown should be:
- Acitvities/Mail Summary: All as plain text list for better reading. 
- Notification: Mostly about a single content, here with HTML if supported by email.

But we should use new `RichTextToEmailHtmlConverter` (from version 1.9 / develop) everywhere in emails instead of `RichTextToHtmlConverter` if possible 

https://github.com/humhub/humhub/blob/master/protected/humhub/widgets/mails/MailContentEntry.php#L69

https://github.com/humhub/humhub/pull/4995/files#diff-884458671d2c8536b1b764932003ea0fb105de274a6c0771bac2a7e2b36a5aac

**Comment by yurabakhtin** [comment] 2021-04-14 11:58
@luke- As I understood we should wait until the PR https://github.com/humhub/humhub/pull/4995 will be merged in to `develop` version 1.9 and then we will modify the new `RichTextToEmailHtmlConverter` to consider what we will render for email html messages, right?

**Comment by luke-** [comment] 2021-04-16 09:49
@yurabakhtin Yes, I would like to merge #4995 and then implement it in the "Develop" branch in various places where we already use RichOutput in e-mails. e.g. Notifications / Mail Module Notifies.

Do you have any idea how we can fix the specific problem of this issue?

**Comment by yurabakhtin** [comment] 2021-04-19 07:25
@luke- 

> Do you have any idea how we can fix the specific problem of this issue?

If you mean the issue when string like `I think this is what` is cropped to `I...` but the string "She thinks this is what" isn't cropped to `She...` then I have investigated this:

1. Firstly there was a wrong using of the function `RichText::preview($text, $maxLength = 0)` because the second param should be integer and not array as it was here https://github.com/humhub/humhub/pull/5004/files#diff-d4209389818765e2605ae051d95cd82e84b68178079a9880c93c64c8abd35b73L17
2. Then the wrong param value as array was passed on the `RichTextToPlainTextConverter::onAfterParse()`:

```php
if($maxLength > 0) {
    $result = Helpers::truncateText($result, $maxLength);
}
```

the function `Helpers::truncateText($text, $length)`:

```php
public static function truncateText($text, $length)
{
    $length = abs((int)$length);
    if (strlen($text) > $length) {
        $text = preg_replace("/^(.{1,$length})(\s.*|$)/s", '\\1...', $text);
    }
    $text = str_replace('<br />', '', $text);

    return trim($text);
}
```

here the array is converted to integer `1` by the code `abs((int)$length)` and then in regexp we have a rule `.{1,1}(\s.*` that can be applied for string started with word of 1 char like `I`.
I.e. if we call `RichText::preview(I think this is what, 1)` we get same result. If we want to crop the case with `She` we should use second param as 3, possible results:

- `RichText::preview('I think this is what', 1)` => `I...`
- `RichText::preview('She thinks this is what', 1)` => `She thinks this is what`
- `RichText::preview('She thinks this is what', 3)` => `She...`

Do you think we should fix the `Helpers::truncateText($text, $length)` in order to get result `She...` even when second param is less then first word of the `$text`?
If yes then I can try to find a solution otherwise we can merge the PR https://github.com/humhub/humhub/pull/5004 because there I already fixed the wrong using of the `RichText::preview()`.

**Comment by luke-** [comment] 2021-04-19 10:36
@yurabakhtin Thank you for the analysis.  

Since the `options` as 3rd parameter in the PHPDoc for `Richtext::preview` was intended but not implemented, I have now changed the following: https://github.com/humhub/humhub/pull/5023/files

What do you think about this solution?

Otherwise we can also take #5004, but then we should at least use the `RichTextToPlainTextConverter` instead of `RichTextToHtmlConverter` and maybe mark `Richtext::preview` as deprecated.

**Comment by yurabakhtin** [comment] 2021-04-20 05:30
@luke- Yes, your solution works well, we can use it but please see what difference between `Richtext::preview()` and `RichTextToPlainTextConverter::process()`:

<img width="1198" alt="comparing" src="https://user-images.githubusercontent.com/6995524/115341591-8fdf6e00-a1b1-11eb-9f46-dcc2b43ba667.png">

I think the `Richtext::preview()` renders images better than `RichTextToPlainTextConverter::process()`.
I used in my solution `RichTextToHtmlConverter::process()` because I thought for HTML version of email message we should display all html tags and images, but if it is enough to display plain text then yes we can use your solution.

**Comment by luke-** [comment] 2021-04-20 08:07
@yurabakhtin Thanks, ok then I'll merge my PR. 

In the mails of the Mail Summaries (Activity) we currently always use Plain Text. We want to keep it that way for the time being, because it is easier to read when there is a lot of content.

That's right, `RichText::preview` seems to use the `RichTextToShortTextConverter`, which indeed displays image links better.

**Closed by luke-** 2021-04-20 08:07 UTC
Labels: Kind:BUG
