### ISSUE TITLE
Numbers of Follower/Followed at User Profile Header is different from UserListBox.

### ISSUE THREAD

**Issue by tosintech-web** [humhub/humhub#5341] opened 2021-10-11 14:50 UTC
### Is your feature request related to a problem? Please describe.
Ver 1.9
User Profile header, UserListBox shows only users whose status is enabled.
But, follower counter shows the number include disabled users.

### Describe the solution you'd like
I think they may show same number to avoid user confuse.

### Describe alternatives you've considered
protected/humhub/modules/conntrollers/ProfileController.php
What do you think about that "$query" of pubic function actionFollowedUserList() and actionFollowerList() would be arranged? Or protected/humhub/modules/user/bihaviors/Followable.php public function getFollowerCount() and getFollowingCount() would be arranged?

**Comment by luke-** [comment] 2021-10-11 17:47
@yurabakhtin Can you please take a look here? Maybe this issue is already fixed, because I've merged this PR https://github.com/humhub/humhub/pull/4879/files into `develop`. In this PR you refactored the Following queries a bit.

**Comment by yurabakhtin** [comment] 2021-10-12 12:33
@luke- Yes, the issue was fixed in the PR https://github.com/humhub/humhub/pull/4879 because I can reproduce this only on `master` branch with version `1.9.2`:

<img width="1152" alt="followers_master" src="https://user-images.githubusercontent.com/6995524/136955733-8a86079a-c340-460f-a586-5343795ca469.png">

but on `develop` branch with version `1.10.0-beta.1` it works well because the PR was merged there:

<img width="1153" alt="followers_develop" src="https://user-images.githubusercontent.com/6995524/136956419-a469fe22-a0ba-4558-88a6-b0f8db419d18.png">

If need we can create a quick fix for `master` branch.

**Closed as completed** 2021-10-12 12:43 UTC
Labels: Kind:BUG

**Comment by tosintech-web** [comment] 2021-10-13 14:09
Thank you, @yurabakhtin @luke-
