### ISSUE TITLE
Getting identity in command line can throw an exception on Humhub 1.14

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#6347] opened 2023-05-23 13:10 UTC
### What steps will reproduce the problem?

I didn't succeed to reproduce the problem, but I often get exception errors on several Humhub instances, on code executed by cron job.

Update: see first comment

The origin is various, but they all fail at this step:

```php
yii\web\User->getIdentity()
```

### What is the expected result?

Returns `null`

### What do you get instead?

```
yii\base\UnknownMethodException: Calling unknown method:
humhub\components\console\Application::getSession() in
/usr/www/humhub/protected/vendor/yiisoft/yii2/base/Component.php:300
Stack trace:
#0
/usr/www/humhub/protected/vendor/yiisoft/yii2/web/User.php(690):
yii\base\Component->__call()
#1
/usr/www/humhub/protected/vendor/yiisoft/yii2/web/User.php(199):
yii\web\User->renewAuthStatus()
```

### Additional info

The problem is here: https://github.com/yiisoft/yii2/blob/master/framework/web/User.php#LL196C17-L196C17

`$this->enableSession` should be false (as executed by cron job), but sometimes it's true.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.14.1
| PHP version      | 7.4 and 8.2
| Operating system | Ubuntu 20.04

**Comment by funkycram** [comment] 2023-05-24 08:34
@luke- This issue is now quite a problem and occurs very often. It might create database corruptions.
It's since version 1.14 (I don't know exactly which sub version).

I've finally funded a way to reproduce the bug.

1. Create a space whose URL is "test"
2. In command line, execute this script:
```php
$space = Space::findOne(['url' => 'test']);
$space->delete();
```

Result:
```
Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: humhub\components\console\Application::getSession()'

in /www/humhub/protected/vendor/yiisoft/yii2/base/Component.php:300

Stack trace:
#0 /www/humhub/protected/vendor/yiisoft/yii2/web/User.php(690): yii\base\Component->__call()
#1 /www/humhub/protected/vendor/yiisoft/yii2/web/User.php(199): yii\web\User->renewAuthStatus()
#2 /www/humhub/protected/vendor/yiisoft/yii2/web/User.php(377): yii\web\User->getIdentity()
#3 /www/humhub/protected/vendor/yiisoft/yii2/base/Component.php(139): yii\web\User->getId()
#4 /www/humhub/protected/humhub/components/ActiveRecord.php(64): yii\base\Component->__get()
#5 /www/humhub/protected/humhub/modules/content/models/Content.php(230): humhub\components\ActiveRecord->beforeSave()
#6 /www/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(792): humhub\modules\content\models\Content->beforeSave()
#7 /www/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(680): yii\db\BaseActiveRecord->updateInternal()
#8 /www/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(679): yii\db\ActiveRecord->update()
#9 /www/humhub/protected/humhub/modules/content/services/ContentStateService.php(145): yii\db\BaseActiveRecord->save()
#10 /www/humhub/protected/humhub/modules/content/services/ContentStateService.php(165): humhub\modules\content\services\ContentStateService->update()
#11 /www/humhub/protected/humhub/modules/content/models/Content.php(396): humhub\modules\content\services\ContentStateService->delete()
#12 /www/humhub/protected/humhub/modules/content/models/Content.php(350): humhub\modules\content\models\Content->softDelete()
#13 /www/humhub/protected/humhub/modules/content/Events.php(66): humhub\modules\content\models\Content->delete()
#14 [internal function]: humhub\modules\content\Events::onSpaceDelete()
#15 /www/humhub/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func()
#16 /www/humhub/protected/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger()
#17 /www/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(1025): yii\base\Component->trigger()
#18 /www/humhub/protected/humhub/modules/space/models/Space.php(329): yii\db\BaseActiveRecord->beforeDelete()
#19 /www/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(754): humhub\modules\space\models\Space->beforeDelete()
#20 /www/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(724): yii\db\ActiveRecord->deleteInternal()
#21 /www/humhub/protected/modules/maintenance/commands/MaintenanceController.php(161): yii\db\ActiveRecord->delete()
#22 [internal function]: humhub\modules\maintenance\commands\MaintenanceController->actionTest()
#23 /www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#24 /www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#25 /www/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction()
#26 /www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction()
#27 /www/humhub/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#28 /www/humhub/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction()
#29 /www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest()
#30 /www/humhub/protected/yii(29): yii\base\Application->run()
#31 {main}
```

**Comment by funkycram** [comment] 2023-05-25 10:36
@yurabakhtin do you know what changed on Humhub 1.14 about this issue?
This bug affects many services, e.g. the Mass Notification module doesn't work anymore because of `$space->getPermissionManager($senderUser)->can(CanSendMassNotification::class)` in the cron job.
Don't hesitate if I can help. Thanks!

**Comment by funkycram** [comment] 2023-05-25 11:08
@yurabakhtin @luke- This PR fixes the problem: https://github.com/humhub/humhub/pull/6354
But I'm not sure at all it's the correct way.
I've added the fix to the CHANGELOG.md for Humhub 1.14.3

**Comment by funkycram** [comment] 2023-05-25 16:10
Thanks for your tests. I cannot reproduce either on the develop branch but I do on the 1.14.2 installed from the ZIP file.
Now I'm going to try on a fresh install and see if it's caused by a module.

**Comment by funkycram** [comment] 2023-05-25 17:40
@luke- @yurabakhtin after many tests I finally found the combination to reproduce the bug.

1. Install a fresh Humhub 1.14.2 from ZIP
2. Install **REST module** v0.9.0 (you don't need to activate it, it makes no difference)
3. Install AND activate the **FILES module** v0.16.1
4. In command line, execute this command: `php yii user/create admin1 admin1@mail.com Admin One`

If REST module is uninstalled, or FILES module is disabled, there is no bug!

```
Stack trace:
#0 /home/marc/www/hhtest/protected/vendor/yiisoft/yii2/web/User.php(690): yii\base\Component->__call()
#1 /home/marc/www/hhtest/protected/vendor/yiisoft/yii2/web/User.php(199): yii\web\User->renewAuthStatus()
#2 /home/marc/www/hhtest/protected/vendor/yiisoft/yii2/web/User.php(377): yii\web\User->getIdentity()
#3 /home/marc/www/hhtest/protected/vendor/yiisoft/yii2/base/Component.php(139): yii\web\User->getId()
#4 /home/marc/www/hhtest/protected/humhub/components/ActiveRecord.php(56): yii\base\Component->__get()
#5 /home/marc/www/hhtest/protected/humhub/modules/space/models/Membership.php(149): humhub\components\ActiveRecord->beforeSave()
#6 /home/marc/www/hhtest/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(600): humhub\modules\space\models\Membership->beforeSave()
#7 /home/marc/www/hhtest/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(570): yii\db\ActiveRecord->insertInternal()
#8 /home/marc/www/hhtest/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(676): yii\db\ActiveRecord->insert()
#9 /home/marc/www/hhtest/protected/humhub/modules/space/behaviors/SpaceModelMembership.php(464): yii\db\BaseActiveRecord->save()
#10 [internal function]: humhub\modules\space\behaviors\SpaceModelMembership->addMember()
#11 /home/marc/www/hhtest/protected/vendor/yiisoft/yii2/base/Component.php(297): call_user_func_array()
#12 /home/marc/www/hhtest/protected/humhub/modules/user/models/User.php(642): yii\base\Component->__call()
#13 /home/marc/www/hhtest/protected/humhub/modules/user/models/User.php(594): humhub\modules\user\models\User->setUpApproved()
#14 /home/marc/www/hhtest/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(615): humhub\modules\user\models\User->afterSave()
#15 /home/marc/www/hhtest/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(570): yii\db\ActiveRecord->insertInternal()
#16 /home/marc/www/hhtest/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(676): yii\db\ActiveRecord->insert()
#17 /home/marc/www/hhtest/protected/humhub/modules/user/commands/UserController.php(78): yii\db\BaseActiveRecord->save()
#18 [internal function]: humhub\modules\user\commands\UserController->actionCreate()
#19 /home/marc/www/hhtest/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#20 /home/marc/www/hhtest/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#21 /home/marc/www/hhtest/protected/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction()
#22 /home/marc/www/hhtest/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction()
#23 /home/marc/www/hhtest/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#24 /home/marc/www/hhtest/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction()
#25 /home/marc/www/hhtest/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest()
#26 /home/marc/www/hhtest/protected/yii(29): yii\base\Application->run()
#27 {main}
```

**Comment by yurabakhtin** [comment] 2023-05-26 13:12
@funkycram Thank you for the detailed instruction for the reproduce!

@luke- I find after insert new User all modules are initialized so the code is called from REST module https://github.com/humhub/rest/commit/6dee550#diff-074f64cd19bc13bc527290951a58a65cb54f2f35a43ce5bf95e5dbb20b4d297dR37:

```php
Yii::$app->set('user', [
    'class' => UserComponent::class,
    'identityClass' => UserModel::class,
]);
```

i.e. before call event triggers we have `\Yii::$app->user->enableSession === false` but after set new user the `\Yii::$app->user->enableSession` is updated to `true`.

I still need to investigate how to fix the module REST API because I didn't work on the changes.

**Comment by funkycram** [comment] 2023-05-26 13:31
Thanks @yurabakhtin .
I think the problem is more global, because it doesn't only occurs on user creation, but on various cron jobs.
But, yes it's related to the REST module, but perhaps the File module too, as it seems better (at least on my latest tests) when disabling it.

**Comment by yurabakhtin** [comment] 2023-05-26 13:45
@luke- @funkycram Fixed in PR https://github.com/humhub/rest/pull/126.

**Comment by funkycram** [comment] 2023-05-26 16:32
Thanks very much @yurabakhtin !
Tested, it fixes the bug!

**Closed** 2023-05-26 17:01 UTC
Labels: Kind:BUG
