### ISSUE TITLE
Registration token rendered using PHP 8.0.9

### ISSUE THREAD

**Issue by ArchBlood** [humhub/humhub#5244] opened 2021-08-14 22:09 UTC
### What steps will reproduce the problem?
1. Switch to PHP 8.0.9
2. Use PHP to send mail
3. Register an account normally
4. Check email for token through HTML and plaintext

### What is the expected result?
The token generated shouldn't show a `3D` before the token and after `=` which should match the database entry

### What do you get instead?
https://github.com/humhub/humhub/pull/5234#issuecomment-897708586

### Additional info
No console errors or logs were reported just an error stating an invalid token, I've also confirmed that it only happens in PHP 8.0.9 and not other versions are affected, further testing would be advised 🤔
| Q                | A
| ---------------- | ---
| HumHub version   | 1.9.0
| PHP version      | 8.0.9
| Operating system | CloudLinux

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment] 2021-08-16 15:29
@ArchBlood I cannot reproduce this with PHP 8.0.9.

**Comment by Reuns** [comment] 2021-11-04 07:47
Reproduced on 8.0.11

**Comment by luke-** [comment] 2021-11-04 10:13
Hmm I've tried with PHP 8.0.12 and still cannot reproduce:

![image](https://user-images.githubusercontent.com/4736168/140296217-5036b5aa-5e57-4a1a-857e-fcb0000eca4a.png)

![image](https://user-images.githubusercontent.com/4736168/140296271-168be66e-95de-41b8-a52e-de5c56591c0f.png)


Which E-Mail Client causing the error?

**Comment by ArchBlood** [comment] 2021-11-04 10:55
> Hmm I've tried with PHP 8.0.12 and still cannot reproduce:
> 
> ![image](https://user-images.githubusercontent.com/4736168/140296217-5036b5aa-5e57-4a1a-857e-fcb0000eca4a.png)
> 
> ![image](https://user-images.githubusercontent.com/4736168/140296271-168be66e-95de-41b8-a52e-de5c56591c0f.png)
> 
> Which E-Mail Client caused the error?

I've used Gmail, SquirrelMail, RoundCube, Horde, Zimbra, Rainloop, Outlook, and finally ProtonMail with the same issue occurring in each if PHP 8.0.9+ is used, I would like to note that this did not happen in any of the beta runs of 1.9 but after stable release.

**Comment by ArchBlood** [comment] 2021-11-04 10:56
My only guess would be that there is a missing or added extension between PHP 7.4 and 8.0.x that is causing the error but I've not had the time to do any more tests

**Comment by Reuns** [comment] 2021-11-04 11:18
Same here.
All I can provide is : 
![image](https://user-images.githubusercontent.com/19529531/140079109-40875c0f-ae0f-49b0-a2f9-6a2cd3b36ffd.png)
![image](https://user-images.githubusercontent.com/19529531/140079317-fd33cfb6-7deb-4b30-84e2-6f9c8fa388d8.png)

**Comment by luke-** [comment] 2021-11-04 12:00
Can you provide me a link where I can try the registration via gmail?

**Comment by Reuns** [comment] 2021-11-04 12:35
You can try here https://www.high-score.fr/

**Comment by luke-** [comment] 2021-11-04 17:04
@Reuns Thanks for the test access, there I can recreate the problem. Unfortunately not on my systems. 

@ArchBlood Do you mean this bug is between this versions?
https://github.com/humhub/humhub/compare/v1.9.0-beta.2...v1.9.0

**Comment by ArchBlood** [comment] 2021-11-04 17:11
> @Reuns Thanks for the test access, there I can recreate the problem. Unfortunately not on my systems. 
> 
> @ArchBlood Do you mean this bug is between this versions?
> https://github.com/humhub/humhub/compare/v1.9.0-beta.2...v1.9.0

Yes, it is between the last beta of 1.9 and stable version and continues onto newer versions.

**Comment by Reuns** [comment] 2021-11-26 13:15
Problem still here on 1.10

**Comment by luke-** [comment] 2021-11-26 13:45
@yurabakhtin Can you take a look into this?

**Comment by yurabakhtin** [comment] 2021-12-01 14:35
@luke- I have tested HumHub versions 1.10+ with php 8.0.8 and 8.0.12, for me the links work well, i.e. I can click and open expected page:

<img width="1187" alt="gmail_html" src="https://user-images.githubusercontent.com/6995524/144253497-652784e5-1163-4498-ae04-ab1c6e8c5a8b.png">

I find the `3D` chars only in source:

<img width="1187" alt="gmail_source" src="https://user-images.githubusercontent.com/6995524/144251987-7e864b9c-f154-46d7-9afe-8f61d4bab52c.png">

Same if I use default mail app on macos:

<img width="1313" alt="app_mail" src="https://user-images.githubusercontent.com/6995524/144252080-76cfa77f-b6e3-4e9b-9e19-303d6d0ef50c.png">

@ArchBlood In my case on the html side I get the link like:

```html
<a href="http://site.test/user/registration?token=QJFk6Ray5L1v">
    <strong>Sign up</strong>
</a>
```

and on the source:

```html
<a href=3D"http://site.test/user/registration?token=3DQJFk6Ray5L1v">
    <strong>Sign up</strong>
</a>
```

Could you show us what you see on the html and source side?
Thanks.

**Comment by Reuns** [comment] 2021-12-01 15:19
Hi @yurabakhtin,
This is what I have in source
TXT
`S'inscrire: https://www.high-s=
core.fr/user/registration?token=3DWPe2izoTCK1L`
![image](https://user-images.githubusercontent.com/19529531/144261134-c046741f-e45b-455c-acff-7374b5973e9c.png)
HTML
`<a href=3D"https://www.high-score.fr/user=
/registration?token=3DWPe2izoTCK1L"
                                     =
                          style=3D"text-decoration: none; color: #fff; font=
-weight: 300;">
                                                         =
       <strong>S'inscrire</strong>
                                      =
                      </a>`
![image](https://user-images.githubusercontent.com/19529531/144261505-3d2b7258-237b-483c-9bb8-2dd08af00874.png)

Hope it'll help you.

**Comment by ArchBlood** [comment] 2021-12-01 16:44
> Hi @yurabakhtin,
> This is what I have in source
> TXT
> `S'inscrire: https://www.high-s=
> core.fr/user/registration?token=3DWPe2izoTCK1L`
> ![image](https://user-images.githubusercontent.com/19529531/144261134-c046741f-e45b-455c-acff-7374b5973e9c.png)
> HTML
> `<a href=3D"https://www.high-score.fr/user=
> /registration?token=3DWPe2izoTCK1L"
>                                      =
>                           style=3D"text-decoration: none; color: #fff; font=
> -weight: 300;">
>                                                          =
>        <strong>S'inscrire</strong>
>                                       =
>                       </a>`
> ![image](https://user-images.githubusercontent.com/19529531/144261505-3d2b7258-237b-483c-9bb8-2dd08af00874.png)
> 
> Hope it'll help you.

I've been getting the same results.

**Comment by yurabakhtin** [comment] 2021-12-02 07:57
@Reuns Thank you for the source. If I got it correctly:

- on the source side you have the urls like `/registration?token=3DWPe2izoTCK1L`, that is ok.
- but your mail clients don't remove the `3D` on open the link, that is wrong.

For me it looks like the problem only in the mail client side.

**Comment by Reuns** [comment] 2021-12-02 10:22
@yurabakhtin 
This option has already been discarded. I'm using Gmail (as you do in your test). I've also tested roundcube ...  no more success.
Would you please, try to register on https://www.high-score.fr and let me know what is happening ?

**Comment by yurabakhtin** [comment] 2021-12-02 11:09
@Reuns I have registered and yes there is a problem:

<img width="1289" alt="broken" src="https://user-images.githubusercontent.com/6995524/144409212-c1d52d1f-6de9-4426-a178-ca4e2326d552.png">

Compare with my version from test server:

<img width="1289" alt="localhost" src="https://user-images.githubusercontent.com/6995524/144409757-f067ee04-e594-4c92-9072-5d6235eaf72c.png">

What I find from the comparing is that my version has:

```
Message-ID: <f280227f8e2856d*******7c372@humhub.yb>
Date: Wed, 01 Dec 2021 16:38:35 +0300
From: HumHub <social@example.com>
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="_=_swift_v4_1638365915_708e718e6055821cc94aefb5a976b9fb_=_"
```

but the server `high-score.fr` looks like adds a new header line `X-Google-Original-Message-ID` and then all next lines are printed in single line, but it should be like this for correct version:

```
Message-ID: <61a89f7d.1c69fb81.1687f.ff39SMTPIN_ADDED_BROKEN@mx.google.com>
X-Google-Original-Message-ID: <cd064*********da66@www.high-score.fr>
Date: Thu, 02 Dec 2021 11:27:03 +0100
From: High-Score <noreply@high-score.fr>
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="_=_swift_v4_1638440823_cdf991785fe9ff2be7203a1d84e3e67e_=_"
```

I.e. if the `Content-Type` with data `boundary` will be started with new line then the bug will be solved, so we need to find what code breaks these data, or why it happens only on php8 or maybe some setting from config of the php8 does this.

**Comment by yurabakhtin** [comment] 2021-12-02 11:38
@Reuns If we look at the end of mail headers where the expected new line is lost before `Content-Type`:

```
Message-ID: <61a8*****@mx.google.com>
X-Google-Original-Message-ID: <c****dc8@www.high-score.fr> Date: Thu, 02 Dec 2021 12:27:18 +0100 From: High-Score <noreply@high-score.fr> MIME-Version: 1.0 Content-Type: multipart/alternative;
  boundary="_=_swift_v4_1638444438_a76f221855ba150d633749d0c7fd8069_=_"
X-Spam-Status: No
X-MailPropre-MailScanner-From: noreply@high-score.fr
X-MailPropre-MailScanner-SpamCheck: not spam, SpamAssassin (not cached, score=0.131, required 5, autolearn=disabled, GMAILCOM 0.01, INVALID_MSGID 0.10, KAM_SHORT 1.00, RCVD_IN_DNSWL_HI 0.01, SPF_HELO_NONE 0.00, SPF_PASS -1.00, TOGMAIL 0.01)
X-MailPropre-MailScanner: Not scanned: please contact your Internet E-Mail Service Provider for details
X-MailPropre-MailScanner-ID: 492021002FD.A885D
X-MailPropre-MailScanner-Information: Please contact the ISP for more information
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/relaxed; d=high-score.fr; s=default; h=Date:Sender:From:Message-ID:Subject:To:Reply-To :Cc:MIME-Version:Content-Type:Content-Transfer-Encoding:Content-ID: Content-Description:Resent-Date:Resent-From:Resent-Sender:Resent-To:Resent-Cc :Resent-Message-ID:In-Reply-To:References:List-Id:List-Help:List-Unsubscribe: List-Subscribe:List-Post:List-Owner:List-Archive; bh=q8a/j/HjyKN9j/9U***KAlbY=; b=e5Vw5****514ikwxt3 YfiPhgmAKa9rPfp******k9FNvyDoPEqFLqF6funolWYWwQbM6w0x4UVdSHHJVUcr8L Xfboimrg==;
To: ****@gmail.com
Subject: Welcome to High-Score.fr
From: noreply@high-score.fr
Sender: <****h.net>
Date: Thu, 02 Dec 2021 12:27:18 +0100
X-AntiAbuse: This header was added to track abuse, please include it with any abuse report
X-AntiAbuse: Primary Hostname - wisconsin.o2switch.net
X-AntiAbuse: Original Domain - gmail.com
X-AntiAbuse: Originator/Caller UID/GID - [1079 994] / [47 12]
X-AntiAbuse: Sender Address Domain - high-score.fr
X-Get-Message-Sender-Via: wisconsin.o2switch.net: authenticated_id: b****/from_h
X-Authenticated-Sender: ****h.net: noreply@high-score.fr
X-Source: 
X-Source-Args: 
X-Source-Dir: brr****.fr
```

I see there are headers of some tools `MailScanner` and `AntiAbuse`.
I don't find any code related to them on HumHub and Yii code sides.
What if the tools are executed only on your provider server side?
Could please review settings of your server and if you find something similar then please disable it and try send a message. Thanks.

**Comment by Reuns** [comment] 2021-12-02 15:35
I can't find anything in settings. I should call the hotline.
BTW, these element already exist with php 7.4 and mails are correct.


Meanwhile I've found a solution (which won't help you) : using SMTP transport instead of PHP.
(It won't correct the bug, but it'll do for me.)

**Comment by yurabakhtin** [comment] 2021-12-02 16:23
@Reuns Thank you for the info.

> BTW, these element already exist with php 7.4 and mails are correct.

Do you mean on php 7.4 you have the same broken headers in single line but email message is rendered correctly by mail client?

**Comment by Reuns** [comment] 2021-12-03 09:49
@yurabakhtin I mean, MailPropre/MailScanner and AntiAbuse. already exists on php 7.4
This one is on 7.4 and works great
![7 4-good](https://user-images.githubusercontent.com/19529531/144582023-d4c0bfd5-6dbd-4495-ad99-6dae62f04b12.jpg)

**Comment by ArchBlood** [comment] 2021-12-05 21:31
Every time I try to wrap my head around this issue, it just keeps bringing me back to this line of code;
https://github.com/humhub/humhub/blob/db4c34776df7add919a9b0ecb49848651ee289b1/protected/humhub/modules/content/widgets/richtext/converter/RichTextToEmailHtmlConverter.php#L62

I'm not exactly sure why. 🤔

**Comment by yurabakhtin** [comment] 2021-12-06 08:26
@ArchBlood The code is related only for image urls:

<img width="689" alt="image_token" src="https://user-images.githubusercontent.com/6995524/144809783-20d91b75-d39f-4af0-8351-62d8b8f4e0a8.png">

The image token was developed in order to view images in email messages when user is not logged in currently in the email client as the humhub user. For info you can read here https://github.com/humhub/news/issues/23.

---

but above we tell about registration urls:

<img width="659" alt="reg_token" src="https://user-images.githubusercontent.com/6995524/144809822-b3553287-a93d-422e-bc97-7d2dca0a2fa0.png">

The registration token in generated here https://github.com/humhub/humhub/blob/db4c34776df7add919a9b0ecb49848651ee289b1/protected/humhub/modules/user/models/Invite.php#L146

However the current issue is not related to the token param at all. It is related to encoding email messages with chars `3D` which are added each char `=`. Unfortunately I still cannot find what code or what server tool breaks the email message, especially the email header `Content-Type: ` + `boundary` as I investigated above.

**Comment by luke-** [comment] 2021-12-06 09:01
@ArchBlood If you are having this problem, maybe you can give Yura a test account on your server? I also find your comment interesting that the problem only occurs from a certain HumHub version.

**Comment by ArchBlood** [comment] 2021-12-07 16:49
> @ArchBlood If you are having this problem, maybe you can give Yura a test account on your server? I also find your comment interesting that the problem only occurs from a certain HumHub version. 

Currently we're still down so I'm not able to create a test account as our server manager is still working things out with our current server providers, once we've resolved our issues on their end we'll be more than happy to help

**Comment by ArchBlood** [comment] 2022-01-30 21:25
Alright, so I've also gone ahead and tested with PHP 8.1.2, same results as in PHP 8

Can be tested here: https://discuss.greenmeteor.net/dashboard
If needed I can also provide an email for the mail client side.

**Comment by Reuns** [comment] 2022-04-28 13:48
Problem still exists with Humhub 1.11.1

**Comment by luke-** [comment] 2022-06-10 08:32
Shoudl be fixed with the Symfony Mailer

**Closed by luke-** 2022-06-10 08:32 UTC
Labels: Kind:BUG, Status:Unable to reproduce, Status:Need investigation
