### ISSUE TITLE
APCu Support

### ISSUE THREAD

**Issue by Felli** [humhub/humhub#2167] opened 2016-12-21 07:22 UTC
When will APCu Support be available in Humhub if ever?

**Comment by cebe** [comment] 2016-12-21 23:05
duplicate of #2005, if you have time you can complete #2015 to get it merged.

**Comment by Felli** [comment] 2016-12-22 00:03
@cebe thanks for bring those up, but this is a general question of when it will be supported that is all, I am guessing it will be available in 1.2 hopefully. :smile:

**Comment by cebe** [comment] 2016-12-22 00:44
you can already use it by manual configuration. It is just not automatic. Also this is open source, you can have it in 1.1.x if the pull request gets completed ;)

**Closed** 2016-12-28 15:51 UTC
