### ISSUE TITLE
Database Exception – yii\db\Exception

### ISSUE THREAD

**Issue by scysys** [humhub/humhub#1851] opened 2016-07-11 19:06 UTC
On Installation

```
Database Exception – yii\db\Exception

SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '' for column 'deadline' at row 1
The SQL being executed was: UPDATE `task` SET `deadline`=NULL WHERE deadline = "" OR deadline = "0000-00-00 00:00:00"
Error Info: Array
(
    [0] => 22007
    [1] => 1292
    [2] => Incorrect datetime value: '' for column 'deadline' at row 1
)
↵
Caused by: PDOException

SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '' for column 'deadline' at row 1

in /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/Command.php at line 844
```

**Comment by scysys** [comment] 2016-07-11 19:37
I better search next time :)

Adding `sql_mode = ALLOW_INVALID_DATES` to mysql cnf fix this problem.
I think it´s only occur after mysql 5.6

**Comment by cebe** [comment] 2016-07-11 21:39
duplicate of https://github.com/humhub/humhub-modules-tasks/issues/29 ?

**Comment by scysys** [comment] 2016-07-12 13:01
Yes

**Comment by MatthiasHertel** [comment] 2016-07-12 13:14
#1786 

this one .... there is a specification of this issue

**Comment by scysys** [comment] 2016-07-12 13:22
yes, thanks matthias. already solved

**Closed** 2016-07-14 12:53 UTC

**Comment by Buliwyfa** [comment] 2016-08-12 00:50
Similar error
On 1.0.1 community edition and ee
On 1.1.0-beta.2 (community edition and ee)
Using wamp with php 7.03 or 5.6.24, Mysql 5.71.11, & Apache. 
OS default time settings are for Spain.
ERROR happens when:
- Trying to enable Task module 
- Trying to install Task module
- During installation if any profiles that used it is select: “My company” or “My club” 
NO error during installation if I chose “Skip this step, I want to set up everything manually”, ”My educational institution” or “My community”

Community edition error
![sqlstate 22007 invalid datetime format 1292 _](https://cloud.githubusercontent.com/assets/13509685/17609658/60ef38a2-6037-11e6-809c-7d9558b9b80b.png)

EE error
![sqlstate 22007 invalid datetime format 1292 _ ee](https://cloud.githubusercontent.com/assets/13509685/17609661/6d191666-6037-11e6-88a5-cde345377c16.png)

**Comment by brucelane** [comment] 2017-02-06 14:50
hi, I'm on a new ubuntu 16.04 server
I tryed to add the line from  https://github.com/humhub/humhub-modules-tasks/pull/30/files without success..
in which file should I add sql_mode = ALLOW_INVALID_DATES ?
