### ISSUE TITLE
Prevent guest to access dashboard

### ISSUE THREAD

**Issue by byndstd** [humhub/humhub#2647] opened 2017-06-28 12:29 UTC
On my setting I did give the permission to guest to access public spaces 
Allow limited access for non-authenticated users (guests)
But I see that the gust still access to dashboard ; is it possible to prevent guest to access any page except public spaces , and keep dashboard to only members as usual

Thank you

**Comment by buddh4** [comment] 2017-06-28 13:10
Currently not, but its planned to add a permission for this purpose.

**Comment by byndstd** [comment] 2017-06-28 15:39
ah ok ; 
Thank you

**Comment by buddh4** [comment] 2017-06-28 15:49
But what do you want them to see if not the dashboard?
Since the dashboard only shows public content this should not be a problem and the default page can be configured anyways.

**Comment by byndstd** [comment] 2017-06-28 15:55
well I want the guest to access the public spaces directly
on the dashboard he will get the registration or log in form.

**Comment by buddh4** [comment] 2017-06-28 16:12
ok, you should be able to change the default page as follows: https://github.com/humhub/humhub/issues/1828.

You could trigger the login/register form by using javascript something like:

```
$(document).on('humhub:ready', function() {
    var viewState = humhub.modules.ui.view.getState();
    if(viewState.moduleId == 'dashboard' && viewState.controllerId == 'dashboard') {
        $('.btn-enter').click();
     }
});
```
(append this to your theme, also I haven't tested this)

**Comment by byndstd** [comment] 2017-06-30 08:48
hello friend I did try your option but it not working 
I still get the same " guest access to dashboard instead login page ".
isn't there anyway same thing like 
if is not member then ...
I want guest access only to spaces are public directly from space url but not the dashboard

**Comment by byndstd** [comment] 2017-11-18 02:55
is it possible to code that in php file within humhub, I see something like 

 * All users have to be logged in + additional permission check for 'action1' and 'action2':
 *
 * ```php
 * public function getAccessRules()
 * {
 *     return [
 *          ['login'],
 *          ['permission' => MyPermission::class, 'actions' => ['action1', 'action2']]
 *     ];
 * }
 * ```

can I use this function to make access to dashboard for only logged in users

**Comment by buddh4** [comment] 2017-11-26 18:48
The problem is you'll have to overwrite the core controller file, which probably will be overwritten by an update.

**Comment by Ace2213** [comment] 2019-08-24 09:22
I agree, but I don't mind them having access to the dashboard. I find you can use it to advertise the content you want, by pinning public posts in public spaces that will show up permanently on the dashboard.

Personally, I don't like them having access to the lists of members of public spaces.

If you're worried about them signing up, you can turn on admin approval for new registrations, as a work-around.

**Comment by marc-farre** [comment] 2023-12-19 10:23
Could be resolved with https://github.com/humhub/humhub/issues/6765

**Closed** 2023-12-19 14:24 UTC
Labels: Kind:Enhancement, Module:Dashboard
