### ISSUE TITLE
Button widget issues

### ISSUE THREAD

**Issue by ArchBlood** [humhub/humhub#4589] opened 2020-10-29 15:33 UTC
### What steps will reproduce the problem?
Go into the admin section and try to perform a submit action
> `Admin > Custom Pages > edit > Submit`

> `Admin > Settings > Advanced > Caching > Save & Flush Caches`

### What is the expected result?
The action should submit and save

### What do you get instead?
Continuous loading and no errors showing

### Additional info
Using `<?= Html::submitButton('Submit', ['class' => 'btn btn-primary']) ?>` & <br>`<?= Html::submitButton(Yii::t('AdminModule.settings', 'Save & Flush Caches'), ['class' => 'btn btn-primary']) ?>` fixed this issue for the Custom Pages module & Admin section for flushing caches
| Q                | A
| ---------------- | ---
| HumHub version   | 1.7-beta.2
| PHP version      | 7.3 & 7.4
| Operating system | CloudLinux

**Comment by buddh4** [comment] 2020-10-29 15:53
Any errors in the javascript log?

**Comment by buddh4** [comment] 2020-10-29 15:56
`Save & Flush Cashes` may take some time, but I could not reproduce both of the cases.

**Comment by ArchBlood** [comment] 2020-10-29 16:04
Got no JavaScript errors other than invalid notification tokens which has been fixed as for wait time, I let it run for up to an hour without any change

**Comment by luke-** [comment] 2020-10-30 09:16
@ArchBlood Can you check if the "Cache Flush" HTTP request is running in the Network tab of the browser console? We need to determine whether it is a problem in the frontend or backend (e.g. endless loop).

**Comment by ArchBlood** [comment] 2020-10-30 09:44
@luke-  Only thing happening in the Network tab for `Button::primary()`
![Screenshot_1](https://user-images.githubusercontent.com/35392110/97689591-2ee0a400-1a72-11eb-9c7c-89fd36b5d021.png)

Using `Html::submitButton()` gives me this
![Screenshot_2](https://user-images.githubusercontent.com/35392110/97690003-c645f700-1a72-11eb-8b74-e27907659374.png)

**Comment by buddh4** [comment] 2020-10-30 10:01
The only difference between the both buttons is that one has a loader and the other has not. We did not change anything with the loader logic so I assume something in your environment may interfer with the loader logic. I'am not sure what this could be. Maybe setup a test environment without any installed modules and check which module/customization could be the problem.

**Comment by ArchBlood** [comment] 2020-10-30 11:01
> Which Browser/Operating System are you using?

At the moment I'm using CloudLinux server side, on the latest version of Chrome on Windows 8.1

**Comment by ArchBlood** [comment] 2020-10-30 12:31
What I find weird is that this didn't happen in 1.7-beta.1 just randomly started happening in 1.7-beta.2 after updating and the only thing that I'm seeing from my end is that poll requests are continuously being made during the flush process where as with the `Html::submitButton()` option flushes everything as intended :thinking:

**Comment by buddh4** [comment] 2020-10-30 13:08
Do you have issues with other loader buttons?

**Comment by ArchBlood** [comment] 2020-10-30 13:44
Only buttons that are from the admin area that deal with submitting like from the Custom Pages module, Profile fields and of course the cache flush button

**Comment by buddh4** [comment] 2020-10-30 15:24
After clearing the cache, the assets have to be rebuilt which can also take some time. So both action are potentially long running, maybe try to wait for some time. As I mentioned, there were no changes in 1.7 regarding loader button and I did not manage to recreate the issue (I've flushed the cache of my test enviornment pretty often in the last few days).

**Comment by ArchBlood** [comment] 2020-10-30 16:12
I'll continue monitoring this just in case

**Comment by ArchBlood** [comment] 2020-10-30 16:24
As for the only issues that the Console shows :thinking:
![Screenshot_1](https://user-images.githubusercontent.com/35392110/97730829-be09ae00-1aaa-11eb-8fb7-6ce55f849746.png)

**Comment by buddh4** [comment] 2020-10-30 16:26
What do you see if you click on the `VM7 dashboard:570` seems like an inline script is failing.

**Comment by ArchBlood** [comment] 2020-10-30 16:36
I see the following

#### dashboard:3
```logs
No resource with given URL found
```
#### VM14 index:604
```js
jQuery(function ($) {
            
            if (!firebase.apps.length) {     
                firebase.initializeApp({messagingSenderId: "284078925011"});
                const messaging = firebase.messaging();
                
                messaging.onMessage(function(payload) {
                  console.log("FCM Notification received: ", payload);
                });
                
                // Callback fired if Instance ID token is updated.
                messaging.onTokenRefresh(function() {
                  messaging.getToken().then(function(refreshedToken) {
                    setTokenSentToServer('');
                    sendTokenToServer(refreshedToken);
                  }).catch(function(err) {
                    console.log('Unable to retrieve refreshed token ', err);
                  });
                });
                
                function afterServiceWorkerRegistration(registration) {
                    messaging.useServiceWorker(registration);
                        
                    // Request for permission
                    messaging.requestPermission().then(function() {
                      console.log('Notification permission granted.');
                    
                      messaging.getToken().then(function(currentToken) {
                        if (currentToken) {
                          console.log('Token: ' + currentToken);
                          sendTokenToServer(currentToken);
                        } else {
                          console.log('No Instance ID token available. Request permission to generate one.');
                          setTokenSentToServer('');
                        }
                      })
                      .catch(function(err) {
                        console.log('An error occurred while retrieving token. ', err);
                        setTokenSentToServer('');
                      });
                    })
                    .catch(function(err) {
                      // e.g. Igonito Mode  
                      //console.log('Unable to get permission to notify.', err);
                    });
                }                
            }
                
            // Send the Instance ID token your application server, so that it can:
            // - send messages back to this app
            // - subscribe/unsubscribe the token from topics
            function sendTokenToServer(currentToken) {
                  if (!isTokenSentToServer(currentToken)) {
                    console.log('Sending token to server...');
                    $.ajax({
                      method: "POST",
                      url: "/fcm-push/token/update",
                      data: { token: currentToken },
                      success: function(data) {
                        setTokenSentToServer(currentToken);
                      }           
                    });
                  } else {
                    console.log('Token already sent to server so won\'t send it again unless it changes');
                  }
            }
        
            function isTokenSentToServer(token) {
                return (window.localStorage.getItem('sentFcmToken') == token);
            }
        
            function setTokenSentToServer(token) {
                window.localStorage.setItem('sentFcmToken', token);
            }
            if ('serviceWorker' in navigator) {
                navigator.serviceWorker.register('/sw.js?v=1604075301', { scope: '/' })
                    .then(function (registration) {
                        if (typeof afterServiceWorkerRegistration === "function") { 
                            afterServiceWorkerRegistration(registration);
                        }
                    })
            }
}); // yellowed
```

**Comment by buddh4** [comment] 2020-10-30 16:45
Could you rather make a screenshot? When clicking on the link it should highlight a line in you document.

**Comment by buddh4** [comment] 2020-10-30 18:36
Maybe try to reproduce it on a fresh HumHub installation without customatations etc. I'll close it for now, in case you have some further infos I'll reopen the issue.

**Closed by buddh4** 2020-10-30 18:36 UTC
Labels: Kind:BUG, Status:Unable to reproduce

**Comment by ArchBlood** [comment] 2020-11-12 18:36
So now the only issue here is for the Custom Pages module it seems, clearing cache is rather long as well since the update to v1.7 :thinking:

**Comment by buddh4** [comment] 2020-11-13 11:48
Please access the network tab of your browser console, clear all recent requests and click the button you have problems with and check if just the request takes very long or no request is sent at all.

**Comment by ArchBlood** [comment] 2020-11-16 18:40
Loading on save just hangs for the Custom Pages module with a lot of poll requests for humhub-app.js

![Screenshot_1](https://user-images.githubusercontent.com/35392110/99293621-e87c9a80-2810-11eb-99ff-494a2cc01ff8.png)

**Comment by buddh4** [comment] 2020-11-16 18:47
Sorry, I can't reproduce it, did you resolve all errors in the browser console? Can you reproduce this on a clean installation without customization?

**Comment by ArchBlood** [comment] 2020-11-16 19:23
I'm thinking it might be a migration that passed through that shouldn't have I'll have a look into it :thinking:

**Comment by ArchBlood** [comment] 2020-11-17 18:25
I removed the module completely then reinstalled with the same conclusion [`Button::save()`](https://github.com/humhub/humhub-modules-custom-pages/blob/master/views/common/edit.php#L97) does not save on edit whereas `Html::submitButton()` does exactly what is needed the same thing happens on a fresh install and latest version of the module as well :thinking:

**Comment by buddh4** [comment] 2020-11-17 18:45
Do you have any other customization or non official modules installed? Does this happen for all custom page types?

**Comment by ArchBlood** [comment] 2020-11-17 20:56
No customizations, only modules installed are @greenmeteor or official modules and this happens where ever the edit option is located, I've also tried no modules other than the Custom Pages with the edit view still not saving on click just hangs on loading

**Comment by buddh4** [comment] 2020-11-18 11:41
Did you fix all errors logged to the browser console? Sorry hard for me to help, as I said I could not recreate this and there were no changes related to this in 1.7, so somehow I still assume its an issue with your environment or other modules.

**Comment by ArchBlood** [comment] 2020-11-18 15:25
No errors display in the browser only issue I'm seeing is with loading the `humhub.app.js`

**Comment by buddh4** [comment] 2020-11-18 16:04
Which kind of issue? If `humhub.app.js` does not load almost nothing should work?

**Comment by ArchBlood** [comment] 2020-11-18 16:32
Only have the issue loading `humhub.app.js` is when using the Button widget

**Comment by ArchBlood** [comment] 2020-11-18 16:46
I think I found the issue I disabled an older version of [E-Mail Whitelist](https://www.humhub.com/en/marketplace/email-whitelist/) and it seems to be working for now
