### ISSUE TITLE
Markdown Profile field shows contents of a different user when editing

### ISSUE THREAD

**Issue by bottin-vdi** [humhub/humhub#7044] opened 2024-05-31 15:07 UTC
### What steps will reproduce the problem?

Add a new profile category. Add a markdown profile field to the category. Make it searchable and visible.

Edit a user's markdown profile field and save it. Then edit the same markdown profile field on a different user (e.g. as admin or by logging in as the second user). The markdown field editor is prefilled with the data from the first user or the user who last edited that field (possibly disclosing information that should not be visible to the user who is editing).

### What is the expected result?

The markdown field editor should be prefilled with the correct value from the correct user profile.

### What do you get instead?

The markdown editor value contains the profile field value of a different user when editing.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.15.5
| PHP version      | 8.1
| Operating system | Windows / Linux

**Comment by ArchBlood** [comment] 2024-05-31 15:34
@luke- I can confirm the issue, even in v.16, it doesn't display the markdown field edited on the second user account about section though. Maybe cache related or handling of backend saving?

**Comment by yurabakhtin** [comment] 2024-06-03 07:22
@luke- Fixed in the PR https://github.com/humhub/humhub/pull/7045.
The value was stored in Sessions, because it works for all RichText/Prosemirror editors with id by default:

![cache-prosemirror](https://github.com/humhub/humhub/assets/6995524/ced8560c-916c-439a-848b-0b8b71068473)

I.e. user saw value of another user only if relogin in the same browser without closing it.

**Closed** 2024-06-03 07:56 UTC
Labels: Kind:BUG
