### ISSUE TITLE
Could not create url for content exception

### ISSUE THREAD

**Issue by disheltCiti** [humhub/humhub#2047] opened 2016-10-25 17:09 UTC
Hi, in main page, latest activities are loading, but never do. The complete trace is 
`exception 'yii\base\Exception' with message 'Could not create url for content!' in /var/www/html/humhub/protected/humhub/modules/content/models/Content.php:497`

Is there a solution?

Regards

**Comment by buddha87** [comment] 2016-10-26 12:43
Hi, please run the following command within the protected directory of your humhub installation:

`php yii integrity/run`

**Comment by disheltCiti** [comment] 2016-10-26 14:42
Thanks for answer, the output is:

`*** Performing database integrity checks

Validating: Polls Module - Answers (0 entries)
Validating: Polls Module - Answers User (0 entries)
Validating: Activity Module (7 entries)
Validating: Comment Module (0 entries)
Validating: Content Module - Wall Entries 8 entries)
Validating: Content Objects (8 entries)
Validating: File Module (0 entries)
Validating: Like (0 entries)
Validating: Notification Module (0 entries)
Validating: Space Module - Spaces (1 entries)
Validating: Space Module - Module (5 entries)
Validating: Space Module - Memberships (6 entries)
Validating: User Module - Users (6 entries)
Validating: User Module - Password (6 entries)
Validating: User Module - Profile (6 entries)
Validating: User Module - Mentioning (0 entries)
Validating: User Module - Follow (1 entries)
Validating: User Module - Modules (0 entries)

*** All integrity checks done
`

**Comment by eddiepiazza** [comment] 2016-10-28 10:16
Same problem... and I tryed all... My Humhub version is 1.1.1

I get this answere from php yii integrity/run command:

`bash-4.1# php yii integrity/run *** Performing database integrity checks Validating: ReportContent Module (0 entries) Validating: Activity Module (189 entries) Validating: Comment Module (6 entries) Validating: Content Module - Wall Entries 211 entries) Validating: Content Objects (225 entries) Validating: File Module (24 entries) Validating: Like (10 entries) Validating: Notification Module (57 entries) Validating: Space Module - Spaces (6 entries) Validating: Space Module - Module (18 entries) Deleting space module 2 without existing space! (yes|no) [no]:`

I tiped "yes" and:

`Deleting space module 2 without existing space! (yes|no) [no]:yes Exception 'yii\db\Exception' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away The SQL being executed was: DELETE FROM `space_module` WHERE `id`=2' in /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/db/Schema.php:633 Error Info: Array ( [0] => HY000 [1] => 2006 [2] => MySQL server has gone away ) Stack trace: #0 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/db/Command.php(854): yii\db\Schema->convertException(Object(PDOException), 'DELETE FROM `sp...') #1 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(262): yii\db\Command->execute() #2 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(610): yii\db\ActiveRecord::deleteAll(Array) #3 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(573): yii\db\ActiveRecord->deleteInternal() #4 /home/opengrow/public_html/es/community/protected/humhub/modules/space/Events.php(98): yii\db\ActiveRecord->delete() #5 [internal function]: humhub\modules\space\Events::onIntegrityCheck(Object(yii\base\Event)) #6 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Event.php(205): call_user_func(Array, Object(yii\base\Event)) #7 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Component.php(549): yii\base\Event::trigger(Object(humhub\commands\IntegrityController), 'run', NULL) #8 /home/opengrow/public_html/es/community/protected/humhub/commands/IntegrityController.php(39): yii\base\Component->trigger('run') #9 [internal function]: humhub\commands\IntegrityController->actionRun() #10 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #11 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)`

All seems in the same...

I uninstalled few modules but there are some I can´t like cusom pages because of all created pages we have in our site.

An other sollution ?

**Comment by buddha87** [comment] 2016-10-28 10:26
@eddiepiazza  what happens if you run the integrity check again, seems your database timed out before it finished resolving your issues since there are a ton of integrity problems.

**Comment by disheltCiti** [comment] 2016-10-28 15:34
I couldn't fix it. I installed it again.

**Comment by eddiepiazza** [comment] 2016-10-28 16:43
I tryed again and:

Validating: ReportContent Module (0 entries)
Validating: Activity Module (189 entries)
Validating: Comment Module (6 entries)
Validating: Content Module - Wall Entries 211 entries)
Validating: Content Objects (225 entries)
Validating: File Module (24 entries)
Validating: Like (10 entries)
Validating: Notification Module (57 entries)
Validating: Space Module - Spaces (6 entries)
Validating: Space Module - Module (16 entries)
Deleting space module 2 without existing space! (yes|no) [no]:y
Deleting space module 3 without existing space! (yes|no) [no]:yes
Deleting space module 4 without existing space! (yes|no) [no]:yes
Deleting space module 5 without existing space! (yes|no) [no]:yes
Deleting space module 6 without existing space! (yes|no) [no]:y
Deleting space module 9 without existing space! (yes|no) [no]:y
Deleting space module 10 without existing space! (yes|no) [no]:y
Deleting space module 11 without existing space! (yes|no) [no]:y
Deleting space module 12 without existing space! (yes|no) [no]:y
Deleting space module 13 without existing space! (yes|no) [no]:y
Deleting space module 14 without existing space! (yes|no) [no]:y
Deleting space module 15 without existing space! (yes|no) [no]:y
Deleting space module 16 without existing space! (yes|no) [no]:y
Deleting space module 17 without existing space! (yes|no) [no]:y
Deleting space module 18 without existing space! (yes|no) [no]:y
Validating: Space Module - Memberships (136 entries)
yValidating: User Module - Users (49 entries)
Validating: User Module - Password (51 entries)
Validating: User Module - Profile (49 entries)

Validating: User Module - Mentioning (0 entries)
Validating: User Module - Follow (55 entries)
yValidating: User Module - Modules (7 entries)
Deleting user-module 2 of non existing user! (yes|no) [no]:Deleting user-module 3 of non exi
sting user! (yes|no) [no]:y
Deleting user-module 3 of non existing user! (yes|no) [no]:y
Deleting user-module 7 of non existing user! (yes|no) [no]:y
Deleting user-module 8 of non existing user! (yes|no) [no]:y
Deleting user-module 10 of non existing user! (yes|no) [no]:y
Deleting user-module 11 of non existing user! (yes|no) [no]:y


After final time and:

Validating: ReportContent Module (0 entries)
Validating: Activity Module (189 entries)
Validating: Comment Module (6 entries)
Validating: Content Module - Wall Entries 211 entries)
Validating: Content Objects (225 entries)
Validating: File Module (24 entries)
Validating: Like (10 entries)
Validating: Notification Module (57 entries)
Validating: Space Module - Spaces (6 entries)
Validating: Space Module - Module (16 entries)
Deleting space module 2 without existing space! (yes|no) [no]:y
Deleting space module 3 without existing space! (yes|no) [no]:yes
Deleting space module 4 without existing space! (yes|no) [no]:yes
Deleting space module 5 without existing space! (yes|no) [no]:yes
Deleting space module 6 without existing space! (yes|no) [no]:y
Deleting space module 9 without existing space! (yes|no) [no]:y
Deleting space module 10 without existing space! (yes|no) [no]:y
Deleting space module 11 without existing space! (yes|no) [no]:y
Deleting space module 12 without existing space! (yes|no) [no]:y
Deleting space module 13 without existing space! (yes|no) [no]:y
Deleting space module 14 without existing space! (yes|no) [no]:y
Deleting space module 15 without existing space! (yes|no) [no]:y
Deleting space module 16 without existing space! (yes|no) [no]:y
Deleting space module 17 without existing space! (yes|no) [no]:y
Deleting space module 18 without existing space! (yes|no) [no]:y
Validating: Space Module - Memberships (136 entries)
yValidating: User Module - Users (49 entries)
Validating: User Module - Password (51 entries)
Validating: User Module - Profile (49 entries)

Validating: User Module - Mentioning (0 entries)
Validating: User Module - Follow (55 entries)
yValidating: User Module - Modules (7 entries)
Deleting user-module 2 of non existing user! (yes|no) [no]:Deleting user-module 3 of non exi
sting user! (yes|no) [no]:y
Deleting user-module 3 of non existing user! (yes|no) [no]:y
Deleting user-module 7 of non existing user! (yes|no) [no]:y
Deleting user-module 8 of non existing user! (yes|no) [no]:y
Deleting user-module 10 of non existing user! (yes|no) [no]:y
Deleting user-module 11 of non existing user! (yes|no) [no]:y

*** All integrity checks done

opengrow@ukss8 [~/public_html/es/community/protected]# y
-bash: y: command not found
opengrow@ukss8 [~/public_html/es/community/protected]# php yii integrity/run

*** Performing database integrity checks

Validating: ReportContent Module (0 entries)
Validating: Activity Module (189 entries)
Validating: Comment Module (6 entries)
Validating: Content Module - Wall Entries 211 entries)
Validating: Content Objects (225 entries)
Validating: File Module (24 entries)
Validating: Like (10 entries)
Validating: Notification Module (57 entries)
Validating: Space Module - Spaces (6 entries)
Validating: Space Module - Module (1 entries)
Validating: Space Module - Memberships (136 entries)
Validating: User Module - Users (49 entries)
Validating: User Module - Password (51 entries)
Validating: User Module - Profile (49 entries)
Validating: User Module - Mentioning (0 entries)
Validating: User Module - Follow (55 entries)
Validating: User Module - Modules (1 entries)

**Comment by eddiepiazza** [comment] 2016-10-28 17:20
I did all, I also uninstalled some modules and Last Activities still not working for users.

The strange thing is that for Admins is perfectly working...

**Comment by eddiepiazza** [comment] 2016-11-03 18:41
Really, after few days fighting with this still not working!

Some ideas ??

**Comment by buddha87** [comment] 2016-11-04 11:05
Can you post the full error stack "Administration -> Information -> Logging".
Do you have any non official modules installed?

**Comment by eddiepiazza** [comment] 2016-11-04 16:56
INFO  Thu, 03 Nov 2016 18:38:50 +0000  application
$_GET = [ 'limit' => '10' 'from' => '' 'mode' => 'activity' ] $_SERVER = [ 'CONTEXT_DOCUMENT_ROOT' => '/home/opengrow/public_html/es/community' 'CONTEXT_PREFIX' => '' 'DOCUMENT_ROOT' => '/home/opengrow/public_html/es/community' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'HTTP_ACCEPT' => 'application/json, text/javascript, */*; q=0.01' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch' 'HTTP_ACCEPT_LANGUAGE' => 'es,en-GB;q=0.8,en;q=0.6,fr;q=0.4,pt-PT;q=0.2,pt;q=0.2' 'HTTP_CONNECTION' => 'keep-alive' 'HTTP_COOKIE' => '_csrf=1ee6516c8e8bacb1440d755f63f78668a235cd495b633c03869c6afc55b2f186a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22gpuqeQrz_zfYQbM1kHoDY-IbfJxF_wqP%22%3B%7D; _gat=1; pm_getting-started-panel=expanded; language=171f215eabfc3ad44c23b882291a1fc4f46e59efc26e0a3ea46fdf298dbc9952a%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A2%3A%22es%22%3B%7D; PHPSESSID=577686a52d2ed0a1d07ef16c7b91dfd8; _ga=GA1.2.1583317483.1478197846; _identity=21fdb0330b5ce19bcfa79f3dffd5149f3827c73bff7041218d69d5e994f49578a%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A50%3A%22%5B4%2C%223e8b6b5f-8c80-403e-a889-daf1367b36be%22%2C2592000%5D%22%3B%7D' 'HTTP_HOST' => 'www.gropedia.com' 'HTTP_MOD_REWRITE' => 'On' 'HTTP_REFERER' => 'http://www.gropedia.com/' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36' 'HTTP_X_CSRF_TOKEN' => 'cWkwUENrbi4WGUUhJjocVC4TVgkSCSMfGiFfFBpGJ0wXI0gWHBwffg==' 'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest' 'PATH' => '/bin:/usr/bin' 'QUERY_STRING' => 'limit=10&from=&mode=activity' 'REDIRECT_HTTP_MOD_REWRITE' => 'On' 'REDIRECT_QUERY_STRING' => 'limit=10&from=&mode=activity' 'REDIRECT_STATUS' => '200' 'REDIRECT_UNIQUE_ID' => 'WBuEOiU97MUADiG-cicAAAAD' 'REDIRECT_URL' => '/dashboard/dashboard/stream' 'REMOTE_ADDR' => '188.82.113.52' 'REMOTE_PORT' => '54717' 'REQUEST_METHOD' => 'GET' 'REQUEST_SCHEME' => 'http' 'REQUEST_URI' => '/dashboard/dashboard/stream?limit=10&from=&mode=activity' 'SCRIPT_FILENAME' => '/home/opengrow/public_html/es/community/index.php' 'SCRIPT_NAME' => '/index.php' 'SERVER_ADDR' => '37.61.236.197' 'SERVER_ADMIN' => 'webmaster@gropedia.open-grow.co.uk' 'SERVER_NAME' => 'www.gropedia.com' 'SERVER_PORT' => '80' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'SERVER_SIGNATURE' => '' 'SERVER_SOFTWARE' => 'Apache' 'UNIQUE_ID' => 'WBuEOiU97MUADiG-cicAAAAD' 'PHP_SELF' => '/index.php' 'REQUEST_TIME_FLOAT' => 1478198330.1194 'REQUEST_TIME' => 1478198330 'argv' => [ 0 => 'limit=10&from=&mode=activity' ] 'argc' => 1 ]




ERROR  Thu, 03 Nov 2016 18:38:50 +0000  yii\base\Exception
exception 'yii\base\Exception' with message 'Could not create url for content!' in /home/opengrow/public_html/es/community/protected/humhub/modules/content/models/Content.php:497 Stack trace: #0 /home/opengrow/public_html/es/community/protected/humhub/components/SocialActivity.php(95): humhub\modules\content\models\Content->getUrl() #1 /home/opengrow/public_html/es/community/protected/humhub/components/SocialActivity.php(78): humhub\components\SocialActivity->getUrl() #2 /home/opengrow/public_html/es/community/protected/humhub/modules/activity/components/BaseActivity.php(72): humhub\components\SocialActivity->getViewParams(Array) #3 /home/opengrow/public_html/es/community/protected/humhub/libs/Viewable.php(89): humhub\modules\activity\components\BaseActivity->getViewParams(Array) #4 /home/opengrow/public_html/es/community/protected/humhub/modules/content/activities/ContentCreated.php(43): humhub\libs\Viewable->render('web', Array) #5 /home/opengrow/public_html/es/community/protected/humhub/modules/activity/models/Activity.php(96): humhub\modules\content\activities\ContentCreated->render() #6 /home/opengrow/public_html/es/community/protected/humhub/modules/content/components/actions/Stream.php(264): humhub\modules\activity\models\Activity->getWallOut() #7 [internal function]: humhub\modules\content\components\actions\Stream->run() #8 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Action.php(92): call_user_func_array(Array, Array) #9 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\Action->runWithParams(Array) #10 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('stream', Array) #11 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/web/Application.php(87): yii\base\Module->runAction('dashboard/dashb...', Array) #12 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #13 /home/opengrow/public_html/es/community/index.php(25): yii\base\Application->run() #14 {main}




INFO  Thu, 03 Nov 2016 18:31:19 +0000  application
$_GET = [ 'limit' => '10' 'from' => '' 'mode' => 'activity' ] $_SERVER = [ 'CONTEXT_DOCUMENT_ROOT' => '/home/opengrow/public_html/es/community' 'CONTEXT_PREFIX' => '' 'DOCUMENT_ROOT' => '/home/opengrow/public_html/es/community' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'HTTP_ACCEPT' => 'application/json, text/javascript, */*; q=0.01' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch' 'HTTP_ACCEPT_LANGUAGE' => 'es,en-GB;q=0.8,en;q=0.6,fr;q=0.4,pt-PT;q=0.2,pt;q=0.2' 'HTTP_CONNECTION' => 'keep-alive' 'HTTP_COOKIE' => '_csrf=1ee6516c8e8bacb1440d755f63f78668a235cd495b633c03869c6afc55b2f186a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22gpuqeQrz_zfYQbM1kHoDY-IbfJxF_wqP%22%3B%7D; _gat=1; pm_getting-started-panel=expanded; language=171f215eabfc3ad44c23b882291a1fc4f46e59efc26e0a3ea46fdf298dbc9952a%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A2%3A%22es%22%3B%7D; _ga=GA1.2.1583317483.1478197846; PHPSESSID=577686a52d2ed0a1d07ef16c7b91dfd8; _identity=21fdb0330b5ce19bcfa79f3dffd5149f3827c73bff7041218d69d5e994f49578a%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A50%3A%22%5B4%2C%223e8b6b5f-8c80-403e-a889-daf1367b36be%22%2C2592000%5D%22%3B%7D' 'HTTP_HOST' => 'www.gropedia.com' 'HTTP_MOD_REWRITE' => 'On' 'HTTP_REFERER' => 'http://www.gropedia.com/' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36' 'HTTP_X_CSRF_TOKEN' => 'NllaU1V2eGhRKS8iMCcKEmkjPAoEFDVZXRE1FwxbMQpQEyIVCgEJOA==' 'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest' 'PATH' => '/bin:/usr/bin' 'QUERY_STRING' => 'limit=10&from=&mode=activity' 'REDIRECT_HTTP_MOD_REWRITE' => 'On' 'REDIRECT_QUERY_STRING' => 'limit=10&from=&mode=activity' 'REDIRECT_STATUS' => '200' 'REDIRECT_UNIQUE_ID' => 'WBuCdyU97MUADe0QjPgAAABv' 'REDIRECT_URL' => '/dashboard/dashboard/stream' 'REMOTE_ADDR' => '188.82.113.52' 'REMOTE_PORT' => '56382' 'REQUEST_METHOD' => 'GET' 'REQUEST_SCHEME' => 'http' 'REQUEST_URI' => '/dashboard/dashboard/stream?limit=10&from=&mode=activity' 'SCRIPT_FILENAME' => '/home/opengrow/public_html/es/community/index.php' 'SCRIPT_NAME' => '/index.php' 'SERVER_ADDR' => '37.61.236.197' 'SERVER_ADMIN' => 'webmaster@gropedia.open-grow.co.uk' 'SERVER_NAME' => 'www.gropedia.com' 'SERVER_PORT' => '80' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'SERVER_SIGNATURE' => '' 'SERVER_SOFTWARE' => 'Apache' 'UNIQUE_ID' => 'WBuCdyU97MUADe0QjPgAAABv' 'PHP_SELF' => '/index.php' 'REQUEST_TIME_FLOAT' => 1478197879.9348 'REQUEST_TIME' => 1478197879 'argv' => [ 0 => 'limit=10&from=&mode=activity' ] 'argc' => 1 




INFO  Wed, 02 Nov 2016 21:02:29 +0000  application
$_GET = [ 'limit' => '10' 'from' => '' 'mode' => 'activity' 'sguid' => 'c97244a9-1713-441e-b695-64ee9ccd87d7' ] $_SERVER = [ 'CONTEXT_DOCUMENT_ROOT' => '/home/opengrow/public_html/es/community' 'CONTEXT_PREFIX' => '' 'DOCUMENT_ROOT' => '/home/opengrow/public_html/es/community' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'HTTP_ACCEPT' => 'application/json, text/javascript, */*; q=0.01' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch' 'HTTP_ACCEPT_LANGUAGE' => 'es-ES,es;q=0.8,en;q=0.6' 'HTTP_CONNECTION' => 'keep-alive' 'HTTP_COOKIE' => 'pm_space-members-panel=expanded; _csrf=8fce558c6d1fed80d498415941de1252c08745e8465e4c51ccd3b4bbad72e0c1a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22mGd9Ytrsth1ZZVuntRySfnY6uWlRdpB8%22%3B%7D; PHPSESSID=e636bed57a04f3359991683761fb82b3; pm_getting-started-panel=expanded; _gat=1; _ga=GA1.2.196935349.1478119297' 'HTTP_HOST' => 'www.gropedia.com' 'HTTP_MOD_REWRITE' => 'On' 'HTTP_REFERER' => 'http://www.gropedia.com/s/grow-shops-esp/' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36' 'HTTP_X_CSRF_TOKEN' => 'cUdwUko1S3QcABRrE0E5BwUvQQgQYz4aBRUJASxbEkIEEBwALkUJTA==' 'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest' 'PATH' => '/bin:/usr/bin' 'QUERY_STRING' => 'limit=10&from=&mode=activity' 'REDIRECT_HTTP_MOD_REWRITE' => 'On' 'REDIRECT_QUERY_STRING' => 'limit=10&from=&mode=activity' 'REDIRECT_STATUS' => '200' 'REDIRECT_UNIQUE_ID' => 'WBpUZCU97MUAD3z9STIAAABF' 'REDIRECT_URL' => '/s/grow-shops-esp/space/space/stream' 'REMOTE_ADDR' => '77.227.204.23' 'REMOTE_PORT' => '55694' 'REQUEST_METHOD' => 'GET' 'REQUEST_SCHEME' => 'http' 'REQUEST_URI' => '/s/grow-shops-esp/space/space/stream?limit=10&from=&mode=activity' 'SCRIPT_FILENAME' => '/home/opengrow/public_html/es/community/index.php' 'SCRIPT_NAME' => '/index.php' 'SERVER_ADDR' => '37.61.236.197' 'SERVER_ADMIN' => 'webmaster@gropedia.open-grow.co.uk' 'SERVER_NAME' => 'www.gropedia.com' 'SERVER_PORT' => '80' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'SERVER_SIGNATURE' => '' 'SERVER_SOFTWARE' => 'Apache' 'UNIQUE_ID' => 'WBpUZCU97MUAD3z9STIAAABF' 'PHP_SELF' => '/index.php' 'REQUEST_TIME_FLOAT' => 1478120549.0344 'REQUEST_TIME' => 1478120549 'argv' => [ 0 => 'limit=10&from=&mode=activity' ] 'argc' => 1 ]

**Comment by eddiepiazza** [comment] 2016-11-04 16:56
All my modules are official.

**Comment by eddiepiazza** [comment] 2016-11-04 17:00
And hat is 'webmaster@gropedia.open-grow.co.uk' ?? I didn t configured that mail and also doesn't exist in my server...

**Comment by buddha87** [comment] 2016-11-04 21:48
The email is probably set by your hoster. 

It seems that one of your activities points to an content without an existing wallentry, we'll have to investigate how this can be reproduced.

Please run the following sql and post the result:

`SELECT a.id, a.object_model, a.object_id, c.id FROM activity a, content c WHERE a.object_model = c.object_model AND a.object_id = c.object_id AND not exists (SELECT * FROM wall_entry w where w.content_id = c.id)`

**Comment by eddiepiazza** [comment] 2016-11-07 10:24
![image](https://cloud.githubusercontent.com/assets/8577866/20054320/583a175e-a4d4-11e6-994a-60b677ef790a.png)

**Comment by buddha87** [comment] 2016-11-07 12:27
I would suggest, you make a db backup. Then delete the activities of this sql result. Then again execute the integrity check. Since the wallentry table will be removed in v1.2 this should not happen in the upcoming release, but well try to reproduce this.

**Comment by eddiepiazza** [comment] 2016-11-07 13:23
Can you send me the sql command to delete correct tables ?

**Comment by eddiepiazza** [comment] 2016-11-07 14:02
Problem Solved! It was a conflict somewhere in an activity entry.
Thank you!!!

**Comment by eddiepiazza** [comment] 2016-11-08 12:49
OMG ! I noticed that now after make this process all spaces menus went to hell !!

![image](https://cloud.githubusercontent.com/assets/8577866/20099688/c36d6aca-a5b1-11e6-9b5b-c5a95cb66a3b.png)

**Closed** 2017-04-04 12:39 UTC
Labels: Status:Need investigation
