### ISSUE TITLE
Deleting a user deletes all Wiki-pages etc by the user

### ISSUE THREAD

**Issue by zaughon** [humhub/humhub#1840] opened 2016-07-07 14:39 UTC
Hey. 
Been playing around with this for a few days, and one thing i noticed is that when you disable or delete a user, all their posts, wikipages etc is removed as well. 

If it's meant to be used for teams in companies etc, there should be a way to prevent access for users who may have quit. Currently it looks like it can only be done if you change their password and their mail-address. 

Disabling or deleting the user removes all posts, wiki-pages etc as well. You probably want to keep that knowledge in the company. 
If you remove them from the Space, it stays, but you can no longer update the page. It causes an Exception when you try to save as a different user:

> Exception – yii\base\Exception
> 
> Could not validate associated Content Record! (Array
> (
> [visibility] => Array
> (
> [0] => Insufficent permissions to create content!
> )
> 
> )
> )

**Comment by buddha87** [comment] 2016-07-14 12:50
You are right, for some content it's important to keep it. But in communities there has to be a way to delete all user related data if the user whises so.

**Comment by rondonjon** [comment] 2016-07-17 12:27
I believe that depends on on how the privacy rules of that community have been defined. Many communities (also in Germany) handle it differently and have no legal problems with that.

An often chosen solution is the seperation of PERSONAL data *of* an account from generated CONTENT *by* that account. When a user exists, the former is deleted or anonymized, whereas the latter remains in the community. And that's IMO the only way to go for humbub.

@buddha87 imagine what Wikipedia or a Q&A community with a policy like yours would look like after some dozen, hundred, or thousand users have left: pages and even the whole portal would sooner or later become worthless and unusable.

@zaughon I agree that it would be nice to have this configurable, but IMO it's not a necessity if the default is "reasonable" (which, admittedly, at this time it is NOT)

**Comment by rondonjon** [comment] 2016-07-17 12:30
Possible duplicate of #1312

**Comment by rondonjon** [comment] 2016-07-17 17:32
See also #1252

**Closed** 2019-01-15 08:53 UTC
Labels: Type:Enhancement
