### ISSUE TITLE
Create File URL Download Token Tests

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5026] opened 2021-04-19 14:53 UTC
- Unit Tests for Token Generation (Static Methods) in Download Controller
- Acceptance/FunctionalTests, That DownloadAction Works with Token

PR: https://github.com/humhub/humhub/pull/4995

**Comment by yurabakhtin** [comment] 2021-04-23 08:02
@luke- 

> - Unit Tests for Token Generation (Static Methods) in Download Controller

The unit tests were already implemented and merged here https://github.com/humhub/humhub/pull/5028.

**Comment by yurabakhtin** [comment] 2021-04-23 08:13
@luke- 

> - Acceptance/FunctionalTests, That DownloadAction Works with Token

These tests can be done only after implement this https://github.com/humhub/humhub/issues/4935#issuecomment-822534035 i.e. when new `RichTextToEmailHtmlConverter` will be used in core emails like "New Comment" or "New Content" notifications.

**Comment by luke-** [comment] 2021-04-23 08:48
@yurabakhtin Ok, shall we close the issue here and include additional tests to the other one?

**Comment by yurabakhtin** [comment] 2021-04-23 09:17
@luke- no need to close it, we can continue this after the new `RichTextToEmailHtmlConverter` will be applied as described above, otherwise we can forget to implement the Acceptance/Functional Tests.

**Comment by yurabakhtin** [comment] 2021-04-27 05:32
waiting to merge PR https://github.com/humhub/humhub/pull/5041

**Comment by luke-** [comment] 2021-04-27 10:16
@yurabakhtin is merged!

**Comment by yurabakhtin** [comment] 2021-04-27 16:18
@luke- I have implemented one functional test in PR https://github.com/humhub/humhub/pull/5050 but I didn't find a way to open an image URL from sent email message, I just implemented a comparing that image contains a `token` param in url.

**Comment by yurabakhtin** [comment] 2021-04-28 04:44
The new test is broken here https://github.com/humhub/humhub/runs/2449859359?check_suite_focus=true

**Comment by yurabakhtin** [comment] 2021-04-28 13:27
@luke- I cannot reproduce the bug locally:

<img width="960" alt="test_email_image_token" src="https://user-images.githubusercontent.com/6995524/116411050-01688d80-a83e-11eb-9434-f7060dd3fac1.png">

but I did a small fix in commit https://github.com/humhub/humhub/pull/5050/commits/16a2a7d46522082f169f427547b49a0b7e32409c, probably on the server side email is encoded by some another way, but when I debugged on my local side I saw all email content has some additional chars, e.g. all `="` is converted to `=3D"` and lines are wrapped by `=\r\n`.
So we need to wait the tests execution after the new fix.

**Comment by yurabakhtin** [comment] 2021-04-28 15:24
@luke- My previous fix didn't solve the issue, do you know how to debug what we really have in the email content on the server side? Locally I can debug the string like this:

<img width="2044" alt="debug_test_email" src="https://user-images.githubusercontent.com/6995524/116429391-852a7600-a84e-11eb-9a07-8f8234851fd9.png">

What if we put the `$commentMailText` inside `$I->see('Token is not detected in image URL with content: ' . $commentMailText);`? I think it will not be displayed fully as we have there for html content.

**Comment by luke-** [comment] 2021-04-28 16:37
@yurabakhtin My commit should be fix the problem: https://github.com/humhub/humhub/pull/5050/commits/8d26779447dc2e953c030ae15207670d9efe59f4

**Closed** 2021-04-28 16:38 UTC
Labels: Component:File, Kind:Enhancement

**Comment by yurabakhtin** [comment] 2021-04-29 05:09
@luke- Thank you for the fix!
