### ISSUE TITLE
File upload fail with rename

### ISSUE THREAD

**Issue by nmalservet** [humhub/humhub#625] opened 2015-01-19 10:57 UTC
I had a problem with file upload.
First, i think in the doc , you shoud write that /path/humhub/uploads must be writable.
After, i had a problem with the operation "rename" on line 143 into modules_core/File/File.php : rename($this->cUploadedFile->getTempName(), $newFilename);
The apache log : rename , blablabla, operation not permited.
I had replaced this line 143 by this :
if( copy($this->cUploadedFile->getTempName(), $newFilename) )
                {
                unlink($this->cUploadedFile->getTempName());
                }
And it's works fine.

**Comment by WASasquatch** [comment] 2015-01-19 16:58
https://github.com/humhub/humhub/blob/master/protected/docs/guide/administration/installation.md#installation

It does tell you. What characters were present in the filename when you uploaded it?

**Comment by nmalservet** [comment] 2015-01-19 20:13
thanks WASasquatch.
Theses files made an issue with the rename  function:
"Inventaire outils BIOBANQUE.docx"
"MALSERVET NICOLAS.doc"
"NicolasResponse.docx".
So i think the problem is into the implementation of the rename function.
The message was : 2015/01/19 11:35:39 [error] [php] rename(/private/var/tmp/phpMIs8lh,/Volumes/...../humhub/uploads/file/dc12b2b7-fdab-43c1-b369-e1b73ee6de08/NicolasResponse.docx): Operation not permitted (/Volumes/..../humhub/protected/modules_core/file/models/File.php:143)....
Im' working on Mac OS, the file system hosting this application is "MacOS extended".

**Comment by WASasquatch** [comment] 2015-01-19 22:22
That comma in the temp firectory is probably reeking havoc on the PHP function.

**Comment by nmalservet** [comment] 2015-01-20 08:21
WASasquatch, do you think thi swas the coma at the end of "phpMIs8lh"? I think this was the separator for the arguments of the function rename : http://php.net/manual/fr/function.rename.php

**Comment by WASasquatch** [comment] 2015-01-20 16:57
No, I don't think so, it was the path it was trying to fetch the file to rename it. That comma probably broke it and it was unable to find the file. Like I said, usually tmp dir only renders with a-zA-Z0-9, no other characters.

**Comment by luke-** [comment] 2015-01-22 09:21
@nmalservet Can you try to change 'rename' with 'move_uploaded_file' in https://github.com/humhub/humhub/blob/master/protected/modules_core/file/models/File.php#L143  If this works also - we should use this function.

**Comment by WASasquatch** [comment] 2015-01-22 18:39
Oh well part the problem is you are not using the function correctly. You have to pass the full path to both paramaters

```php
<?php

rename ("/folder/file.ext", "newfile.ext");

?>
```

That doesn't rename the file within the folder, as you might assume, instead, it moves the file to whatever the PHP working directory is... Chances are you'll not find it in your FTP tree. Instead, use the following:

```php
<?php

rename ("/folder/file.ext", "/folder/newfile.ext");

?>
```

**Comment by luke-** [comment] 2015-01-22 20:30
We're using the rename function correctly and always pass the path & filename to it.

I'm still not sure what's the problem...

**Comment by nmalservet** [comment] 2015-01-22 21:03
@luke i tried "move_uploaded_file" but the result is an empty file is stored (0 bytes).
@WASasquatch ok but in the apache log file, there is the full path with the two parameters...
At this time, this solution works for me, on mac and debian : 
'''
if( copy($this->cUploadedFile->getTempName(), $newFilename) )
                {
                unlink($this->cUploadedFile->getTempName());
                }
'''

**Comment by WASasquatch** [comment] 2015-01-23 17:39
Digging further, here is the likely cause:

***PHP Note:*** rename() should be used to move ordinary files, and not files uploaded through a form. The reason for this is because there is a special function, called move_uploaded_file(), which checks to make sure the file has indeed been uploaded before moving it - this stops people trying to hack your server into making private files visible. You can perform this check yourself if you like by calling the is_uploaded_file() function. 

Because of the comma, which probably caused the file to never upload, this is likely the reason for the error.

**Closed** 2015-01-31 04:17 UTC
