### ISSUE TITLE
[Must Change Password] Chrome Android Redirect Loop

### ISSUE THREAD

**Issue by cs8898** [humhub/humhub#6148] opened 2023-03-08 13:36 UTC
### What steps will reproduce the problem?

- propably dependent on fcm plugin, because it loads the manifest.json
- Mark user so that `forceChangePassword()` => true
- Try to login on an Android Phone with Chrome (111.0.5563.57)
- You will be redirected to `/user/must-change-password`

### What is the expected result?

- Page loads one single Time
- manifest.json can be accessed
- sw.js can be accessed
- Request to API/manifest.json/sw.js should never respond with 302 Redirects.
- Ajax should not handle `302` redirects during those calls

### What do you get instead?

- Page reloads infinite times
- By requesting some endpoints the Backend responds with the Redirect to `/user/must-change-password`.
- The Ajax Handler evaluates those redirects and "reloads" the page.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.12.1
| PHP version      |  ????
| Server Operating system | Linux
| Mobile Operating system | Android 13

**Comment by yurabakhtin** [comment] 2023-03-10 08:41
@cs8898 I could not reproduce the issue with the fcp plugin and enabled `forceChangePassword()`.
Probably some other module makes this issue.
If you have a possible could you try to use a fix like:

```php
if (Yii::$app->request->isAjax) {
    // TODO: maybe it should be restricted better, but we don't need to call this for PollController from live module indeed
    return false;
}

if (Yii::$app->user->mustChangePassword()) {
    return false;
}
```

for the method `humhub\modules\fcmPush\Events::onBeforeRequest()`.
We already had a similar issue for the module 2FA, it will be fixed here https://github.com/humhub/twofa/blob/master/Events.php#L55-L62, but as you can we have there the exception because the event trigger has own redirect, and I don't find any redirect from the fcm module, so probably you have some other module with event where a redirect is used, and it would be good to find what code does the redirect.

**Comment by cs8898** [comment] 2023-03-10 10:02
Hi Im currently using following "Workaround"

```diff
diff --git a/protected/humhub/components/access/ManifestAccess.php b/protected/humhub/components/access/ManifestAccess.php
new file mode 100644
index 000000000..aaba8fae6
--- /dev/null
+++ b/protected/humhub/components/access/ManifestAccess.php
@@ -0,0 +1,29 @@
+<?php
+
+/**
+ * @link https://www.humhub.org/
+ * @copyright Copyright (c) 2023 HumHub GmbH & Co. KG
+ * @license https://www.humhub.com/licences
+ */
+
+namespace humhub\components\access;
+
+/**
+ * Class ManifestAccess is responsible to allow Public Access to the Manifest JSON and ServiceWorker JS.
+ *
+ * @since X.XX
+ *
+ * @see ControllerAccess
+ * @see ManifestController
+ * @see ServiceWorkerController
+ * @author cs8898
+ */
+class ManifestAccess extends ControllerAccess
+{
+
+    /**
+     * @var array fixed rules will always be added to the current rule set
+     */
+    protected $fixedRules = [
+    ];
+}
diff --git a/protected/humhub/components/behaviors/AccessControl.php b/protected/humhub/components/behaviors/AccessControl.php
index 954f6fe86..8fa8a19dc 100644
--- a/protected/humhub/components/behaviors/AccessControl.php
+++ b/protected/humhub/components/behaviors/AccessControl.php
@@ -9,6 +9,8 @@
 namespace humhub\components\behaviors;
 
 use humhub\components\access\ControllerAccess;
+use humhub\modules\web\pwa\controllers\ManifestController;
+use humhub\modules\web\pwa\controllers\ServiceWorkerController;
 use Yii;
 use yii\base\ActionFilter;
 use yii\web\HttpException;
@@ -230,7 +232,10 @@ class AccessControl extends ActionFilter
      */
     protected function forceChangePassword()
     {
-        if (!Yii::$app->user->isMustChangePasswordUrl()) {
+        $isMetaRequest = (Yii::$app->controller instanceof ManifestController) ||
+            (Yii::$app->controller instanceof ServiceWorkerController);
+
+        if (Yii::$app->request->isGet && !$isMetaRequest && !Yii::$app->user->isMustChangePasswordUrl()) {
             Yii::$app->getResponse()->redirect([Yii::$app->user->mustChangePasswordRoute]);
         }
     }
diff --git a/protected/humhub/modules/web/pwa/controllers/ManifestController.php b/protected/humhub/modules/web/pwa/controllers/ManifestController.php
index 67955f322..49d6ed876 100644
--- a/protected/humhub/modules/web/pwa/controllers/ManifestController.php
+++ b/protected/humhub/modules/web/pwa/controllers/ManifestController.php
@@ -8,7 +8,7 @@
 
 namespace humhub\modules\web\pwa\controllers;
 
-use humhub\components\access\ControllerAccess;
+use humhub\components\access\ManifestAccess;
 use humhub\components\Controller;
 use humhub\modules\web\pwa\widgets\SiteIcon;
 use humhub\modules\web\Module;
@@ -30,7 +30,7 @@ class ManifestController extends Controller
      *
      * @var string
      */
-    public $access = ControllerAccess::class;
+    public $access = ManifestAccess::class;
 
     /**
      * @var array the manifest
diff --git a/protected/humhub/modules/web/pwa/controllers/ServiceWorkerController.php b/protected/humhub/modules/web/pwa/controllers/ServiceWorkerController.php
index 2f5fbeb34..4f9762b1b 100644
--- a/protected/humhub/modules/web/pwa/controllers/ServiceWorkerController.php
+++ b/protected/humhub/modules/web/pwa/controllers/ServiceWorkerController.php
@@ -8,7 +8,7 @@
 
 namespace humhub\modules\web\pwa\controllers;
 
-use humhub\components\access\ControllerAccess;
+use humhub\components\access\ManifestAccess;
 use humhub\components\Controller;
 use humhub\modules\ui\Module;
 use Yii;
@@ -31,7 +31,7 @@ class ServiceWorkerController extends Controller
      *
      * @var string
      */
-    public $access = ControllerAccess::class;
+    public $access = ManifestAccess::class;
     public $baseJs;
     public $additionalJs;
 ```
 
## Explanation

* The Redirect for `must-change-password` is disabled when one of the PWA Controllers is in use.
* The Redirect is only used for `GET`
  (quiet buggy but should resolve the FCM problem, better way would be, that FCM only Registers when on Dashboard)
* Another Access class is introduced, namely `ManifestAccess`
  * Main Difference is the Rule Set, that is Empty (actually don't know if that is correct, but it seems working)
  * Probably removing `[self::RULE_MUST_CHANGE_PASSWORD],` is enough.
  
  The fork is at <https://github.com/Schmied-IT/humhub>

**Comment by yurabakhtin** [comment] 2023-03-21 09:38
@cs8898 Could you please check the PR https://github.com/humhub/humhub/pull/6186 does what you need? Thanks.

**Closed** 2024-08-04 11:47 UTC
Labels: Status:Need investigation
