### ISSUE TITLE
add rtl for arabic langu and font size

### ISSUE THREAD

**Issue by asemasran** [humhub/humhub#1640] opened 2016-04-13 10:35 UTC
Hello
This program is really very cool and I used it to my organization
I want to help
I want to Add
rtl Arabic language
And change the font size and color

**Comment by luke-** [comment] 2016-04-14 15:05
Sounds great, what changes are necessary for RTL support?
Arabic language itself should already be supported.

You can help with translations at http://translate.humhub.org

**Comment by buddh4** [comment] 2018-07-12 21:45
Duplicate of https://github.com/humhub/humhub/issues/871

**Closed by buddh4** 2018-07-12 21:45 UTC
Labels: Type:Enhancement

**Comment by FikriSami** [comment] 2021-12-17 12:09
هذا مثال للكتابة باللغة العربية
This is an example of writing in Arabic
Hi everybody
I am really disappointed that RTL is still not possible for posts and comments in Humhum spaces and profiles.
We are approaching 2022
Don't you think it is time you included full text editing options such as alignment and text color?
I would really appreciate it if this is included soon. I created a personal network page to gather my friends from facebook, but many of them are hesitating because the arabic text is left-aligned :(
Thanks in advance
With kind regards
Fikri
