### ISSUE TITLE
Profile space with filter "Show all content" includes content of archived spaces

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#4626] opened 2020-11-11 15:48 UTC
- Create Post on Space x
- Archive Space x
- Access user profile

Expected:

Post should not be included in stream.

Actual:

Post is included in stream.

**Comment by buddh4** [comment] 2021-02-16 16:57
Related to https://github.com/humhub/humhub/issues/3968

**Comment by buddh4** [comment] 2021-02-16 17:55
Cases to test:

- [ ] Profile with contributions without `Archived` filter -> exclude archived content + archived container
- [ ] Profile with contributions with `Archived` filter -> only include archived content + archived container
- [ ] Profile without contributions without `Archived` filter -> only include non archived content of profile
- [ ] Profile without contributions with `Archived` filter -> only include archived content or profile
- [ ] Space without `Archived` filter -> exclude archived content
- [ ] Space with `Archived` filter -> show only archived content
- [ ] Archived Space -> show all content, archive filters hould be disabled
- [ ] Dashboard without `Archived` filter -> exclude archived cotnent + archived container
- [ ] Dashboard with `Archived` filter -> only include archived cotnent + archived container

**Comment by yurabakhtin** [comment] 2021-04-12 09:47
@luke- I could not reproduce this, branch `master`, version `1.8.2 (Unreleased)`, last fix is "- Fix #5002: Fix loading of fixture spaces on tests":

<img width="864" alt="test_archived" src="https://user-images.githubusercontent.com/6995524/114375067-f995c180-9b8c-11eb-9693-150e0a71defb.png">

**Comment by luke-** [comment] 2021-04-13 12:26
@yurabakhtin I can reproduce the problem on the `master` branch. It is important that the whole Space is archived and not just the individual post.

**Comment by yurabakhtin** [comment] 2021-04-13 15:47
@luke- Yes, I agree my previous tests were wrong, I had to test archived Space as descried in first message here.
Fixed in PR https://github.com/humhub/humhub/pull/5011.

> Did you tested the other cases? We may add tests for such edge cases.

No, I tested only the case from first message https://github.com/humhub/humhub/issues/4626#issue-740869939.
Do you mean I should tests all the cases from the comment https://github.com/humhub/humhub/issues/4626#issuecomment-780012939?

**Comment by luke-** [comment] 2021-04-13 15:51
@yurabakhtin It would be good to have codeception tests for all these cases. https://github.com/humhub/humhub/issues/4626#issuecomment-780012939

The issue is not urgent and I would also merge it against the Develop Branch.

**Comment by yurabakhtin** [comment] 2021-04-13 16:01
@luke- 

> The issue is not urgent and I would also merge it against the Develop Branch.

Ok, I changed the base to `develop`.

**Comment by yurabakhtin** [comment] 2021-04-16 08:51
@luke- 

> It would be good to have codeception tests for all these cases. https://github.com/humhub/humhub/issues/4626#issuecomment-780012939

I have implemented some tests in commit https://github.com/humhub/humhub/pull/5011/commits/b4931cf4b29942ee53bde2b75a1a78b7b3bf10e7, but I don't understand what means the "contributions" in "Profile with/without contributions", is it some content created only on profile stream?
Also I don't find how to filter Dashboard by archived content because Dashboard has no filters panel and we can see only not archived content there always.

**Comment by luke-** [comment] 2021-04-16 10:23
@yurabakhtin Thank you! The filters on the dashboard are only displayed when the following option is enabled.
![image](https://user-images.githubusercontent.com/4736168/115010693-fca2f180-9ead-11eb-9ac8-64f691ebe9d4.png)
We may show also the filters without this option in the future.

I think "Profile with/without contributions" means following option:
![image](https://user-images.githubusercontent.com/4736168/115010986-5f948880-9eae-11eb-8beb-f03825e86f72.png)

**Comment by yurabakhtin** [comment] 2021-04-16 14:03
@luke- 

> The filters on the dashboard are only displayed when the following option is enabled.

Thanks for the info, I have added a test for this filters panel on dashboard - https://github.com/humhub/humhub/pull/5011/commits/8f7227c0f4b009f99921fd89486f35e535871197#diff-e2845172f8904cbdb1c4dfedaf94c3d179e8aeea2fd00083b126390eade04082R117

> I think "Profile with/without contributions" means following option:

Ok, but it is not related to the issue with "Archived" filter, or do you think I should add some test for this option? If no, then all done here.

**Comment by luke-** [comment] 2021-04-16 15:55
@yurabakhtin Thanks! This should be enough testing cases!

**Closed by luke-** 2021-04-16 15:55 UTC
Labels: Kind:BUG
